<?php $results['pageTitle'] = "Iansã | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
			<img class="card-img-top" src="images/iansa.jpg" alt="Card image cap">
				<h2 class="card-title"><center>IANSÃ</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na &Aacute;frica &eacute; conhecida apenas como Oy&aacute;, que vem a ser o mesmo nome do rio mais importante da Nig&eacute;ria, o N&iacute;ger. Apesar de seu nome original ter vindo do rio, isto n&atilde;o deve confundir seu elemento que &eacute; o vento. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O nome Ians&atilde; tem uma origem curiosa. Ians&atilde; teve diversos maridos, entre eles Obalua&ecirc;, que lhe deu o poder de encaminhar os esp&iacute;ritos dos mortos (eguns) cada qual para seu destino correto no orun (c&eacute;u). </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na cren&ccedil;a africana o al&eacute;m era composto por 9 espa&ccedil;os, onde os mortos poderiam ser alocados de acordo com seu adiantamento. Estes nove c&eacute;us iam desde o mais tenebroso limbo at&eacute; o mais prodigioso para&iacute;so. Pelo dom que recebeu de Obalua&ecirc;, cabe a Ians&atilde; encaminhar os esp&iacute;ritos dos mortos para seu orun adequado. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Por esse atributo, a orix&aacute; ficou conhecida como Oy&aacute; Mesan Orun, ou Oy&aacute; dos Nove C&eacute;us. No Brasil, com o tempo, passou a ser chamada apenas de Oy&aacute; Mesan (m&atilde;e dos nove) e, depois de mais algum tempo, popularmente e por contra&ccedil;&atilde;o, passou a ser &lsquo;Oy&aacute; San&rsquo;, at&eacute; finalmente alcan&ccedil;ar a forma atual Ians&atilde;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; a orix&aacute; dos ventos, da tempestade e do raio, o qual usa com a permiss&atilde;o de Xang&ocirc;. Guerreira e destemida, Ians&atilde; est&aacute; muito distante dos outros orix&aacute;s femininos. Est&aacute; mais no campo destinado &agrave;s figuras masculinas, como as frentes de batalhas e das constantes aventuras. Est&aacute; sempre longe de casa, Ians&atilde; odeia o trabalho dom&eacute;stico. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Extremamente sensual, apaixona-se com frequ&ecirc;ncia, por este motivo a lista de parceiros normalmente &eacute; grande, mas nunca ao mesmo tempo. &Eacute; &iacute;ntegra em suas paix&otilde;es. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Para Ians&atilde; n&atilde;o existe o comum, o med&iacute;ocre, o regular e nem o discreto. Tudo &eacute; um acontecimento, seu &oacute;dio &eacute; avassalador, seu arrependimento (comum para ela) &eacute; dram&aacute;tico. Sempre alcan&ccedil;a a vit&oacute;ria nas batalhas que trava, por isso &eacute; decisiva em quest&otilde;es de prote&ccedil;&atilde;o e de demandas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Alegre, gosta de festas e do conv&iacute;vio social. Gosta de estar em evid&ecirc;ncia, de se destacar na multid&atilde;o. &Eacute; o orix&aacute; do arrebatamento, da entrega, da paix&atilde;o. Autorit&aacute;ria e de temperamento forte, irrequieta, dominadora e impetuosa. Explodem com facilidade e perdoam com a mesma rapidez. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Faz bem tudo a que se dedica, pois se entrega de corpo e alma naquilo que acredita. Representa a liberdade e a lideran&ccedil;a. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; muito parecida com Xang&ocirc;, um de seus maridos. Muitos dizem que Ians&atilde; seria uma c&oacute;pia feminina do orix&aacute; da justi&ccedil;a. Xang&ocirc; foi seu grande amor apesar dele t&ecirc;-la raptado e roubado de Ogum. O amor de Ians&atilde; por Xang&ocirc; era tamanho, que as lendas dizem que ela o acompanhou mesmo na morte. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ians&atilde; simboliza a for&ccedil;a e o poder feminino, a mulher em busca de seu pr&oacute;prio sustento, que deseja um homem para am&aacute;-la e n&atilde;o para sustent&aacute;-la. &Eacute; a mulher que enfrenta tudo por seus ideais. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ians&atilde; n&atilde;o aceita submiss&atilde;o e nem qualquer tipo de pris&atilde;o. Mesmo porque &eacute; imposs&iacute;vel aprisionar o vento. O vento que pode soprar numa brisa suave ou se tornar um tornado devastador. Ians&atilde; n&atilde;o baixa a cabe&ccedil;a para ningu&eacute;m. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ao contr&aacute;rio do que muitos dizem, &eacute; extremamente fiel se tratada adequadamente. Apesar de melindrosa, possui encanto e sedu&ccedil;&atilde;o da mais extrema feminilidade. Temperamental e muito ciumenta, mas n&atilde;o &eacute; possessiva. Inteligente e generosa, odeia injusti&ccedil;as. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ians&atilde; &eacute; o ar em movimento que ati&ccedil;a o fogo, que desperta as paix&otilde;es, que nos move na dire&ccedil;&atilde;o de nossos objetivos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tamb&eacute;m est&aacute; ligada &agrave; fecundidade, mas de forma diferente. As tempestades inundam as terras e as deixam f&eacute;rteis e o vento espalha as sementes para que a vida possa sempre continuar. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Segundo a mitologia ioruba, Ians&atilde; transformava-se em b&uacute;falo e voltava &agrave; condi&ccedil;&atilde;o feminina como queria. Por este motivo os chifres </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">de b&uacute;falo est&atilde;o ligados fortemente ao seu culto. Foi dessa forma que Ians&atilde; foi considerada a deusa da ca&ccedil;a e da guerra. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Seus instrumentos s&atilde;o a espada curta (sabre), que usa para guerrear e o eruexim, tipo de rabo de cavalo que usa para movimentar os eguns. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O que pedir?</span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Invocamos Ians&atilde; para prote&ccedil;&atilde;o, principalmente contra entidades femininas encarnadas ou desencarnadas. Para trazer for&ccedil;a e disposi&ccedil;&atilde;o. Contra todo o tipo de demanda, para proteger de tempestades. As mulheres podem invocar Ians&atilde; para qualquer situa&ccedil;&atilde;o. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Caracter&iacute;sticas dos filhos de Ians&atilde; </span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Ians&atilde; tendem a ser magros e vistosos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">D&atilde;o-se bem em tudo o que fazem, mesmo porque se entregam totalmente &agrave; conquista de seus objetivos. Dedicados e prestimosos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Extremamente temperamentais como a m&atilde;e, s&atilde;o inconstantes e sentimentais. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Arrependem-se com a mesma facilidade que perdoam. Isso porque esquecem tudo com facilidade, e isso os coloca em risco de cometer o mesmo erro mais de uma vez. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Alegres, guerreiros e cheios de vitalidade, gostam de festas e de movimento. Come&ccedil;am discuss&otilde;es est&eacute;reis s&oacute; pelo prazer de contestar. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o os conhecidos &ldquo;tempestade em copo d&rsquo;&aacute;gua&rdquo;, mas s&atilde;o incapazes de odiar. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Inquietos e extrovertidos, est&atilde;o sempre chamando a aten&ccedil;&atilde;o, mas s&atilde;o bem conhecidos por seu temperamento explosivo. Sempre sua palavra &eacute; a que vale mais e gosta de impor suas vontades aos outros. N&atilde;o admitem ser contestados, n&atilde;o importando se est&atilde;o certos ou n&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Odeiam injusti&ccedil;as, tendem a proteger os fracos e a contrariar comportamentos de preconceito. Deixam tudo por uma aventura. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Ians&atilde; n&atilde;o conseguem disfar&ccedil;ar seus sentimentos, pois eles ficam bem a mostra, sejam eles bons ou maus. S&atilde;o transparentes. S&atilde;o corajosos, n&atilde;o tem medo de nada. Quanto maior o obst&aacute;culo ou desafio, tanto melhor para eles. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">N&atilde;o gostam de nada rotineiro ou repetitivo. Por isso se jogam de cabe&ccedil;a na profiss&atilde;o ou outras atividades, mas n&atilde;o ficam em casa e nem gostam dos trabalhos dom&eacute;sticos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Ians&atilde; s&atilde;o fi&eacute;is e companheiros se estiverem felizes em seu relacionamento. Do contr&aacute;rio, s&atilde;o capazes de trair muitas vezes e com parceiros diferentes, n&atilde;o levando em conta nem a dec&ecirc;ncia e nem a fam&iacute;lia. Ao contr&aacute;rio dos filhos de Iemanj&aacute;, os filhos de Ians&atilde; s&atilde;o mais devotados aos companheiros do que aos filhos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Por estes motivos, tem dificuldade em viver relacionamentos longos. At&eacute; porque viver com um filho ou filha de Ians&atilde; &eacute; extremamente dif&iacute;cil. Coisas insignificantes podem causar ataques de c&oacute;lera devastadores. S&atilde;o extremamente ciumentos e seu excesso de franqueza sempre os coloca em situa&ccedil;&otilde;es dif&iacute;ceis. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Seus ataques de c&oacute;lera s&atilde;o memor&aacute;veis, n&atilde;o se importam com o que os outros dizem ou pensam. S&atilde;o orgulhos, teimosos, rebeldes e impertinentes. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As mulheres de Ians&atilde; s&atilde;o provocantes, conquistam e dominam seus homens. Gostam de receber homenagens, mas n&atilde;o valorizam os m&eacute;ritos alheios. Desconfiados, vivem num mundo de fantasia. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o amigos fi&eacute;is, mas selecionam muito bem aqueles que ir&atilde;o colocar em seu conv&iacute;vio mais &iacute;ntimo. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Outros Detalhes</span></span></strong></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sincretismo: Santa B&aacute;rbara; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Data de culto: 04 de Dezembro; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o: Eparrei Oy&aacute; (Salve Oy&aacute;, com admira&ccedil;&atilde;o), Eparrei Mesan Orun (Salve a m&atilde;e dos nove c&eacute;us, com admira&ccedil;&atilde;o);</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Aacute;rea de atua&ccedil;&atilde;o: Prote&ccedil;&atilde;o, demandas, quebra de magia negativa, aben&ccedil;oar mulheres independentes, encaminhamento de esp&iacute;ritos; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Elemento: Ar em movimento e fogo;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chacra: Frontal e card&iacute;aco;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Metal: Cobre; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Astro regente: Lua (no quarto novo); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dia da semana: Quarta-feira; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da guia: Amarela, em algumas casa laranja ou vermelha; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da vela: Amarela, em algumas casa laranja ou vermelha;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pedra: Coral, rubi, granada;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebida: Champanha branca; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Amal&aacute;: Acaraj&eacute;, xinxin, vatap&aacute;;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Frutas: Ma&ccedil;&atilde; vermelha, uva rosa, tangerina, cereja, pitanga, laranja-bahia, morango, manga rosa;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Flores: Palmas e rosas amarelas; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas ervas: Espada de Santa B&aacute;rbara, folhas de pitangueira, cord&atilde;o de frade, ger&acirc;nio, capim santo, espinheira santa, rubi, carobinha, cip&oacute; cruz, louro;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local de oferta: Bambuzal e lugares onde se venta (exemplo, alto de morros);</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Animais: B&uacute;falo (for&ccedil;a) e Borboleta (liberdade); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Instrumentos: Leque, espada e eruexim (espanta-moscas feito de rabo de cavalo ou boi) que ela utiliza para movimentar os esp&iacute;ritos;</span></span></span></span></span></li>
</ul>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fontes: </span></span></span></span></span></p>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Marcio Kain, Curso de Teologia da Umbanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fl&aacute;vio Penteado, Povo de Aruanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ademir Jr, Teologia de Umbanda e suas dimens&otilde;es;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lurdes Vieira, Manual Doutrin&aacute;rio, Ritualistico e Comportamental Umbandista</span></span></span></span></span></li>

					</p>
					<a href="AUmbanda_OSORIXAS.php" class="btn btn-primary">&larr; Retornar aos Orixás</a>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 13/04/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>