<?php $results['pageTitle'] = "Xangô | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
			<img class="card-img-top" src="images/xango.jpg" alt="Card image cap">
				<h2 class="card-title"><center>XANGÔ</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; o Orix&aacute; do raio e do trov&atilde;o, do fogo, da justi&ccedil;a, da administra&ccedil;&atilde;o e da pol&iacute;tica. Nas lendas africanas seus pais s&atilde;o Orani&atilde;, que foi um dos reis de If&eacute; e o fundador da cidade de Oi&oacute;, e Torosi, filha de Elemp&ecirc;, rei da na&ccedil;&atilde;o Tap&aacute; (nupes). Entretanto, muitos na Umbanda consideram Oxal&aacute; e Iemanj&aacute; seus progenitores. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Segundo Pierre Verger podemos descrever Xang&ocirc; tanto do ponto de vista hist&oacute;rico como do ponto de vista religioso. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Foi o terceiro (ou quarto) rei de Oi&oacute;, reino que muito fez crescer e prosperar. Excepcional soberano, &eacute; s&aacute;bio juiz e administrador. Muitos o adoravam e tantos outros o temiam. Mas ningu&eacute;m era indiferente ao rei. Enquanto Ox&oacute;ssi era rei de Ketu, Xang&ocirc; era considerado rei de toda a na&ccedil;&atilde;o Ioruba. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ap&oacute;s sua morte foi divinizado, como era comum acontecer com os grandes reis e her&oacute;is. Ap&oacute;s tornar-se orix&aacute;, seu culto era o mais c&eacute;lebre de Oi&oacute;, sendo que os reis subsequentes a Xang&ocirc;, tamb&eacute;m eram considerados seus sacerdotes. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Quando n&atilde;o estava em guerra, defendendo e ampliando os horizontes de seu reino, Xang&ocirc; estava em seu pal&aacute;cio onde recebia seus s&uacute;ditos, aos quais ouvia, ajudava e aconselhava, e, &eacute; claro, julgando suas pend&ecirc;ncias. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; um orix&aacute; muito temido e respeitado, viril e violento. Dizem que Xang&ocirc; castiga os mentirosos e malfeitores com seu raio, e, por este motivo, na &Aacute;frica a morte por raio &eacute; considerada infame, pois teria sido o resultado da ira de Xang&ocirc;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No mesmo racioc&iacute;nio, se um raio atingir uma casa, seu propriet&aacute;rio &eacute; obrigado a pagar altas taxas ao sacerdote de Xang&ocirc;, o qual ap&oacute;s recolher o tributo, revolve o entulho da casa atingida em busca da pedra que foi atingida pelo raio, pois este &eacute; um dos s&iacute;mbolos m&aacute;ximos deste orix&aacute;. Suas armas s&atilde;o a bola de fogo que solta pela boca e o machado de duas l&acirc;minas, que ora corta para fazer o bem e ora corta para ceifar o mal. Outra vis&atilde;o sobre o machado &eacute; que cortar&aacute; a quem quer que seja para se fazer a justi&ccedil;a. O juiz da espiritualidade sempre tem que olhar para os dois lados. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas doutrinas dizem que foi Xang&ocirc; que trouxe para os homens o culto dos ancestrais (Egungun), pois teria ido ao mundo espiritual com a ajuda de Orunmil&aacute; para abra&ccedil;ar pela &uacute;ltima vez sua filha mais querida que havia sido morta por feiticeiras. Uma vez no mundo dos mortos, Xang&ocirc; dominou seus segredos e estabeleceu seu culto. Estas doutrinas relatam ainda que detinha grandes conhecimentos de magia, mas que s&oacute; os utilizava em casos de grande necessidade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">J&aacute; tantas outras dizem que Xang&ocirc; tem uma enorme avers&atilde;o por sofrimento, doen&ccedil;as e a pr&oacute;pria morte. Seu temor pela morte &eacute; t&atilde;o grande que ele abandona seus filhos sete meses antes de seu desencarne, entregando-os aos cuidados de Obalua&ecirc;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Xang&ocirc; &eacute; a autoridade presente, e, como suas pedras, &eacute; pesado, s&oacute;lido e indivis&iacute;vel. Seus filhos constantemente pedem em ora&ccedil;&otilde;es que ele os ajude a n&atilde;o infringir a lei, seja dos homens ou da espiritualidade, por medo da c&oacute;lera de seu pai. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; certamente, ao lado de Iemanj&aacute;, um dos orix&aacute;s mais conhecidos e cultuados no Brasil, sendo que no Nordeste existe at&eacute; um culto com seu nome. N&atilde;o era incomum antigamente, o nome de Xang&ocirc; ser associado ao do pr&oacute;prio Candombl&eacute;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tudo o que se refere a estudos, ao conhecimento especializado, ao direito, contratos, demandas judiciais, elabora&ccedil;&atilde;o de normas e leis, documentos trancados e confidenciais, pertencem a Xang&ocirc;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Est&aacute; envolvido na melhora e no progresso social e cultural. No dia a dia, encontramos Xang&ocirc; nos movimentos sociais, campanhas, partidos pol&iacute;ticos, sindicatos, reparti&ccedil;&otilde;es p&uacute;blicas, f&oacute;runs judiciais, cart&oacute;rios, delegacias, nas diretorias de grandes empresas. Enfim, tudo o que se refere &agrave;s rela&ccedil;&otilde;es e ci&ecirc;ncias humanas, administra&ccedil;&atilde;o e governo. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O que pedir?</span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Invocamos Xang&ocirc; nos casos de demandas judiciais, justi&ccedil;a em geral, para a prosperidade e o dinheiro, para adquirir conhecimento (principalmente o especializado), para o aux&iacute;lio na administra&ccedil;&atilde;o, e at&eacute; mesmo em desastres naturais como terremotos, vulc&otilde;es e avalanches. Muitos recorrem a ele tamb&eacute;m para conseguir o equil&iacute;brio, seja material, emocional ou espiritual. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Caracter&iacute;sticas dos filhos de Xang&ocirc; </span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Xang&ocirc; tem um tipo f&iacute;sico forte, muitas vezes atarracado, mas com alguma gordura, pois sempre tendem a obesidade. Tudo acompanhado de ombros largos e uma estrutura &oacute;ssea extremamente densa e firme, como uma rocha. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">J&aacute; suas filhas podem n&atilde;o ter a eleg&acirc;ncia como atributo fundamental, seguindo o mesmo tipo f&iacute;sico, podem parecer masculinizadas e &agrave;s vezes, grosseiras. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos deste orix&aacute; tem uma atra&ccedil;&atilde;o pela infidelidade muito grande. Sejam homens, ou mulheres, das quais muitos autores dizem ser as mais ardentes do mundo. A conquista e a pr&aacute;tica sexual s&atilde;o vistas como algo vital para os filhos de Xang&ocirc;. Entretanto, como acontece com todas as suas conquistas, n&atilde;o sabe o que fazer com elas ap&oacute;s a vit&oacute;ria, o que faz com que sejam frequentemente frustrados e fracassados no amor. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o extremamente cheios de energia e tem sempre enorme autoestima. Tem consci&ecirc;ncia de sua import&acirc;ncia e de sua nobreza. Independente de quem seja, a chegada de um filho de Xang&ocirc; &eacute; como a chegada de uma grande autoridade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sempre s&atilde;o procurados por pessoas mais velhas ou mais experientes para dar conselhos, mesmo que ele n&atilde;o conhe&ccedil;a o assunto profundamente. Suas orienta&ccedil;&otilde;es s&atilde;o sempre sensatas e coesas, sempre muito justas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o honestos e sinceros, n&atilde;o admitem mentiras e nem trai&ccedil;&otilde;es. N&atilde;o admitem dar satisfa&ccedil;&otilde;es e odeiam ser questionados sobre suas atitudes. S&atilde;o teimosos e vaidosos, jamais acatam opini&atilde;o dos outros e adoram dar a &uacute;ltima palavra. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Quando contrariados ficam enfurecidos e incontrol&aacute;veis. Resolvem tudo de forma destruidora e com muita rapidez. Passado o rompante, recomp&otilde;e-se com facilidade e voltam a normalidade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O humor do filho de Xang&ocirc; &eacute; vari&aacute;vel e costumeiramente ind&oacute;cil. Entretanto, s&atilde;o incapazes de cometer intencionalmente algum mal contra algu&eacute;m. S&atilde;o exigentes mas sabem elogiar e recompensar muito bem aqueles que o cercam, quando estes acertam. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o l&iacute;deres natos e sabem trabalhar muito bem com pessoas sob seu comando. Adoram dominar e influenciar as pessoas. S&atilde;o autorit&aacute;rios, mas honestos e equilibrados. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o justos, honestos. N&atilde;o fazem injusti&ccedil;as e s&atilde;o incapazes de fazer escolhas movidos por paix&otilde;es, amizades ou interesses. Orgulhosos e teimosos, jamais admitem ter se enganado. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Equilibrados, os filhos de Xang&ocirc; podem ser obstinados, inteligentes, ponderados e altivos. Em desequil&iacute;brio s&atilde;o mesquinhos, vaidosos, in&oacute;cuos, corruptos e conservadores. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Eloquentes e soci&aacute;veis, sabem se postar perante o p&uacute;blico e tem facilidade para fazer amizades duradouras. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Gostam de comer e beber muito bem. Gostam das coisas boas da vida compartilhando tudo com sua fam&iacute;lia e amigos, a quem adoram agradar. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No in&iacute;cio da carreira profissional podem ter muitas desilus&otilde;es, alcan&ccedil;am todos os objetivos entre erros e acertos. A sorte est&aacute; sempre a seu lado, o que o motiva e o encoraja a prosseguir. Sua franqueza e honestidade faz com que colecione alguns desafetos, mas nem por isso far&aacute; diferente da pr&oacute;xima vez. &Eacute; cort&ecirc;s, generoso e diplomata. Tem grande facilidade para ganhar dinheiro, mas pouco ju&iacute;zo para gast&aacute;-lo. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Se existe um ponto fraco para os filhos de Xang&ocirc;, esta &eacute; a criatividade. Possuem muita dificuldade de criar coisas novas, por isso preferem melhorar as que j&aacute; existem. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Discuss&otilde;es e desentendimentos s&atilde;o comuns para quem convive com o filho deste Orix&aacute;. N&atilde;o admite ser cobrado ou vigiado, embora considere seus esses direitos. &Eacute; zeloso com aquilo que considera seu. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A maturidade faz muito bem para os filhos de Xang&ocirc;. &Eacute; nesse ponto da vida que se tornam mais calmos e equilibrados. Normalmente &eacute; nessa &eacute;poca que seus relacionamentos se tornam duradouros. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Come&ccedil;am cedo a trabalhar. Sendo que qualquer carreira que o coloque em contato com o p&uacute;blico s&atilde;o as que mais se afinizam com seu perfil. Vendas, direito e qualquer cargo relacionado &agrave; justi&ccedil;a, qualquer cargo p&uacute;blico, pol&iacute;tica, administra&ccedil;&atilde;o de bens de terceiros s&atilde;o algumas das op&ccedil;&otilde;es. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; cr&iacute;tico, mas sempre embasando muito bem seu ponto de vista. E com a mesma sinceridade que critica, distribui elogios a quem os mere&ccedil;a. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Faz e gosta das coisas &agrave;s claras, e uma vez empenhada sua palavra, esteja certo de que a cumprir&aacute;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; otimista por natureza. Quando seus planos n&atilde;o d&atilde;o certo n&atilde;o se deixa abater e passa a trabalhar para realiz&aacute;-los, o que na maioria das vezes consegue. Por este motivo odeia pessoas pessimistas e com ar de perdedor. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As filhas de Xang&ocirc; possuem forte tino comercial, amantes da natureza e da vida ao ar livre. Tamb&eacute;m s&atilde;o extremamente positivas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Possuem franqueza e honestidade como pontos fortes, por&eacute;m muitas vezes s&atilde;o indelicadas e ofendem sem inten&ccedil;&atilde;o por este motivo. O tempo e a maturidade tamb&eacute;m corrigir&atilde;o esses desequil&iacute;brios. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">De personalidade forte e independente, n&atilde;o gostam de ser mandadas, principalmente na rela&ccedil;&atilde;o afetiva. S&atilde;o cr&eacute;dulas por demais, chegando &agrave; inoc&ecirc;ncia. Por isso precisam muitas vezes de um pulso forte para controla-las. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Detestam servi&ccedil;os dom&eacute;sticos, mas odeiam ainda mais a desorganiza&ccedil;&atilde;o e a sujeira. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Como pais e m&atilde;es os filhos de Xang&ocirc; s&atilde;o companheiros, incentivando e estimulando suas crias. S&atilde;o amigos e aos olhos alheios podem parecer relapsos. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Outros Detalhes</span></span></strong></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sincretismo: S&atilde;o Jer&ocirc;nimo, S&atilde;o Jos&eacute;, S&atilde;o Pedro, Mois&eacute;s, S&atilde;o Jo&atilde;o Batista; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Data de culto: 30 de Setembro (S&atilde;o Jer&ocirc;nimo); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o: Ka&ocirc; Kabecil&ecirc; (Venham ver e admirar o rei da casa); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Aacute;rea de atua&ccedil;&atilde;o: Justi&ccedil;a, equil&iacute;brio, administra&ccedil;&atilde;o, neg&oacute;cio, aprimoramento;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Elemento: Fogo; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chacra: Card&iacute;aco; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Metal: Estanho;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Astro regente: J&uacute;piter; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dia da semana: Quarta-feira; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da guia: Marrom, branco e vermelho(em algumas casas); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da vela: Marrom (vermelha em algumas casas); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pedra: Meteorito, pirita, jaspe; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebida: Cerveja preta;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Amal&aacute;: Rabada, acaraj&eacute;, quiabo; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Frutas: Marmelo, caqui, fruta-do-conde, melancia, morango, manga (cora&ccedil;&atilde;o de boi) e mam&atilde;o;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Flores: L&iacute;rio, cravos brancos e vermelhos; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas ervas: Erva de S&atilde;o Jo&atilde;o. Erva tost&atilde;o, louro, caruru, alevante, comigo ningu&eacute;m pode, folhas de mangueira, folhas de marmeleira, folhas de seringueira, folhas de caf&eacute;, folhas de figueira, aperta ru&atilde;o;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local de oferta: Pedreiras, pedras perto do mar; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Animais: Porco do mato e aves malhadas;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Instrumentos: Ox&eacute; (machado de duas l&acirc;minas) e balan&ccedil;a;</span></span></span></span></span></li>
</ul>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fontes: </span></span></span></span></span></p>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Marcio Kain, Curso de Teologia da Umbanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fl&aacute;vio Penteado, Povo de Aruanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ademir Jr, Teologia de Umbanda e suas dimens&otilde;es;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lurdes Vieira, Manual Doutrin&aacute;rio, Ritualistico e Comportamental Umbandista</span></span></span></span></span></li>

					</p>
					<a href="AUmbanda_OSORIXAS.php" class="btn btn-primary">&larr; Retornar aos Orixás</a>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 13/04/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>