<?php $results['pageTitle'] = "O Terreiro | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
				<h2 class="card-title"><center>O TERREIRO</center></h2>
					<p class="card-text">
						
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Cong&aacute;</span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Cong&aacute; &eacute; um n&uacute;cleo de for&ccedil;a em atividade constante, agindo como centro atrator, condensador, escoador, expansor, transformador e alimentador dos mais diferentes tipos e n&iacute;veis de energia e magnetismo.</span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; atrator, porque puxa para si todas as variedades de pensamentos que pairam sobre o terreiro. Est&aacute; em cont&iacute;nua atividade magn&eacute;tica, atraindo ondas ou feixes de pensamento, positivos ou negativos.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; condensador, pois as ondas ou feixes mentais se aglutinam ao seu redor. Condensa em si os fluxos de cargas positivas e negativas, que v&ecirc;m dos presentes. </span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; escoador, funcionando como se fosse um fio-terra (para-raios). Comprime miasmas e cargas negativas e as descarrega para a M&atilde;e-Terra.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; expansor, porque restitui aos presentes (corpo medi&uacute;nico e assist&ecirc;ncia) as ondas e feixes de pensamento captados e potencializados.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; transformador, pois age, em alguns casos e sob determinados limites, como um reciclador de lixo astral, condensando, depurando e vertendo a energia captada j&aacute; reciclada.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; alimentador, pelo fato de ser o N&uacute;cleo de For&ccedil;a da Casa, agindo como fonte de combust&iacute;vel principal para as atividades medi&uacute;nicas que sustentam a egr&eacute;gora. </span></span></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Cong&aacute; n&atilde;o &eacute; mero enfeite. Tamb&eacute;m n&atilde;o &eacute; um aglomerado de s&iacute;mbolos afixados de forma aleat&oacute;ria, atendendo a vaidade de uns e o devaneio de outros. O Cong&aacute;, dentro dos Templos Umbandistas s&eacute;rios, tem fundamento, tem raz&atilde;o de ser. &Eacute; pautado em bases e diretrizes s&oacute;lidas, l&oacute;gicas, racionais, m&iacute;sticas, sob a supervis&atilde;o dos mentores de Aruanda.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Curimba</span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Curimba &eacute; o nome que se d&aacute; ao grupo de pessoas respons&aacute;vel por entoar os pontos cantados e tocar os atabaques nos rituais Umbandistas. Outros instrumentos tamb&eacute;m s&atilde;o utilizados por esse grupo, como berimbau por exemplo, al&eacute;m de outros instrumentos de percuss&atilde;o consagrados.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Segundo o dicion&aacute;rio informal: <em>&eacute; um instrumento de percuss&atilde;o dos terreiros de Umbanda e das religi&otilde;es de origem africana, como o Candombl&eacute;. Predominantemente usado para a emana&ccedil;&atilde;o de energia positiva para os m&eacute;diuns e guias espirituais. Atabaque, timbadora. Assim como o termo Macumba, que na verdade &eacute; o nome da &aacute;rvore africana da qual se fazia o mesmo instrumento na &Aacute;frica, pode-se entender que o nome Curimba &eacute; o pr&oacute;prio trabalho no terreiro, centro, tenda ou ro&ccedil;a, at&eacute; porque &eacute; um dos pontos de for&ccedil;a no terreiro, como o cong&aacute; e a trunqueira.</em></span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Curimba tem papel fundamental no ritual Umbandista. A entoa&ccedil;&atilde;o dos pontos cantados e do som dos atabaques movimenta energia, que auxilia na incorpora&ccedil;&atilde;o dos guias e protetores. Tamb&eacute;m auxilia na firmeza e limpeza do terreiro. Ela tem a fun&ccedil;&atilde;o de abrir, manter, sustentar e fechar os trabalhos espirituais de uma forma harmoniosa e clara.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Vel&aacute;rio</span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local onde os m&eacute;diuns, cambonos e doutrinadores firmam velas para os esp&iacute;ritos que foram orientados ou auxiliados. Tamb&eacute;m &eacute; utilizado para firmar a vela do anjo de guarda. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><a name="_Toc516143196"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Tronqueira</span></span></span></strong></a><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> (ou Trunqueira)</span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local onde se encontram os assentamentos de Exu e tamb&eacute;m onde este Orix&aacute; recebe suas oferendas. Normalmente &eacute; fechado &agrave; chave, sendo que somente o dirigente ou um irm&atilde;o devidamente autorizado tem permiss&atilde;o para entrar. &Eacute; constru&iacute;do usualmente na parte da frente dos terreiros, para que Exu barre a entrada de esp&iacute;ritos indesejados. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em alguns terreiros, pode ser apenas a casa do Sr. Exu Tronqueira, o qual se encarrega de fazer a primeira prote&ccedil;&atilde;o da casa e tamb&eacute;m de amarrar, em seu tronco de trabalho, todos os esp&iacute;ritos e energias m&aacute;s. Neste caso, a Tronqueira ser&aacute; uma casinha similar &agrave;quelas que abrigam imagens de santos em resid&ecirc;ncias de algumas pessoas. Ainda, quando a Tronqueira se apresenta desta forma, somente o Sr. Tronqueira recebe ali suas ofertas. Os outros Exus recebem seus tributos em outro local. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Gira</span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Espa&ccedil;o para onde s&atilde;o encaminhados os consulentes e os m&eacute;diuns atendidos, para que possam girar e permitir a aproxima&ccedil;&atilde;o de seus guias e protetores. Dessa forma, refinam a conex&atilde;o e o equil&iacute;brio com seus guias, al&eacute;m de serem submetidos &agrave; limpeza espiritual.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Roda de Fogo (Fundanga)</span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O uso da roda &eacute; milenar. Desde antes de Nosso Senhor Jesus Cristo ter vindo aqui na Terra, j&aacute; se fazia a &ldquo;roda&rdquo; pelos judeus, para tirar esp&iacute;ritos ruins quando o corpo era obsedado. Para que a roda possa ser feita deve-se ter uma escora muito grande, para que ela n&atilde;o se inverta. A roda precisa ser feita em terreiros onde tem escora e esp&iacute;ritos que queiram evoluir. No terreiro h&aacute; esp&iacute;ritos que querem evoluir e que ainda n&atilde;o encarnaram na terra. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Querem evoluir para adquirir per&iacute;spirito e poder encarnar. Esses esp&iacute;ritos s&atilde;o usados na roda. Quando entramos na roda, eles entram tamb&eacute;m, um para cada pessoa. Nossos olhos n&atilde;o os enxergam, mas eles est&atilde;o l&aacute;. Eles fazem o trabalho quando sentem a for&ccedil;a da &ldquo;roda&rdquo;, que vem da for&ccedil;a do terreiro e toda a energia ruim acumulada &eacute; levada por eles para ser descarregada no meio do oceano. Essa energia descarregada &eacute; aquela pr&oacute;pria dos que n&atilde;o tem uma faculdade mental equilibrada e tem uma s&eacute;rie de emo&ccedil;&otilde;es descontroladas.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O uso da p&oacute;lvora (fundanga ou tuia) se justifica porque ao ser queimada ou mesmo explodida nos trabalhos de limpeza e descarrego, provoca deslocamento do ar com repercuss&atilde;o no plano astral, limpando a aura do filho de f&eacute; dos miasmas, vibra&ccedil;&otilde;es negativas, bacilos ps&iacute;quicos, cargas mal&eacute;ficas provenientes de elementais, larvas astrais, subst&acirc;ncias delet&eacute;rias que se tenham agrupado na aura do doente, criando um casc&atilde;o invis&iacute;vel, por&eacute;m nocivo ao recebimento de energias c&oacute;smicas salutares que ficam impedidas de penetrar no corpo f&iacute;sico atrav&eacute;s dos centros de for&ccedil;a no corpo astral (chacras). </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Passe</span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A sala de passe &eacute; o outro ponto de for&ccedil;a da Casa, onde ocorre o trabalho de imposi&ccedil;&atilde;o de m&atilde;os para a doa&ccedil;&atilde;o de energias e curas espirituais. Possui seu Cong&aacute; pr&oacute;prio.</span></span></span></span></p>

					</p>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 26/11/2018
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>