<?php $results['pageTitle'] = "Iemanjá | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
			<img class="card-img-top" src="images/iemanja.jpg" alt="Card image cap">
				<h2 class="card-title"><center>IEMANJÁ</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Deusa de Egb&eacute;, na&ccedil;&atilde;o Iorub&aacute;, onde corre o rio Yemoja, de onde vem seu nome. Muitos ainda o traduzem por &ldquo;m&atilde;e cujos filhos s&atilde;o peixes&rdquo;. Tamb&eacute;m &eacute; conhecida ainda pelos nomes de Rainha do Mar, Ina&ecirc;, Mucun&acirc;, Dandalunda e Jana&iacute;na. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Filha de Olokum, o senhor dos mares, de quem recebeu suas atribui&ccedil;&otilde;es com a &aacute;gua. Teve v&aacute;rios maridos, entre eles os mais importantes foram Orunmil&aacute; e Oxal&aacute;. Teve in&uacute;meros filhos, entre eles os orix&aacute;s Ogum, Exu, Ox&oacute;ssi e Xang&ocirc;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No Brasil, &eacute; o orix&aacute; do pante&atilde;o africano mais conhecida, tanto pelas festas feitas em seu nome, que arrastam milhares de pessoas, quanto pelo costume de pular 7 ondas na entrada do ano novo, ritual repetido em todo o litoral brasileiro e consagrado a ela. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">De seu ventre sa&iacute;ram os orix&aacute;s. De seus enormes seios saem as &aacute;gua que alimentam os rios do mundo e que por sua vez fertilizam a terra. Iemanj&aacute; &eacute; a fecundidade, a vida. Da mesma forma que Oxal&aacute; &eacute; o princ&iacute;pio gerador masculino, Iemanj&aacute; &eacute; o princ&iacute;pio gerador feminino. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Deusa do mar e protetora do mar e da vida marinha, das m&atilde;es, das esposas e da fam&iacute;lia, representando a procria&ccedil;&atilde;o, encerra em si mesma o conceito prim&aacute;rio da m&atilde;e benevolente. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Divide com Oxum o atributo da vida, Iemanj&aacute; gera, Oxum mant&eacute;m. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; Iemanj&aacute; quem ampara a cabe&ccedil;a dos beb&ecirc;s ao nascerem, e s&oacute; depois entrega aos orix&aacute;s que ir&atilde;o reg&ecirc;-lo. &Eacute; tamb&eacute;m conhecida como senhora de todas as cabe&ccedil;as e, por isso, no Candombl&eacute; e em algumas doutrinas umbandistas, certamente seja t&atilde;o reverenciada, pois &eacute; na cabe&ccedil;a onde se encontram assentados os orix&aacute;s da pessoa que comandar&atilde;o seu destino. Em lavagens de cabe&ccedil;a e em eboris, seu nome &eacute; presen&ccedil;a obrigat&oacute;ria. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; ela quem rege as rela&ccedil;&otilde;es entre os seres. No terreiro, &eacute; respons&aacute;vel pelo esp&iacute;rito fraterno que deve existir entre os irm&atilde;os de f&eacute; e o pai ou m&atilde;e-de-santo. Nas amizades, &eacute; a lealdade. Na fam&iacute;lia, &eacute; ela quem estrutura as rela&ccedil;&otilde;es entre pais e filhos, irm&atilde;os e irm&atilde;s, e de quaisquer entes queridos. Iemanj&aacute; &eacute; a vontade de vermos bem e seguros todos aqueles que amamos. A m&atilde;e que sofre pelo filho &eacute; a imagem que melhor representa este orix&aacute;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em resumo &eacute; o amor ao pr&oacute;ximo e a uni&atilde;o e harmonia da fam&iacute;lia. &Eacute; a grande m&atilde;e que sempre tem uma palavra benevolente ou um conselho para dar a qualquer filho que a ela recorra. Sempre atende aos que dela se socorrem. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Iemanj&aacute; &eacute; o senso de educa&ccedil;&atilde;o que damos a nossos filhos, o mesmo que aprendemos com nossos pais, que aprenderam com nossos av&oacute;s. Extremamente exigente com seus filhos, at&eacute; mesmo o castigo &eacute; regido por ela. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Deusa dos mares e das &aacute;guas como um todo, respons&aacute;vel pela fauna e flora marinha, inclusive a reprodu&ccedil;&atilde;o dos peixes. Por este motivo &eacute; padroeira dos pescadores, para os quais &eacute; considerada como senhora do alimento. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O que pedir?</span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Muito invocada para a prosperidade e abund&acirc;ncia. Invocamos Iemanj&aacute; para curar problemas na cabe&ccedil;a (f&iacute;sico ou mental), para a ben&ccedil;&atilde;o e prote&ccedil;&atilde;o da fam&iacute;lia, dos amigos e das rela&ccedil;&otilde;es entre irm&atilde;os de f&eacute;. As festas familiares como casamentos, anivers&aacute;rios, entre outras, s&atilde;o tamb&eacute;m aben&ccedil;oadas por ela. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Calunga Grande </span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A palavra calunga vem do dialeto Bantu e significa &ldquo;morada dos mortos&rdquo;. Na Umbanda costumamos atribuir ao cemit&eacute;rio o nome de Calunga Pequena, e ao mar, Calunga Grande. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Mas como o dom&iacute;nio da senhora geradora da vida poderia estar relacionada com os mortos? </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Devemos lembrar que a morte n&atilde;o &eacute; o fim de nada e sim uma transforma&ccedil;&atilde;o da vida. Assim como Pai Obalua&ecirc; (ou Omulu) &eacute; considerado o senhor da morte, mas, acima de tudo, &eacute; tamb&eacute;m o grande agente transformador, que guia os esp&iacute;ritos da vida material para a vida espiritual. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Da mesma forma o mar tamb&eacute;m &eacute; um agente de transforma&ccedil;&atilde;o, trazendo e fecundando a vida em nosso planeta. Outra explica&ccedil;&atilde;o para denominarmos o mar como Calunga Grande seria dada pelos pr&oacute;prios negros que vieram escravizados nos navios negreiros. A viagem para a Am&eacute;rica em navio negreiro, era extremamente danosa e mortal, sendo que muitos autores dizem que apenas 1/3 dos escravos sobreviviam diante das condi&ccedil;&otilde;es desumanas do transporte. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dessa forma, o negro viu muitos de sua ra&ccedil;a adoecerem e morrerem, sendo que os corpos eram lan&ccedil;ados ao mar. Fora isso, a viagem na condi&ccedil;&atilde;o de escravo simbolizava a morte de sua liberdade, de sua fam&iacute;lia, de sua cidade, de sua cultura e religi&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Para muitos o fundo do mar seria a pris&atilde;o de muitos eguns, pois antigamente era comum lan&ccedil;ar o corpo dos mortos ao mar. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Aqueles que partilham desse credo lembram que Iemanj&aacute; foi m&atilde;e adotiva de Obalua&ecirc;, ao qual conferiu poderes sobre a morte e sobre estes mesmos eguns. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Caracter&iacute;sticas dos filhos de Iemanj&aacute; </span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Iemanj&aacute; tem tend&ecirc;ncia a ter o nariz afilado, e as mulheres, seios grandes. Tendem &agrave; obesidade ou a alguma desarmonia no corpo. Empreendedores, ativos e sovinas. Muito sonhadores, ing&ecirc;nuos e, &agrave;s vezes, exagerados. N&atilde;o tem no&ccedil;&atilde;o de propor&ccedil;&atilde;o. Se um filho de Iemanj&aacute; convidar 2 pessoas para jantar em sua casa, tenha certeza de que far&aacute; comida para 20. S&atilde;o calmos, d&oacute;ceis e criativos. Formais e cheios de dignidade. &nbsp;Voluntariosos, assumem os problemas dos outros como se fossem seus. Excepcionais conselheiros. As mulheres s&atilde;o ainda maternais e s&eacute;rias, podendo criar sem problemas os filhos dos outros. Apesar da apar&ecirc;ncia tranquila, podem se transformar quando o assunto for fam&iacute;lia, a qual defendem com unhas e dentes. S&atilde;o extremamente exigentes com seus filhos. Castigam, mas n&atilde;o admitem que outros o fa&ccedil;am. Entretanto s&atilde;o excelentes educadores. S&atilde;o caseiros, gostam de rotina e normalmente s&atilde;o bons com os servi&ccedil;os dom&eacute;sticos. Met&oacute;dicos, adoram tudo o que se relaciona com o oculto. Sens&iacute;veis e emotivos, s&atilde;o os famosos chor&otilde;es. Em equil&iacute;brio s&atilde;o nobres, criativos, corajosos e constantes. Desequilibrados podem ser rudes, insens&iacute;veis medrosos, orgulhosos e gulosos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o amigos, mas colocam &agrave; prova as amizades. N&atilde;o perdoam uma ofensa, e, caso perdoem, n&atilde;o esquecer&atilde;o jamais. Muitos dizem que os filhos de Iemanj&aacute; n&atilde;o s&atilde;o bons em guardar segredos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exageram em suas verdades para dizer que n&atilde;o mentem, e sempre fazem uso de chantagens emocionais. As mulheres de Iemanj&aacute; s&atilde;o muito mais m&atilde;e que esposas. E s&atilde;o independentes de maridos e dos pais. Tendem a ter mais de um casamento. Desconfiados, podem alimentar ci&uacute;mes doentios. Reclamam de tudo, mas nunca deixam de fazer aquilo que lhe pedem. Lutadores e dedicados, procuram sempre formas de alcan&ccedil;ar os postos mais elevados. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Nas profiss&otilde;es s&atilde;o excelentes psic&oacute;logos, educadores, m&eacute;dicos e at&eacute; mesmos simples donas de casa. Podem ter em seu destino motivos para mudar de estado ou de pa&iacute;s. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Existe um grande folclore sobre as filhas de Iemanj&aacute; n&atilde;o poderem cortar o cabelo sem a autoriza&ccedil;&atilde;o do orix&aacute;. Se voc&ecirc; acredita nisso, pe&ccedil;a licen&ccedil;a, mesmo que apenas mentalmente, e corte seu cabelo filha de Iemanj&aacute;. Na Umbanda esse tipo de recomenda&ccedil;&atilde;o n&atilde;o faz sentido se lembrarmos que os orix&aacute;s s&atilde;o parte da energia do pr&oacute;prio Deus. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Outros Detalhes</span></span></strong></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sincretismo: Nossa Senhora da Gl&oacute;ria, Nossa Senhora dos Navegantes, Nossa Senhora da Concei&ccedil;&atilde;o </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Data de culto: 02 de Fevereiro (NS Navegantes), 08 de Dezembro (NS Concei&ccedil;&atilde;o), </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o: Odo I&aacute; (salve a m&atilde;e) ou Odo Fe Iab&aacute; (Salve a m&atilde;e das &aacute;guas); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Aacute;rea de atua&ccedil;&atilde;o: Fam&iacute;lia, rela&ccedil;&otilde;es pessoais, cura (cabe&ccedil;a), vida, fecundidade e prosperidade; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Elemento: &Aacute;gua;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chacra: Frontal </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Metal: Prata;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Astro regente: Lua (no quarto cheio); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dia da semana: S&aacute;bado; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da guia: Azul e branco ou azul claro com contas transparentes; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da vela: Azul clara;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pedra: P&eacute;rola, &aacute;gua marinha, l&aacute;pis-laz&uacute;li, calced&ocirc;nia e turquesa; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebida: &Aacute;gua mineral ou champanhe branco;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Amal&aacute;: Peixe, camar&atilde;o, canjica doce, arroz com mel; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Frutas: Marmelo, graviola, uvas brancas, melancia, n&ecirc;spera, pera; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Flores: Rosas brancas ou palmas brancas;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas ervas: Panac&eacute;ia, ang&eacute;lica, pic&atilde;o-da-praia, manac&aacute;, c&acirc;nfora, chap&eacute;u de couro, l&aacute;grima de Nossa Senhora, Erva de Santa Luzia, lavanda, mastru&ccedil;o;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local de oferta: Praias ou em alto mar, tamb&eacute;m aceita perto de grandes rios;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Animais: Peixe, cabra branca, ovelha branca, galinha branca; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Instrumentos: Abeb&eacute;, leque de metal prateado na figura de um peixe;</span></span></span></span></span></li>
</ul>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fontes: </span></span></span></span></span></p>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Marcio Kain, Curso de Teologia da Umbanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fl&aacute;vio Penteado, Povo de Aruanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ademir Jr, Teologia de Umbanda e suas dimens&otilde;es;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lurdes Vieira, Manual Doutrin&aacute;rio, Ritualistico e Comportamental Umbandista</span></span></span></span></span></li>

					</p>
					<a href="AUmbanda_OSORIXAS.php" class="btn btn-primary">&larr; Retornar aos Orixás</a>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 14/04/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>