<?php $results['pageTitle'] = "A Carta Magna da Umbanda | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
				<h2 class="card-title"><center>A CARTA MAGNA DA UMBANDA</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">1. A religi&atilde;o de Umbanda &eacute; genuinamente brasileira, com as seguintes caracter&iacute;sticas em sua origem:</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">&bull; &Eacute; milenar, porque seus fundamentos s&atilde;o os mesmos que presidiam o reencontro com Deus, desde o in&iacute;cio da ra&ccedil;a humana no nosso planeta.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">&bull; &Eacute; c&oacute;smica, porque seus fundamentos culminaram com a uni&atilde;o preconizada pelo Movimento Umbandista dos quatro pilares do conhecimento humano, que s&atilde;o: a Filosofia, a Ci&ecirc;ncia, a Religi&atilde;o e a Arte.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">&bull; &Eacute; evolutiva, em suas manifesta&ccedil;&otilde;es, porque a Umbanda se manifesta em seu dia-a-dia, utilizando todos os recursos positivos existentes no ontem, no hoje e, com certeza, se valer&aacute; dos que vierem, no amanh&atilde;.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">&bull; &Eacute; cr&iacute;stica, porque os seus aspectos, princ&iacute;pios, postulados e finalidades est&atilde;o baseados nos ensinamentos dos Mestres da Luz, principalmente no Mestre Jesus, sendo a manifesta&ccedil;&atilde;o e a viv&ecirc;ncia do Evangelho Redentor. Aceitando tudo o que &eacute; bom, rejeitando o que n&atilde;o eleva e caminha ao crescimento do ser humano.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">&bull; &Eacute; brasileira, em suas origens. Como pr&aacute;tica religiosa surgiu e desenvolveu-se no Brasil, institu&iacute;da pelo Caboclo das Sete Encruzilhadas, atrav&eacute;s da mediunidade de Z&eacute;lio Fernandino de Moraes, em 15 de novembro de 1908.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">2. A Umbanda teve, na sua origem, contribui&ccedil;&otilde;es da Doutrina Esp&iacute;rita, e contribui&ccedil;&otilde;es positivas das religi&otilde;es Ind&iacute;gena, Africana, e Cat&oacute;lica Popular. Contudo, a Umbanda &eacute; isenta de interfer&ecirc;ncias das religi&otilde;es citadas, n&atilde;o se submetendo a nenhum dogma relacionado com elas.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">3. A Umbanda integrou, reinterpretou e adaptou algumas vis&otilde;es religiosas aludidas (Ind&iacute;gena, Africana, e Cat&oacute;lica Popular), de acordo com sua pr&oacute;pria percep&ccedil;&atilde;o, dando origem a uma religi&atilde;o de base universalista.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">4. A Umbanda tem Hino pr&oacute;prio desde 1961, de autoria de Jos&eacute; Manuel Alves (letra) e Dalmo da Trindade Reis (m&uacute;sica).</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">5. A Umbanda &eacute;: doa&ccedil;&atilde;o, caridade, compromisso, prosperidade e humildade.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">a) DOA&Ccedil;&Atilde;O: A Umbanda tem no voluntariado, no servi&ccedil;o medi&uacute;nico a forma de crescimento natural da religi&atilde;o, onde a participa&ccedil;&atilde;o &eacute; fundamental. &Eacute; por meio da doa&ccedil;&atilde;o que o medianeiro aprende a valorizar o seu Templo e a socializar com os seus irm&atilde;os.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">b) CARIDADE: A a&ccedil;&atilde;o caritativa &eacute; uma das formas da eleva&ccedil;&atilde;o do esp&iacute;rito. Fora da caridade n&atilde;o existe a compreens&atilde;o da miss&atilde;o evolutiva do religioso de Umbanda. A caridade &eacute; a express&atilde;o m&aacute;xima do aprendizado religioso em sua plenitude pelo m&eacute;dium de Umbanda.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">c) COMPROMISSO: A Umbanda tem no compromisso do m&eacute;dium com o bem, com a verdade, com a lealdade, com a caridade, com a entrega pessoal e com o respeito, a ess&ecirc;ncia do verdadeiro religioso como forma de evolu&ccedil;&atilde;o.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">d) PROSPERIDADE: A prosperidade se d&aacute; a todos os n&iacute;veis pelo esfor&ccedil;o de crescimento e desenvolvimento di&aacute;rio em todos os sentidos. A prosperidade n&atilde;o se ganha, se conquista atrav&eacute;s da pr&aacute;tica da honestidade, do esfor&ccedil;o, do conhecimento e pelo trabalho individual, onde, amparado por sua f&eacute; e merecimento, o individuo conquistar&aacute; seus objetivos.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">e) HUMILDADE: O religioso de Umbanda tem como base espiritual a sua humildade; entendendo que ele, m&eacute;dium, n&atilde;o &eacute; melhor que ningu&eacute;m, mas sim tem a responsabilidade maior e compromisso como instrumento da Espiritualidade em transmitir as mensagens de Luz, passadas pelos planos elevados. Na Umbanda, existe uma hierarquia espiritual que orienta os trabalhos, com Dirigentes, M&eacute;diuns e Auxiliares; por&eacute;m, todos sabemos que no plano material somos, em todos os momentos, aprendizes e professores e todos n&oacute;s estamos em constante aprendizado, n&atilde;o sendo ningu&eacute;m melhor do que o outro, apenas com fun&ccedil;&otilde;es e responsabilidades diferentes. Entendemos que quem deve ser glorificado &eacute; Deus, nunca o medianeiro.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">6. O religioso de Umbanda segue o que foi anunciado pelo seu fundador, o Caboclo das Sete Encruzilhadas, bem como, os ensinamentos dos Esp&iacute;ritos Cr&iacute;sticos, os Mestres do Amor, como via evolutiva para se chegar a uma espiritualidade superior.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">7. A Umbanda tr&aacute;s em si a base religiosa que deve ser considerada: Amar, respeitar, n&atilde;o julgar, n&atilde;o caluniar, atuar sempre com a verdade, na base do bem, da educa&ccedil;&atilde;o e da eleva&ccedil;&atilde;o. O posicionamento &eacute;tico em qualquer religi&atilde;o deve se basear em tais predicados, manifestados pelos verdadeiros religiosos.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">8. Os m&eacute;diuns s&atilde;o vistos como religiosos e devem agir como tal, com f&eacute; em Deus, nos Sagrados Orix&aacute;s e nos Guias Espirituais; possuir os atributos da f&eacute;, amar seu semelhante, n&atilde;o julgar, n&atilde;o caluniar, ser pacificador, estar ao servi&ccedil;o do bem e jamais utilizar o seu conhecimento de forma torpe. Esses atributos s&atilde;o posicionamentos &eacute;ticos e morais para todos os que comungam da f&eacute; umbandista.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">9. A Umbanda atua na eleva&ccedil;&atilde;o, na educa&ccedil;&atilde;o religiosa e na evolu&ccedil;&atilde;o dos Esp&iacute;ritos, praticando trabalhos que visam o progresso do ser humano, direcionando a reforma &iacute;ntima por meio dos postulados de Jesus, da vibra&ccedil;&atilde;o dos Sagrados Orix&aacute;s e dos ensinamentos dos Esp&iacute;ritos Cr&iacute;sticos, que s&atilde;o transmitidos pelos Guias Espirituais que se manifestam nos Templos de Umbanda.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">10. A Umbanda &eacute; uma religi&atilde;o que cr&ecirc; na exist&ecirc;ncia de um Deus &uacute;nico, intelig&ecirc;ncia suprema, causa prim&aacute;ria de todas as coisas, eterno, imut&aacute;vel, imaterial, onipotente, onipresente, soberanamente justo e bom, infinito em todas as suas perfei&ccedil;&otilde;es.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">11. A Umbanda cr&ecirc; no Mestre Jesus, pautando seu aspecto doutrin&aacute;rio baseado em Seus ensinamentos.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">12. A Umbanda cr&ecirc; na exist&ecirc;ncia de Hierarquias Divinas, denominadas por n&oacute;s de Orix&aacute;s, respons&aacute;veis pela sustenta&ccedil;&atilde;o planet&aacute;ria, e alicerces para direcionarmos nossas condutas na pr&aacute;tica do amor, da caridade e da f&eacute;. N&atilde;o s&atilde;o deuses, mas sim, denomina&ccedil;&otilde;es humanas para os Poderes Reinantes do Divino Criador.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">13. A Umbanda reverencia a M&atilde;e Natureza, por ser nela que se encontra a mais pura manifesta&ccedil;&atilde;o Divina, por onde os Sagrados Orix&aacute;s se manifestam energeticamente com mais intensidade e, tamb&eacute;m, porque vamos buscar e nos harmonizar com as for&ccedil;as ali reinantes, sustentadoras de toda a forma de vida planet&aacute;ria.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">14. A Umbanda cr&ecirc; na exist&ecirc;ncia da comunica&ccedil;&atilde;o medi&uacute;nica por meio de medianeiros preparados para tal tarefa, em trabalhos caritativos, em atendimentos fraternos em coparticipa&ccedil;&atilde;o com os Guias Espirituais.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">15. A Umbanda prima pela simplicidade de seus rituais, o que permite a dedica&ccedil;&atilde;o integral do tempo das sess&otilde;es ao atendimento fraterno dos que a ela recorrem.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">16. Nos atendimentos fraternos est&aacute; o cerne do assistencialismo da Umbanda, sempre de forma caritativa.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">17. Umbanda &eacute; sin&ocirc;nimo de pr&aacute;tica religiosa e caritativa, n&atilde;o se coadunando com cobran&ccedil;as pecuni&aacute;rias pelo que faz. N&atilde;o faz parte de seus fundamentos a retribui&ccedil;&atilde;o financeira pelos atendimentos fraternos ou pelos passes realizados. Contudo, &eacute; l&iacute;cito, quando necess&aacute;rio para sustenta&ccedil;&atilde;o, manuten&ccedil;&atilde;o e desenvolvimento dos Templos, assim como, para proporcionar conforto e bem-estar a seus frequentadores, o chamamento dos m&eacute;diuns e das pessoas que frequentam o Templo para contribu&iacute;rem para esses fins. Todavia, a contribui&ccedil;&atilde;o far-se-&aacute; conforme o crit&eacute;rio de cada Templo, mas de uma forma moderada e ajustada &agrave;s necessidades, sem que haja discrimina&ccedil;&atilde;o ou preconceito para com aqueles que n&atilde;o possam contribuir.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">18. No caso espec&iacute;fico de dirigentes umbandistas que passaram a dedicar-se integralmente ao Culto, em determinadas situa&ccedil;&otilde;es e regi&otilde;es, cobrando nomeadamente por suas consultas, as sess&otilde;es (giras) devem continuar p&uacute;blicas e abertas, onde &eacute; facultada a solicita&ccedil;&atilde;o de contribui&ccedil;&otilde;es volunt&aacute;rias aos membros e assistidos.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">19. A Umbanda possui sacramentos e ritos pr&oacute;prios, tais como: o batismo, o casamento e o f&uacute;nebre.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">20. Os principais ritos da Umbanda s&atilde;o realizados por meio de ora&ccedil;&otilde;es, pontos cantados, que, em alguns Terreiros, s&atilde;o ritmados atrav&eacute;s de instrumentos musicais.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">21. A Umbanda realiza sess&otilde;es e trabalhos de limpeza espiritual, descarregos e energ&eacute;tica, assim como o de aconselhamento e tratamento espiritual, que visam o bem-estar e o desenvolvimento espiritual, consciencial, emocional e moral do indiv&iacute;duo. Nesses trabalhos s&atilde;o utilizados o passe energ&eacute;tico, o uso ritual&iacute;stico do tabaco e dos elementos vegetais, designadamente, em defuma&ccedil;&otilde;es, em banhos e/ou amacis. A Umbanda ainda se utiliza de componentes minerais, tais como: pedras, cristais, metais e a pemba, que s&atilde;o elementos condensadores de energia, como tamb&eacute;m, da energia essencial dos elementos da natureza.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">22. A Umbanda recorre &agrave;s ora&ccedil;&otilde;es, desobsess&otilde;es, ou, se preciso for, &agrave;s oferendas de flores, bebidas, frutos, sucos, ch&aacute;s, alimentos, incensos e velas. A oferenda, al&eacute;m de opera&ccedil;&atilde;o espiritual/vibracional, &eacute; tamb&eacute;m uma rever&ecirc;ncia espont&acirc;nea aos Sagrados Orix&aacute;s e &eacute; recomendada a sua pr&aacute;tica aos seus fi&eacute;is, visto que entendemos que esses elementos possuem elevadas vibra&ccedil;&otilde;es energ&eacute;ticas que podem ser manipuladas espiritualmente em beneficio de algo ou algu&eacute;m. Entendemos tamb&eacute;m que um dos objetivos da Umbanda &eacute; o de elevar e sublimar o esp&iacute;rito e seus iniciados e assistidos pela &eacute;tica de Cristo.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">PRINC&Iacute;PIO DE IGUALDADE</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">23. A Umbanda defende a todos um tratamento digno e igualit&aacute;rio, pois ningu&eacute;m pode ser privilegiado, favorecido, prejudicado, discriminado, privado de direitos ou dispensado de deveres em raz&atilde;o de ascend&ecirc;ncia, descend&ecirc;ncia, sexo, orienta&ccedil;&atilde;o sexual, cor, etnia, ra&ccedil;a, idade, l&iacute;ngua, religi&atilde;o, descren&ccedil;a religiosa, grau de instru&ccedil;&atilde;o, condi&ccedil;&atilde;o econ&ocirc;mica e social, territ&oacute;rio de origem, convic&ccedil;&atilde;o pol&iacute;tica, ideol&oacute;gica e filos&oacute;fica.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">DIREITO &Agrave; VIDA</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">24. A religi&atilde;o de Umbanda defende que a vida humana &eacute; inviol&aacute;vel.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">25. N&atilde;o &eacute; admiss&iacute;vel para a Umbanda a pena de morte.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">SUIC&Iacute;DIO / EUTAN&Aacute;SIA / DISTANASIA / HOMIC&Iacute;DIO</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">26. A Umbanda, por valorizar a vida, nos aspectos terreno e espiritual, entende que a passagem deve ser natural, respeitando a Lei do Carma e aprendizados importantes ao esp&iacute;rito.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">27. A Umbanda defende que ningu&eacute;m tem o direito de abreviar voluntariamente a sua vida pelo suic&iacute;dio.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">28. S&oacute; o Criador, atrav&eacute;s de Sua Onisci&ecirc;ncia, Onipresen&ccedil;a e Onipot&ecirc;ncia, sabe o momento do desenlace carnal de qualquer individuo.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">29. Assim, mesmo no caso em que a morte &eacute; inevit&aacute;vel e a pessoa esteja em situa&ccedil;&atilde;o de sofrimento, a Eutan&aacute;sia ativa praticada por pessoas, mesmo que com motiva&ccedil;&atilde;o altru&iacute;stica &eacute; compreendida pela Umbanda como a falta de resigna&ccedil;&atilde;o e de submiss&atilde;o &agrave; vontade do Divino Criador.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">30. A Distan&aacute;sia que &eacute; prolongamento da vida por tratamentos extraordin&aacute;rios e a Orton&aacute;sia, que &eacute; a decis&atilde;o de n&atilde;o se submeter a tais tratamentos considerados paliativos, do ponto de vista cl&iacute;nico, legal e espiritual, n&atilde;o ferem o conceito religioso de Umbanda porque o paciente &eacute; livre para submeter-se ou n&atilde;o a tratamentos e cirurgias consideradas ou n&atilde;o de risco, e se o fizer, vir&aacute; a falecer de causas naturais da evolu&ccedil;&atilde;o da doen&ccedil;a, sem interfer&ecirc;ncias de pessoas no processo do Criador.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">31. Pr&aacute;ticas que atentam contra a vida humana ou animal, n&atilde;o s&atilde;o aceitas pela Umbanda.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">32. Por&eacute;m, homic&iacute;dio cometido em leg&iacute;tima defesa pr&oacute;pria ou de terceiros, ou por erro n&atilde;o censur&aacute;vel, n&atilde;o acarreta &ocirc;nus espirituais sobre tais fatos.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">ABORTO</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">33. A Umbanda &eacute; contra a pr&aacute;tica do aborto considerado interrup&ccedil;&atilde;o da gesta&ccedil;&atilde;o.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">34. Na Umbanda entende-se que a partir da concep&ccedil;&atilde;o da vida pr&eacute;-embrion&aacute;ria j&aacute; existe um Esp&iacute;rito que anseia por sua evolu&ccedil;&atilde;o.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">35. Os progenitores com ou sem aux&iacute;lio deterceiras pessoas que provoquem o aborto por qualquer meio, e em todo per&iacute;odo da gesta&ccedil;&atilde;o, cometer&atilde;o uma transgress&atilde;o &agrave; Lei de Deus, porque isso impede o esp&iacute;rito de passar pelas provas necess&aacute;rias &agrave; sua evolu&ccedil;&atilde;o, necessitando do corpo em forma&ccedil;&atilde;o como seu instrumento.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">36. Quando o nascimento da crian&ccedil;a colocar em perigo a vida da m&atilde;e, &eacute; prefer&iacute;vel, por bom senso e na forma da lei, manter a vida da genitora.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">37. O aconselhamento direto com os Guias Espirituais &eacute; fundamental para que as a&ccedil;&otilde;es se baseiem sempre na Espiritualidade e na particularidade de cada situa&ccedil;&atilde;o que envolva a forma&ccedil;&atilde;o e desenvolvimento de vida humana.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">38. No caso de ocorrer ou ter ocorrido o aborto por decis&atilde;o de qualquer natureza, a Umbanda jamais condenar&aacute; os envolvidos, ocupando-se, antes, em acolhe-los e prestar-lhes orienta&ccedil;&atilde;o e conforto espiritual.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">DIREITO &Agrave; INTEGRIDADE PESSOAL</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">39. A religi&atilde;o de Umbanda defende que a integridade moral e f&iacute;sica das pessoas &eacute; inviol&aacute;vel.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">40. Ningu&eacute;m pode ser submetido &agrave; tortura f&iacute;sica ou mental, nem a maus tratos ou penas cru&eacute;is, degradantes ou desumanas.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">PEDOFILIA / MAUS TRATOS</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">41. A Umbanda n&atilde;o aceita qualquer forma ou ato que atente contra a integridade f&iacute;sica e moral da crian&ccedil;a e do adolescente, em especial os casos de pedofilia praticada por todo e qualquer meio, inclusive por internet, assim como as condutas de maus tratos, defendendo que as leis j&aacute; estabelecidas devam ser aplicadas, nomeadamente, a Conven&ccedil;&atilde;o dos Direitos da Crian&ccedil;a.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">42. Pessoas que possuem desvio de conduta em rela&ccedil;&atilde;o &agrave;s crian&ccedil;as e adolescentes podem estar obsediadas e necessitam de orienta&ccedil;&atilde;o espiritual e acompanhamento psicol&oacute;gico, al&eacute;m de se submeterem &agrave; aplica&ccedil;&atilde;o das leis civis e criminais pertinentes.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">VIOL&Ecirc;NCIA DOM&Eacute;STICA</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">43. A Umbanda n&atilde;o aceita qualquer forma de viol&ecirc;ncia dom&eacute;stica, atendendo aos par&acirc;metros da legisla&ccedil;&atilde;o vigente com destaque para os Princ&iacute;pios das Na&ccedil;&otilde;es Unidas para as Pessoas Idosas, Conven&ccedil;&atilde;o sobre a elimina&ccedil;&atilde;o de todas as formas de discrimina&ccedil;&atilde;o contra as mulheres e a Conven&ccedil;&atilde;o sobre os Direitos das Pessoas com Defici&ecirc;ncia e a Carta das Na&ccedil;&otilde;es Unidas (O.N.U.), segundo os quais os direitos da pessoa humana devem ser preservados. No &acirc;mbito dom&eacute;stico, a pr&aacute;tica do respeito, aceita&ccedil;&atilde;o das diferen&ccedil;as, e conviv&ecirc;ncia de harmonia devem ser cultivados entre os familiares de todas as idades. As rela&ccedil;&otilde;es sexuais, dentro e fora do casamento ou da uni&atilde;o est&aacute;vel devem ser sempre consentidas pelas pessoas envolvidas, sendo que a Umbanda condena qualquer ato sexual obtido mediante viol&ecirc;ncia ou contra a vontade da pessoa.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">PRECONCEITO &Eacute;TNICO</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">44. A Umbanda n&atilde;o aceita o preconceito &eacute;tnico e racial. O preconceito racial &eacute; antes de tudo, uma demonstra&ccedil;&atilde;o de atraso espiritual e desconhecimento das Leis Divinas. Aquele que diminui ou persegue o irm&atilde;o pela cor da pele ou por qualquer outra caracter&iacute;stica &eacute;tnica, viola a regra de ouro presente nas mais diversas tradi&ccedil;&otilde;es espirituais e religiosas: &ldquo;Amar a Deus sobre todas as coisas, e ao pr&oacute;ximo como a si mesmo&rdquo;.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">ORIENTA&Ccedil;&Atilde;O SEXUAL E IDENTIDADE DE G&Ecirc;NERO</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">45. NA Umbanda todo ser humano &eacute; visto como irm&atilde;o espiritual, sendo aceita qualquer orienta&ccedil;&atilde;o sexual e identidade de g&ecirc;nero. Assim, a religi&atilde;o entende e acolhe Esp&iacute;ritos, e n&atilde;o o g&ecirc;nero ou a sexualidade. Discrimina&ccedil;&atilde;o e preconceito n&atilde;o s&atilde;o ensinados pelos nossos Guias Espirituais, posto que a Umbanda acolhe a todos. Desta forma, &eacute; fundamental respeitarmos a condi&ccedil;&atilde;o de cada indiv&iacute;duo: heterossexualidade, homossexualidade, bissexualidade, transexualidade e intersexualidade s&atilde;o quest&otilde;es de foro &iacute;ntimo e pessoal.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">O PAPEL DA MULHER NA SOCIEDADE E NA UMBANDA</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">46. A Umbanda defende o direito de igualdade, sendo que a mulher deve ocupar qualquer posi&ccedil;&atilde;o na sociedade e no mercado de trabalho, com o mesmo tratamento, conforme o vertido na Conven&ccedil;&atilde;o sobre a elimina&ccedil;&atilde;o de todas as formas de discrimina&ccedil;&atilde;o contra as mulheres.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">47. As mulheres na Umbanda est&atilde;o em todos os n&iacute;veis hier&aacute;rquicos, ritual&iacute;sticos e doutrin&aacute;rios da religi&atilde;o.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">CRIAN&Ccedil;AS NA UMBANDA</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">48. NA Umbanda todas as decis&otilde;es que digam respeito &agrave;s crian&ccedil;as devem ter em conta o seu melhor interesse consideradas suas peculiaridades de pessoa em desenvolvimento, em harmonia com o estipulado na Conven&ccedil;&atilde;o dos Direitos da Crian&ccedil;a.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">49. A UMBANDA reconhece que a presen&ccedil;a das crian&ccedil;as nas sess&otilde;es &eacute; um processo importante na sua pr&oacute;pria forma&ccedil;&atilde;o espiritual, assim como para sua educa&ccedil;&atilde;o e assist&ecirc;ncia religiosas.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">50. A Umbanda garante &agrave;s crian&ccedil;as, o direito de conhecer segundo os preceitos da religi&atilde;o, a mensagem universal da Jesus, com sua magnitude em Deus e nos Sagrados Orix&aacute;s, atrav&eacute;s do atendimento medi&uacute;nico, do batizado, passes e desenvolvimento. Promovendo o respaldo moral, f&iacute;sico e espiritual contra todas as formas de viol&ecirc;ncia.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">51. A Umbanda incentiva a crian&ccedil;a para que reconhe&ccedil;a desde cedo sua import&acirc;ncia, valor e car&aacute;ter, concedendo-lhe o direito de livre escolha condizente &agrave; sua pureza e maturidade &agrave;s nossas cren&ccedil;as, garantido sempre o seu amparo. &Eacute; admiss&iacute;vel e reconhecida a pr&aacute;tica da Evangeliza&ccedil;&atilde;o Infantil, a fim de instruir crian&ccedil;as e adolescentes em condutas morais e &eacute;ticas, al&eacute;m de proporcionar aulas educativas a respeito da Umbanda.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">IDOSOS NA UMBANDA</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">52. A Umbanda defende que os idosos devem ter acesso aos recursos educativos, culturais, recreativos e espirituais da sociedade.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">53. Os idosos devem ser tratados de forma justa, independentemente de sua idade, n&atilde;o podendo ser privados do acolhimento dentro da religi&atilde;o e do desenvolvimento medi&uacute;nico.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">54. A Umbanda preconiza o respeito, o amparo e a assist&ecirc;ncia aos idosos, no &acirc;mbito familiar e social, com base no amor, na caridade, no reconhecimento e na legisla&ccedil;&atilde;o em vigor, em especial nos Princ&iacute;pios das Na&ccedil;&otilde;es Unidas para as Pessoas Idosas.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">DEFICIENTES</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">55. Na Umbanda, nenhuma pessoa portadora de defici&ecirc;ncia cong&ecirc;nita ou adquirida, seja de natureza f&iacute;sica, sensorial ou intelectual &eacute; privada de acolhimento ou desenvolvimento medi&uacute;nico.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">56. A Umbanda compreende que as defici&ecirc;ncias se restringem &agrave; carne e n&atilde;o ao esp&iacute;rito, portanto, as limita&ccedil;&otilde;es do corpo material se tornam nulas, mediante a nossa f&eacute; e o Plano Espiritual. Porquanto, como disseminadores de amor ao pr&oacute;ximo, n&atilde;o nos cabe desmerecer ou restringir quaisquer que sejam as condi&ccedil;&otilde;es f&iacute;sicas, mentais ou psicol&oacute;gicas de um irm&atilde;o, pois somos livres de julgamentos e permitimos que todos aqueles que buscam a doutrina umbandista sejam tratados com igualdade e respeito.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">57. Aos dirigentes de Templos, de Federa&ccedil;&otilde;es, pede-se privilegiar a acessibilidade, conforme a caridade, o bom senso e as leis vigentes, designadamente, a Conven&ccedil;&atilde;o Sobre os Direitos das Pessoas com Defici&ecirc;ncia e o Estatuto da Pessoa com Defici&ecirc;ncia. Em &acirc;mbito internacional segue a Carta das Na&ccedil;&otilde;es Unidas, que reconhece a dignidade e valor inerentes e os direitos iguais e inalien&aacute;veis.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">ALCO&Oacute;LATRAS E TOXIC&Ocirc;MANOS</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">58. Todos que recorrem aos Terreiros de Umbanda encontrar&atilde;o o lado assistencialista. O dependente qu&iacute;mico e o alc&oacute;olatra devem ser tratados sem preconceito e discrimina&ccedil;&atilde;o, tendo total assist&ecirc;ncia por parte da Umbanda.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">59. A Umbanda respeita a vontade e o livre arb&iacute;trio do indiv&iacute;duo de buscar e aceitar o tratamento espiritual. Nos tratamentos devem ser observados e respeitados o lado psicol&oacute;gico, a depend&ecirc;ncia qu&iacute;mica e a aten&ccedil;&atilde;o espiritual devem ser fornecidos para o dependente e sua fam&iacute;lia.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">CASAMENTO</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">60. A Umbanda defende que o casamento deve dar-se por amor e livre arb&iacute;trio, onde o casal &eacute; orientado e acolhido tamb&eacute;m espiritualmente. Independentemente, da orienta&ccedil;&atilde;o sexual, etnia, instru&ccedil;&atilde;o, condi&ccedil;&atilde;o social e religi&atilde;o.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">61. Na vis&atilde;o umbandista &eacute; irrelevante a heterossexualidade, a homossexualidade, bissexualidade, a transexualidade e a intersexualidade, ou se um dos consortes n&atilde;o professar a religi&atilde;o umbandista. Reservamos a todos, direitos iguais de matrim&ocirc;nio, respeitando a orienta&ccedil;&atilde;o sexual de cada um.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">62. A Umbanda compreende que o casamento religioso funciona como base espiritual para a fam&iacute;lia e tanto o corpo medi&uacute;nico quanto a assist&ecirc;ncia, t&ecirc;m o direito a este sacramento.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">63. Na Umbanda, o matrim&ocirc;nio tamb&eacute;m &eacute; assegurado como direito &agrave;queles que j&aacute; se divorciaram.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">DIV&Oacute;RCIO</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">64. Os Guias Espirituais, na Umbanda, n&atilde;o incentivam o div&oacute;rcio, por&eacute;m, n&atilde;o compactuam com relacionamentos infelizes, que fazem com que o esp&iacute;rito fique abalado pelo &oacute;dio, pelo sofrimento, pelo desrespeito, pela falta de amor que, por muitas vezes, podem causar riscos &agrave; integridade f&iacute;sica, moral e espiritual de um dos c&ocirc;njuges ou ao casal, e por consequ&ecirc;ncia, traumatizar familiares, filhos e amigos.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">65. O casamento indissol&uacute;vel &eacute; cria&ccedil;&atilde;o humana, por dogmas religiosos e/ou de ordem social e econ&ocirc;mica. Na Umbanda, acredita-se que o carma do casal pode ser breve ou durar uma vida inteira, de acordo com o que sua pr&oacute;pria miss&atilde;o espiritual determina, e n&atilde;o se imp&otilde;e uma conviv&ecirc;ncia de infelicidade ou viol&ecirc;ncia dom&eacute;stica e sexual.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">ADO&Ccedil;&Atilde;O</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">66. O posicionamento da Umbanda n&atilde;o &eacute; apenas favor&aacute;vel, mas tamb&eacute;m incentivador &agrave; ado&ccedil;&atilde;o.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">67. O acolhimento f&iacute;sico, moral e espiritual do adotado, sempre levando em considera&ccedil;&atilde;o as condi&ccedil;&otilde;es dos pais, &eacute; o de respeito, carinho, amor e prote&ccedil;&atilde;o para o resgate da crian&ccedil;a e do adolescente e sua inser&ccedil;&atilde;o nos princ&iacute;pios de cidadania, favorecendo-o a ser consciente de suas responsabilidades e voltado para a pr&aacute;tica do bem. Esse ser humano, bem como aqueles que ser&atilde;o seus pais, precisam da compreens&atilde;o de sua condi&ccedil;&atilde;o humana e espiritual, devendo exercer a cria&ccedil;&atilde;o e educa&ccedil;&atilde;o do adotado segundo os preceitos da dignidade humana, paternidade respons&aacute;vel e do planejamento familiar, como determina a Conven&ccedil;&atilde;o dos Direitos da Crian&ccedil;a.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">68. Acreditamos no mesmo direito por parte de pais e m&atilde;es heterossexuais, homossexuais, bissexuais, transexuais e intersexuais, pois a amplitude desse ato n&atilde;o se reserva &agrave; condi&ccedil;&atilde;o sexual ou de g&ecirc;nero e, sim, ao resgate c&aacute;rmico em condi&ccedil;&otilde;es tanto materiais quanto emocionais para a educa&ccedil;&atilde;o da crian&ccedil;a e do adolescente.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">PRESERVATIVOS E M&Eacute;TODOS CONTRACEPTIVOS</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">69. A Umbanda apoia o uso de preservativos e m&eacute;todos contraceptivos, como meios de prote&ccedil;&atilde;o contra DSTs (doen&ccedil;as sexualmente transmiss&iacute;veis) e preven&ccedil;&atilde;o de gravidez indesejada. Cada qual deve saber e escolher o momento de gerar um novo ser, que necessitar&aacute; de amor, compreens&atilde;o, educa&ccedil;&atilde;o, orienta&ccedil;&atilde;o e discernimento ao longo de sua vida. Nesse sentido, o uso de m&eacute;todos contraceptivos &eacute; um modo de proteger a vida.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">70. O uso de contraceptivo &eacute; aceito pela religi&atilde;o da UMBANDA, pois respeita o livre arb&iacute;trio, o controle de natalidade e o planejamento familiar.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">DOA&Ccedil;&Atilde;O DE &Oacute;RG&Atilde;OS</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">71. A Doutrina Umbandista v&ecirc; com bons olhos a doa&ccedil;&atilde;o de &oacute;rg&atilde;os, em vida e depois da morte, nos limites da legisla&ccedil;&atilde;o vigente em cada pa&iacute;s.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">72. A Umbanda defende mesmo que a separa&ccedil;&atilde;o entre o Esp&iacute;rito e o corpo f&iacute;sico n&atilde;o se tenha completado, como nos casos de morte cerebral, deste modo a Espiritualidade disp&otilde;e de recursos para impedir impress&otilde;es penosas e sofrimentos ao Esp&iacute;rito doador.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">73. A doa&ccedil;&atilde;o de &oacute;rg&atilde;os n&atilde;o &eacute; contr&aacute;ria &agrave;s leis da Natureza, porque beneficia outras pessoas e o pr&oacute;prio esp&iacute;rito do doador em sua evolu&ccedil;&atilde;o espiritual e, al&eacute;m disso, &eacute; uma oportunidade para que se desenvolvam os conhecimentos cient&iacute;ficos no plano material, colocando-os &agrave; servi&ccedil;o de v&aacute;rios necessitados.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">74. O mesmo se d&aacute; em rela&ccedil;&atilde;o &agrave; doa&ccedil;&atilde;o de sangue, medula e qualquer tecido org&acirc;nico que venha proporcionar ajuda ao semelhante. A Umbanda, assim como qualquer religi&atilde;o, necessita incentivar a pr&aacute;tica de doa&ccedil;&atilde;o para amparar milh&otilde;es de irm&atilde;os necessitados pelo mundo.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">CREMA&Ccedil;&Atilde;O</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">75. A Umbanda n&atilde;o rejeita a crema&ccedil;&atilde;o.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">76. A crema&ccedil;&atilde;o &eacute; leg&iacute;tima para todos aqueles que a desejam, desde que haja um per&iacute;odo de, pelo menos, setenta e duas (72) horas de expecta&ccedil;&atilde;o para a ocorr&ecirc;ncia em qualquer forno cremat&oacute;rio, o que poder&aacute; verificar-se com o dep&oacute;sito de despojos humanos em ambiente frio. Esse per&iacute;odo &eacute; necess&aacute;rio, pois existem sempre muitos ecos de sensibilidade entre o Esp&iacute;rito desencarnado e o corpo onde se extinguiu o t&ocirc;nus vital, nas primeiras horas sequentes ao desenlace, em vista os flu&iacute;dos org&acirc;nicos que o Esp&iacute;rito ainda solicita para as sensa&ccedil;&otilde;es da exist&ecirc;ncia material.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">77. O sepultamento ou a crema&ccedil;&atilde;o nada mais representam para o Esp&iacute;rito, que a desagrega&ccedil;&atilde;o mais lenta ou mais r&aacute;pida das estruturas entretecidas em agentes f&iacute;sicos, das quais se libertou.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">CANDIDATOS &Agrave; POLITICA NA UMBANDA</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">78. A Umbanda chama a aten&ccedil;&atilde;o para o pensamento sobre a pol&iacute;tica p&uacute;blica participativa. &Eacute; relevante a constru&ccedil;&atilde;o de organiza&ccedil;&atilde;o pol&iacute;tica, pois s&oacute; assim, conquistaremos o que &eacute; de direito de qualquer cidad&atilde;o que professa sua f&eacute;.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">79. A participa&ccedil;&atilde;o do religioso deve ser incentivada atrav&eacute;s da consci&ecirc;ncia de institucionalizarmos nossos ideais.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">80. Os representantes p&uacute;blicos necessitam comprometer-se com a comunidade religiosa a qual est&aacute; inserido; deixando seu gabinete aberto para todos os projetos que visam o coletivo religioso.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><strong><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">LIVRE ARB&Iacute;TRIO</span></span></span></span></strong></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">81. A Umbanda, com sua plenitude, assegura aos indiv&iacute;duos a sua liberdade e felicidade, n&atilde;o compactuando com a ideologia de &ldquo;acorrentar&rdquo; filhos de f&eacute; ou adeptos em detrimento da casa.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">82. Al&eacute;m disso, n&atilde;o compactua/comunga com o emprego de amea&ccedil;as e viol&ecirc;ncias psicol&oacute;gicas ou morais para garantir o narrado no t&oacute;pico anterior.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:11pt"><span style="color:black"><span style="font-size:12.0pt">84. Umbanda preza pela liberdade individual e o direito de &ldquo;ir e vir&rdquo; dos adeptos, n&atilde;o interferindo no livre arb&iacute;trio dos indiv&iacute;duos, sendo este, uma das Leis Divinas de nossa religi&atilde;o e da pr&oacute;pria espiritualidade. Tamb&eacute;m n&atilde;o exerce qualquer tipo de viol&ecirc;ncia (moral e psicol&oacute;gica), falseando verdades sobre a liturgia umbandista para restringir o direito de escolha de seus fieis.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><span style="font-size:16px"><span style="color:black">85. A Umbanda aceita os estudos teol&oacute;gicos desde que respeite todas as vertentes a ela atribu&iacute;da, sem a&ccedil;&otilde;es tendenciosas que crie conflitos sobre a diversidade existente em seus estudos. Do ponto de vista acad&ecirc;mico de historiadores e antrop&oacute;logos entende-se que a absor&ccedil;&atilde;o do documento Carta Magna de Umbanda &eacute; de fundamental import&acirc;ncia. A Umbanda por sua miscigena&ccedil;&atilde;o e pluralidade de interpreta&ccedil;&otilde;es n&atilde;o pode estar presa a ideologias que n&atilde;o coadunam com o respeito aos itens 1- 2-12-13-14 e 15, onde demonstra uma diversidade interpretativa de sua origem e jamais se fixando em um conceito fechado, mas respeitando a todas as formas de entendimento. A&ccedil;&atilde;o &uacute;nica desta religi&atilde;o que n&atilde;o se compara a nenhuma outra existente, portanto deve ser classificada por antrop&oacute;logos por este olhar peculiar da religi&atilde;o de Umbanda que demonstra ser uma grande s&iacute;ntese universal.</span></span></span></p>

					</p>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 26/11/2018
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>