<?php $results['pageTitle'] = "As Linhas Transitórias ou Intermediárias | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
				<h2 class="card-title"><center>AS LINHAS TRANSITÓRIAS OU INTERMEDIÁRIAS</center></h2>
					<p class="card-text">
						<img src="images/boiadeiros.jpg" class="card-img-top"></img>

<br></br>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A linha de Boiadeiros &eacute; a primeira na escala vibrat&oacute;ria de evolu&ccedil;&atilde;o dos Guias de Direita, onde se apresentam os esp&iacute;ritos egressos das Linhas dos Guardi&otilde;es. Ou seja, o Boiadeiro pode ser visto como um Exu que adquiriu m&eacute;rito e decidiu se integrar &agrave;s Linhas da Direita. S&atilde;o conhecidos tamb&eacute;m como Caboclos Boiadeiros. Atuam nas sete Linhas da Umbanda, ora regidos pelo Orix&aacute; Ogum, ora pelo Orix&aacute; Oi&aacute; (Ians&atilde;). Trazem, como simbologia, o la&ccedil;o e o chicote. S&atilde;o audazes e aguerridos. Atuam como refreadores de &ldquo;demandas&rdquo; e do baixo astral, rigorosos no trato com a espiritualidade &ldquo;trevosa&rdquo;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Boiadeiros na Umbanda s&atilde;o entidades espirituais de homens que trabalharam no campo, na rudeza da condu&ccedil;&atilde;o do gado e na dureza da lida do sert&atilde;o. Operam nos terreiros com seu la&ccedil;o e seu grito caracter&iacute;stico, capturando esp&iacute;ritos deca&iacute;dos e quiumbas que atormentam os consulentes, encaminhando-os para as falanges de socorro e recupera&ccedil;&atilde;o.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas caracter&iacute;sticas dos boiadeiros</span></span></span></u></strong></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: Jetru&aacute;! X&ecirc;tro! Marrumba X&ecirc;tro! Getru&aacute; boiadeiro! (Salve aquele que tem bra&ccedil;o forte, pulso firme).</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dia da Semana: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Quinta-feira.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebidas:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> Cacha&ccedil;a com mel, batida de coco, caf&eacute;, caf&eacute; com cacha&ccedil;a.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fumo: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cigarro de palha e fumo de rolo.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cozinha:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> Feij&atilde;o tropeiro, ab&oacute;bora com farofa.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Utens&iacute;lios: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chap&eacute;u de couro, la&ccedil;os, berrantes, guias de couro tran&ccedil;ado.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Irradia&ccedil;&atilde;o:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> A irradia&ccedil;&atilde;o depende do Orix&aacute;.</span></span></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<img src="images/baianos.jpg" class="card-img-top"></img>	

<br></br>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Linha dos Baianos &eacute; formada por Esp&iacute;ritos alegres, brincalh&otilde;es e descontra&iacute;dos. Atuam desmanchando demandas. S&atilde;o bons conselheiros e orientadores. Gostam muito de trabalhar girando e dan&ccedil;ando com passos pr&oacute;prios. Agradecem &agrave;s festas que lhe s&atilde;o oferecidas. Bebem batida de coco e comem comidas t&iacute;picas da cozinha baiana.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Baianos que se apresentam na Umbanda s&atilde;o Esp&iacute;ritos ligados ao Nordeste do nosso Pa&iacute;s, que viveram ou passaram parte de sua vida em Estados dessa regi&atilde;o. Tiveram suas li&ccedil;&otilde;es e aprenderam muito com os Mestres do Catimb&oacute; e da Pajelan&ccedil;a. S&atilde;o os Esp&iacute;ritos respons&aacute;veis pela &ldquo;esperteza&rdquo; do homem em sua jornada terrena.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Povo Baiano vem ao Terreiro para trazer seu Ax&eacute;, sua Energia Positiva. A gira &eacute; sempre muito animada. S&atilde;o Entidades que tem muito a nos ensinar, sempre com uma resposta certeira e r&aacute;pida para nossas quest&otilde;es. Com seus cocos, azeite de dend&ecirc;, comidas e cantigas t&iacute;picas da regi&atilde;o, realizam trabalhos em prol da evolu&ccedil;&atilde;o espiritual de todos. Por terem vivido em &eacute;pocas mais recentes, s&atilde;o Esp&iacute;ritos mais pr&oacute;ximos de n&oacute;s.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Suas rezas, comidas, bebidas e dan&ccedil;as, s&atilde;o apropriadas para cada ocasi&atilde;o. No desenvolvimento de suas giras, os Baianos trazem como mensagem a forma e o saber lidar com as adversidades de nosso dia-a-dia, com a alegria, a flexibilidade, a magia e a brincadeira sadia.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">M&eacute;diuns introspectivos, quando incorporados com estes Guias, acabam se libertando e demonstrando alegria e descontra&ccedil;&atilde;o. Outros, que j&aacute; s&atilde;o descontra&iacute;dos por sua pr&oacute;pria natureza, aprendem a desenvolver com os Baianos outras qualidades, como a for&ccedil;a de viver diante dos problemas e situa&ccedil;&otilde;es cotidianas e o amparo ao pr&oacute;ximo, transformando a tristeza em alegria e esperan&ccedil;a. Costumam trabalhar para o descarrego e o equil&iacute;brio.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O dia dedicado a eles depende de cada regi&atilde;o, costume e devo&ccedil;&atilde;o.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas caracter&iacute;sticas dos baianos</span></span></span></u></strong></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: Salve a Baianada! </span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cores:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> Laranja ou a cor definida pela entidade.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebidas:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> &Aacute;gua de coco, batida de coco.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fumo: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cigarro de palha.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cozinha:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> Cocada, coco, farofa com carne seca.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Utens&iacute;lios: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chap&eacute;u de couro ou de palha.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Irradia&ccedil;&atilde;o:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> A irradia&ccedil;&atilde;o depende do Orix&aacute;.</span></span></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<img src="images/marinheiro.jpg" class="card-img-top"></img>	

<br></br>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Marinheiros s&atilde;o em sua grande maioria esp&iacute;ritos que militam a Umbanda para dar sustento no campo da dilui&ccedil;&atilde;o de cargas trevosas. Outros atuam como elementos de sustenta&ccedil;&atilde;o de trabalhos voltados a curas, atraindo os poderes elementais que estes esp&iacute;ritos trazem consigo.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os guias incorporados dan&ccedil;am, giram, balan&ccedil;am, gesticulam e fazem diversos movimentos para desprendimento energ&eacute;tico. Desta forma, os Guias liberam n&atilde;o s&oacute; a energia corp&oacute;rea do m&eacute;dium, mas tamb&eacute;m o poder de seu mist&eacute;rio, emanando ondas energ&eacute;ticas dentro do campo espiritual do m&eacute;dium e do Terreiro.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os marinheiros, por meio de movimentos ondulares ou de balan&ccedil;os que mais lembram o cambalear de uma pessoa embriagada, realizam seu trabalho redentor dentro dos campos da Umbanda Sagrada. &Eacute; importante que os m&eacute;diuns e principalmente os assistidos, saibam de tal fato, para que estes n&atilde;o deturpem e n&atilde;o deem um mal sentido aos trabalhos de Umbanda.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Entidades de Marinheiros trabalham na irradia&ccedil;&atilde;o dos Orix&aacute;s Iemanj&aacute; e Oxum, que comp&otilde;em e regem o chamado &ldquo;Povo da &Aacute;gua&rdquo;.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas caracter&iacute;sticas dos marinheiros</span></span></span></u></strong></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: Salve o Povo D&rsquo;&aacute;gua! Salve os Marinheiros!</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fumo: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cigarro de filtro.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Irradia&ccedil;&atilde;o:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> A irradia&ccedil;&atilde;o da Orix&aacute; Iemanj&aacute; ou Oxum.</span></span></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<img src="images/agua.jpg" class="card-img-top"></img>	

<br></br>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Sereias s&atilde;o seres que nunca encarnaram e atuam como seres encantados, como os elementais. S&atilde;o seres naturais, regidas por Iemanj&aacute;, Oxum e Nan&atilde;.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Todas incorporam nos cantos de Iemanj&aacute;, mas podem-se tamb&eacute;m entoar cantos de Oxum e Nan&atilde; durante suas manifesta&ccedil;&otilde;es. Elas reagem aos pontos cantados dan&ccedil;ando suas dan&ccedil;as rituais, mais r&aacute;pidas nos cantos de Oxum e mais lentas nos cantos de Nan&atilde;.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Elas t&ecirc;m elevado poder de limpeza, purifica&ccedil;&atilde;o e descarga de energias negativas. No entanto, h&aacute; pessoas que n&atilde;o se sentem bem com a influ&ecirc;ncia dessas For&ccedil;as, especialmente se n&atilde;o conseguirem exercer a mediunidade com harmonia e equil&iacute;brio. </span></span></span></span></span></p>
					</p>
            </div>
            <div class="card-footer text-muted">
				06/01/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>