<?php $results['pageTitle'] = "OXUM | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
			<img class="card-img-top" src="images/oxum.jpg" alt="Card image cap">
				<h2 class="card-title"><center>OXUM</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A mais bela, sensual e pac&iacute;fica de todos os orix&aacute;s. A menina mo&ccedil;a &eacute; considerada a rainha de todo o ouro do mundo. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O nome Oxum vem do Rio Oxum (Os&uacute;n), que corre na Iorubal&acirc;ndia. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Filha de Oxal&aacute; e Iemanj&aacute;, Oxum foi a primeira filha do casal, e por isso, foi coberta de aten&ccedil;&atilde;o, dengos e mimos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Oxum &eacute; o nome de um rio na regi&atilde;o de Oxogb&ocirc;, na Nig&eacute;ria. As lendas dizem ser esta a morada deste orix&aacute;. Dona das &aacute;guas doces, dos lagos, das cachoeiras e dos rios mansos e cristalinos, faz par com Iemanj&aacute; no &acirc;mbito da vida. Iemanj&aacute; gera, Oxum mant&eacute;m e desenvolve. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na &Aacute;frica, sua associa&ccedil;&atilde;o com a fecundidade &eacute; t&atilde;o grande que n&atilde;o se semeava o campo sem que antes fossem prestadas as devidas ofertas e homenagens a ela. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Entretanto, na Umbanda, Iemanj&aacute; gera a vida e depois ampara as crian&ccedil;as no parto, mas toda a gesta&ccedil;&atilde;o &eacute; de Oxum. A ela tamb&eacute;m &eacute; atribu&iacute;da a prote&ccedil;&atilde;o a todas as crian&ccedil;as at&eacute; o momento de falar e andar, a partir desse ponto as crian&ccedil;as s&atilde;o regidas por Cosme e Dami&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Apesar disto, &eacute; a Oxum que as mulheres recorrem quando n&atilde;o conseguem engravidar. Oxum rege ainda a menstrua&ccedil;&atilde;o e tamb&eacute;m divide a maternidade com a rainha do mar. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A palavra que melhor descreve este orix&aacute; &eacute; amor. A deusa do amor e da beleza usa de todos os seus atributos para alcan&ccedil;ar seus objetivos, podendo chegar a medidas extremas quando se sentir amea&ccedil;ada. Usar&aacute; toda sua ast&uacute;cia, mal&iacute;cia e determina&ccedil;&atilde;o contra seus inimigos e advers&aacute;rios. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A sedu&ccedil;&atilde;o &eacute; seu ponto forte, entretanto, apaixona-se facilmente, e nesse estado, se entrega sem limites chegando ao ponto de submiss&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Uma das &aacute;rea de atua&ccedil;&atilde;o de Oxum &eacute; a sexualidade dos seres, sendo que os &oacute;rg&atilde;os reprodutores tamb&eacute;m s&atilde;o por ela regidos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Orix&aacute; que adora enfeites como colares, brincos e pulseiras, adorna seus filhos com ouro. Quem precisa de dinheiro &eacute; s&oacute; pedir a Oxum que ela concede. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Considerada a dona do ovo, que tamb&eacute;m &eacute; um de seus s&iacute;mbolos por ser a representa&ccedil;&atilde;o m&aacute;xima da fecundidade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em algumas na&ccedil;&otilde;es, &eacute; considerada como aquela que cura com a &aacute;gua fria. Cura as crian&ccedil;as e as fazem beber mel, sendo a abelha seu animal s&iacute;mbolo. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sempre representada como uma mo&ccedil;a de fei&ccedil;&otilde;es magn&iacute;ficas, olhando-se para um espelho que carrega na m&atilde;o direita e abanando-se com um leque que carrega na m&atilde;o esquerda. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Seu culto, seus atributos e seus dom&iacute;nios s&atilde;o constantemente confundidos com os de Iemanj&aacute;. Afinal de contas, as duas trabalham com a fecundidade e a vida. Iemanj&aacute; gera, Oxum desenvolve e mant&eacute;m. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Carrega o t&iacute;tulo de Ialod&ecirc;, a mulher mais importante da cidade, isso demonstra sua nobreza. Considerada a rainha de toda a &aacute;gua doce do planeta, sabemos que sem esta &aacute;gua, a vida seria imposs&iacute;vel. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Inteligente e esperta, alheia a qualquer tipo de conflito, &eacute; excepcional diplomata. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A fecundidade de Oxum &eacute; tema t&atilde;o forte e recorrente que esse fundamento n&atilde;o estaria ligado somente &agrave; vida dos seres, pois sem Oxum &eacute; imposs&iacute;vel fecundar ideias e projetos. Sem seu ax&eacute; a vida n&atilde;o inicia e nem prospera. </span></span></span></span></span></p>

<ul>
	<li style="text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O que pedir?</span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Invocamos Oxum para alcan&ccedil;ar a fertilidade de mulheres est&eacute;reis, para alcan&ccedil;ar sorte no amor com a conquista do par ideal, na gesta&ccedil;&atilde;o das mulheres, em problemas com a menstrua&ccedil;&atilde;o ou aparelho reprodutor, para fecundar qualquer nova decis&atilde;o ou projeto, na agricultura, para obter riqueza ou dinheiro, para evitar conflitos e para a diplomacia. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Caracter&iacute;sticas dos filhos de Oxum </span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Oxum amam espelhos, joias caras, roupas bonitas e da moda. N&atilde;o saem de casa sem cuidar da vestimenta e dos cabelos. As mulheres n&atilde;o abrem m&atilde;o da maquiagem para todos os momentos. S&atilde;o vaidosos, elegantes e sensuais de forma natural. Gostam de tudo relacionado &agrave; beleza, como tratamentos de pele, e at&eacute; mesmo, as cirurgias pl&aacute;sticas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pierre Fatumbi Verger, grande pesquisador dos cultos africanos, escreveu: &quot;o arqu&eacute;tipo de Oxum &eacute; das mulheres graciosas e elegantes, com paix&atilde;o pelas joias, perfumes e vestimentas caras. Das mulheres que s&atilde;o s&iacute;mbolo do charme e da beleza. Voluptuosas e sensuais, por&eacute;m mais reservadas que as de Ians&atilde;. Elas evitam chocar a opini&atilde;o publica, &agrave; qual d&atilde;o muita import&acirc;ncia. Sob sua apar&ecirc;ncia graciosa e sedutora, escondem uma vontade muito forte e um grande desejo de ascens&atilde;o social&quot; </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Verger sintetizou muito bem o perfil dos filhos de Oxum. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Oxum zelam muito de sua imagem p&uacute;blica, por isso odeiam esc&acirc;ndalos e at&eacute; mesmo fofocas que possam atingir a imagem de bondosos e inocentes, fundamentos que cultuam e constroem com dedica&ccedil;&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Gostam de festas, de aparecer em p&uacute;blico, dos prazeres da vida e at&eacute; de seduzir o sexo oposto, com muita discri&ccedil;&atilde;o sempre. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tem tend&ecirc;ncia para engordar e o nariz do tipo batatinha. Os cabelos podem ser claros. Gosta de mudan&ccedil;as. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o narcisistas, a ponto de amarem mais a si mesmo que os outros. Mas, como s&atilde;o gentis e carinhosos, &eacute; muito dif&iacute;cil que outros percebam esta sua faceta. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o calmos, tranquilos e emotivos, com facilidade para o choro. &Agrave;s vezes infantis, mas est&atilde;o sempre prontos para ouvir e ajudar os outros. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Podem ser desconfiados, interesseiros, hip&oacute;critas, indecisos, ciumentos, intrigueiros, e, segundo alguns, fofoqueiros. N&atilde;o sabem recusar e nem dizer &ldquo;n&atilde;o&rdquo;. Ofendem-se com facilidade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As filhas de Oxum s&atilde;o boas m&atilde;es, boas cozinheiras, boas donas de casa e excelentes companheiras. Adoram crian&ccedil;as pequenas. D&atilde;o-se muito bem com trabalhos manuais. Tem facilidade para encontrar o amor verdadeiro. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A intui&ccedil;&atilde;o &eacute; o ponto forte dos filhos deste orix&aacute;, e seus filhos rapidamente aprendem a trabalhar com este dom. Por isso tamb&eacute;m s&atilde;o bons em adivinha&ccedil;&otilde;es e consultor de or&aacute;culos, pois a intui&ccedil;&atilde;o os guia facilmente. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Arquitetura, religi&atilde;o, ci&ecirc;ncias ocultas, com&eacute;rcio, est&eacute;tica e tudo ligado a beleza, psic&oacute;logas, educadoras de crian&ccedil;as pequenas, nutri&ccedil;&atilde;o e restaurantes s&atilde;o algumas das profiss&otilde;es ou ocupa&ccedil;&otilde;es perfeitas para os filhos deste Orix&aacute;. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Outros Detalhes</span></span></strong></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sincretismo: N. S. da Imaculada Concei&ccedil;&atilde;o, N. S. Aparecida;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Data de culto: 08 de Dezembro (NS Concei&ccedil;&atilde;o) ou 12 de Outubro (NS Aparecida);</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o: Ora i&ecirc;i&ecirc;&ocirc; ou Ai&ecirc;i&ecirc;&ocirc; (Salve a m&atilde;e do sorriso gentil); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Aacute;rea de atua&ccedil;&atilde;o: Gesta&ccedil;&atilde;o, amor, fertilidade, criatividade, novos projetos e id&eacute;ias, dinheiro e riqueza, diplomacia;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Elemento: &Aacute;gua;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chacra: Umbilical; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Metal: Ouro;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Astro regente: Lua (no quarto crescente);</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dia da semana: S&aacute;bado; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da guia: Azul com contas douradas, azul escuro ou amarela (em algumas casas);</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da vela: Azul escura, amarela (em algumas casas); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pedra: Top&aacute;zio amarelo ou azul;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebida: &Aacute;gua mineral ou champanhe branco; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Amal&aacute;: Quindim, moqueca e pir&atilde;o;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Frutas: p&ecirc;ssego amarelo, mel&atilde;o amarelo, damasco, ponkan, banana ouro, laranja lima, n&ecirc;spera, ma&ccedil;&atilde; e nectarina; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Flores: L&iacute;rios, palmas brancas ou amarelas, rosas brancas ou amarelas;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas ervas: Oriri, jasmim, vit&oacute;ria-r&eacute;gia, arnica montana, camomila, erva de Santa Maria, aguap&eacute;, m&atilde;e-boa, cal&ecirc;ndula, ip&ecirc;-amarelo, erva cidreira; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local de oferta: Cachoeiras, lagos e rios calmos e limpos; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Animais: Abelha e pomba;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Instrumentos: Abeb&eacute;, (leque ) e espelho; </span></span></span></span></span></li>
</ul>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fontes: </span></span></span></span></span></p>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Marcio Kain, Curso de Teologia da Umbanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fl&aacute;vio Penteado, Povo de Aruanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ademir Jr, Teologia de Umbanda e suas dimens&otilde;es;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lurdes Vieira, Manual Doutrin&aacute;rio, Ritualistico e Comportamental Umbandista</span></span></span></span></span></li>

					</p>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 13/04/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>