<?php $results['pageTitle'] = "Os Guardiões | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
                        
  			<img class="card-img-top" src="images/guardioes.jpg" alt="Card image cap">
				<h2 class="card-title"><center>OS GUARDIÕES</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Guardi&otilde;es (Exus e Pombagiras) t&ecirc;m como fun&ccedil;&atilde;o principal proteger. &Eacute; a primeira, a mais densa e a mais importante linha de defesa de uma pessoa. Al&eacute;m disso, Exu e Pombagira dividem o carma com seu protegido, e, por isso, quando o protegido est&aacute; feliz, Exu est&aacute; feliz, e o contr&aacute;rio tamb&eacute;m &eacute; verdade. Exu &eacute; o que faz cumprir a lei do merecimento, a lei do retorno, a lei da a&ccedil;&atilde;o e rea&ccedil;&atilde;o e tamb&eacute;m &eacute; o executor do carma. Trabalham nas Trevas para a Luz e guiados pela Lei Maior do PAI. N&atilde;o se trata de bem e nem de mal, trata-se apenas de cumprir a lei da espiritualidade superior. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Por todos esses motivos, EXU e POMBAGIRA N&Atilde;O FAZEM O MAL.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:16.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">EXU</span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A palavra exu significa esfera na na&ccedil;&atilde;o Iorub&aacute;, segundo algumas lendas oriundas dessa mesma na&ccedil;&atilde;o, Exu &eacute; o mensageiro de Olodumar&eacute; ou Olorum (Deus), para que os pedidos feitos para os Orix&aacute;s fossem atendidos deve-se fazer oferendas primeiro para Exu. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu est&aacute; presente em torno de n&oacute;s, na sociedade, ele se mostra em nosso campo emocional, psicol&oacute;gico de fora para dentro, de dentro para fora em muitos aspectos da nossa vida.</span></span></span></span></span></p>

<img src="images/caveira.jpeg" style="padding: 0 15px;float:right; width:180px;height: 200px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O trabalho de Exu na Umbanda mexe com as nossas emo&ccedil;&otilde;es, com o nosso inconsciente, mexe com os nossos sentimentos mais profundos, com nossos traumas, nossas fobias e nossos medos. As cicatrizes mais profundas, aquelas patologias que modificam o nosso comportamento, s&atilde;o &agrave;s vezes despertadas por Exu.Os guardi&otilde;es nos afetam ao pontode remexer no fundo de nosso ser. S&atilde;o sentimentos que n&atilde;o queremos por para fora, mas os guardi&otilde;es muitas vezes ofazem para nos curarmos mais rapidamente. Exu mexe com nossos v&iacute;cios, nossa sombra, no sentido bem psicol&oacute;gico, mexe com nossas trevas anteriores.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Rodrigo Queir&oacute;s diz &ldquo;A Umbanda n&atilde;o &eacute; uma religi&atilde;o ideal, mas &eacute; antes disso um ideal de religi&atilde;o.&rdquo; O que isso quer dizer? Que n&atilde;o existe uma religi&atilde;o ideal, mas que eu fa&ccedil;o da Umbanda o meu ideal e o ideal em qualquer religi&atilde;o &eacute; a busca por Deus. O ideal em religi&atilde;o &eacute; buscar a perfei&ccedil;&atilde;o, &eacute; conhecer algo chamado &ldquo;conhece-te a ti mesmo&rdquo; e Exu, por meio das nossas emo&ccedil;&otilde;es, do nosso inconsciente, enquanto nosso melhor amigo e por meio de tantas outras ferramentas que Exu tr&aacute;s para n&oacute;s na Umbanda, que seja a magia, como mensageiro dos Orix&aacute;s, que seja lidando com aspectos do bem e do mal, Ele nos ajuda a conhecer a n&oacute;s mesmos, pois o conhecimento de si pr&oacute;prio implica em conhecer nossos v&iacute;cios e virtudes, o que h&aacute; de luz e sombra dentro de cada um de n&oacute;s.</span></span></span></span></span></p>

<img src="images/guardiao.jpg" style="padding: 0 15px;float:left; width:250px;height: 200px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os EXUS s&atilde;o os mais humanos dos Mist&eacute;rios da Cria&ccedil;&atilde;o. Eles s&atilde;o esp&iacute;ritos em busca de evolu&ccedil;&atilde;o e compromissados com a espiritualidade superior. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na Umbanda a origem de Exu est&aacute; em fun&ccedil;&atilde;o da necessidade de existirem guardi&otilde;es, encaminhadores e combatentes das for&ccedil;as trevosas. Trabalho b&aacute;sico da Umbanda. Por isso se diz que &ldquo;sem Exu n&atilde;o se faz nada&rdquo;. Isso n&atilde;o &eacute; porque Exu n&atilde;o deixa, porque &eacute; vingador, tra&iacute;ra ou voluntarioso como querem fazer pensar algumas lendas sobre Exu, mas sim porque n&atilde;o h&aacute; como combater for&ccedil;as trevosas sem defesa e prote&ccedil;&atilde;o.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Nossos guias (caboclos e pretos-velhos) nos protegem e defendem, mas cabe a Exu o primeiro combate, o combate direto contra as energias que circulam no Astral Inferior.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas caracter&iacute;sticas dos exus</span></span></span></u></strong></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: Laroi&ecirc; Exu! (exu eu te sa&uacute;do), Exu &eacute; Mojub&aacute; (Ex&uacute; &eacute; mensageiro)</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cores:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> Preto, vermelho, vermelho e preto ou as cores escolhidas pela entidade.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebidas:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> Cacha&ccedil;a (Marafo), Whisky.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fumo: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cigarro branco, charutos.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Utens&iacute;lios: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chap&eacute;u, cartola, bengala, capa.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Linha e Irradia&ccedil;&atilde;o:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> A linha depende da entidade e a irradia&ccedil;&atilde;o Orix&aacute; Exu.</span></span></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pontos de For&ccedil;a</span></span></span></u></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pontos de For&ccedil;a s&atilde;o locais cujas energias s&atilde;o as mais &quot;puras&quot; e facilitam o contato com o outro &quot;lado&quot; da vida. Estes locais s&atilde;o conhecidos tamb&eacute;m comodom&iacute;nios.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os pontos de for&ccedil;a s&atilde;o:</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cemit&eacute;rio: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Exus que trabalham nesse ponto de for&ccedil;a fazem trabalhos, obriga&ccedil;&otilde;es, descarregados, mas n&atilde;o d&atilde;o consultas. Quando em consulta trabalham descarregando o consulente, sendo s&eacute;rios e discretos. Trabalham geralmente para Obalua&ecirc;.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Encruzilhada: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Exus que trabalham nesse ponto de for&ccedil;a fazemtrabalhos, obriga&ccedil;&otilde;es, descarregados e gostam de dar consultas. Menos s&eacute;rios que os exus de cemit&eacute;rios. Trabalham para diversos orix&aacute;s.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Estrada: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Exus que trabalham nesse ponto de for&ccedil;a d&atilde;o consultas, s&atilde;o brincalh&otilde;es e gostam de uma boa gargalhada e movimentam-se bastante</span></span></span><span style="font-size:14.0pt">e podem atender v&aacute;rias pessoas ao mesmo tempo.</span></span></span></p>

<img src="images/tranca.jpg" style="padding: 0 15px;float:right; width:200px;height: 250px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Exus podem ser classificados tamb&eacute;m por n&iacute;vel de consci&ecirc;ncia e evolu&ccedil;&atilde;o espiritual: </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exus Coroados</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: S&atilde;o aqueles que t&ecirc;m grande evolu&ccedil;&atilde;o, j&aacute; est&atilde;o nas fun&ccedil;&otilde;es de mando. S&atilde;o os chefes das falanges. Recebem as ordens diretas de entidades dos planos superiores da Umbanda. Poucos s&atilde;o aqueles que se manifestam em algum m&eacute;dium. Apenas alguns m&eacute;diuns, bem preparados, com enorme miss&atilde;o aqui na Terra, tem um Exu Coroado como o seu guardi&atilde;o pessoal. S&atilde;o os guardi&otilde;es chefes de terreiro. N&atilde;o mais reencarnam, j&aacute; esgotaram h&aacute; tempos os seus Carmas. Antigamente eram conhecidos como Exu de Lei. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exus Batizados</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: Tamb&eacute;m conhecidos como Exus Cruzados. S&atilde;o subordinados dos Exus Coroados. J&aacute; tem a no&ccedil;&atilde;o do bem e do mal. S&atilde;o os exus mais comuns que se manifestam nos terreiros. Tamb&eacute;m, tem fun&ccedil;&otilde;es de subchefes. Fazem parte da seguran&ccedil;a de um terreiro. O campo de atua&ccedil;&atilde;o destes exus est&aacute; nas sombras (entre a Luz e as Trevas). Est&atilde;o ainda nos ciclos de reencarna&ccedil;&otilde;es. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exus Espadados</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: S&atilde;o subordinados dos Exus Cruzados. O seu campo de atua&ccedil;&atilde;o encontra-se entre as sombras e as trevas. Acabaram de despertar sua consci&ecirc;ncia para os conceitos de bem e mal, e possuem discreto n&iacute;vel de evolu&ccedil;&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exus Pag&atilde;os</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: Na realidade ainda n&atilde;o s&atilde;o Exus. S&atilde;o kiumbas capturados ou que em algum momento manifestaram o desejo de tentar outro caminho. Ainda n&atilde;o tem consci&ecirc;ncia clara entre o bem e o mal, e aceitam fazer qualquer trabalho desde que devidamente pagos. S&atilde;o conduzidos com m&atilde;o-de-ferro pelos Exus Espadados, que os castigam quando necess&aacute;rio. O termo Exu Pag&atilde;o foi criado para distingui-los dos outros esp&iacute;ritos que praticam o mal deliberadamente. Est&atilde;o em aprendizado. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu, para um esp&iacute;rito em evolu&ccedil;&atilde;o, &eacute; um t&iacute;tulo que dever&aacute; ser conquistado atrav&eacute;s do tempo, do trabalho e do merecimento de cada entidade. Uma pessoa por se vestir como um policial, n&atilde;o se torna um; nem quem veste um guardap&oacute; se torna m&eacute;dico. Um esp&iacute;rito, apenas por se dizer Exu, n&atilde;o significa que o seja. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu pode usar terno, capa, cartola, bengala. Pode usar uniforme ou a vestimenta dos cavaleiros, ou guerreiros do passado, mas tenha certeza de que nada lembrar&aacute; um dem&ocirc;nio. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu &eacute; limpo, correto e certeiro. Exu n&atilde;o bebe demais e, caso o fa&ccedil;a, tenha certeza de que tem um motivo, e de que ele levar&aacute; embora todo o &aacute;lcool de seu aparelho. Quando o m&eacute;dium fica b&ecirc;bado, tenha certeza de que Exu nada tem a ver com o fato. Isso &eacute; coisa de m&eacute;dium desorientado ou sem preparo.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:16.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">POMBAGIRA</span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Pombagiras s&atilde;o entidades espirituais femininas (&ldquo;Mulheres&rdquo;) que se manifestam em seus m&eacute;diuns. As Pombagiras, em outras vidas, foram mulheres &agrave; frente do seu tempo. Elas foram m&atilde;es, filhas, amigas, esposas, amantes, lindas (consciente de suas belezas), inteligentes (confiantes de suas capacidades), vaidosas, estudiosas, talentosas, donas de si e de uma autoconfian&ccedil;a que as faziam brilhar.</span></span></span></span></span></p>

<img src="images/molambo.jpg" style="padding: 0 15px; float:right; width:250px;height: 200px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Pombagiras trazem para os seus m&eacute;diuns essas mesmas qualidades. Elas passam aos seus protegidos aquilo que lhes faltam. Se o m&eacute;dium tem baixa autoestima, ela trata de elev&aacute;-la. Se o m&eacute;dium se acha pouco inteligente, a Pombagira cuida para que o desejo de saber, estudar e aprender cres&ccedil;a. Ela faz com que seu protegido perceba que &eacute; capaz de realizar aquilo em que se sente fraco.&nbsp; Se o m&eacute;dium est&aacute; desanimado, com pouca vontade de continuar a viver e crescer financeiramente, a Pombagira aumenta a sua for&ccedil;a e perseveran&ccedil;a, fazendo crescer o desejo de continuar e de alcan&ccedil;ar seus objetivos e de vencer os obst&aacute;culos.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Esse desejo, essa for&ccedil;a de vontade, que &eacute; considerado o fator de trabalho das Pombagiras, &eacute; o desejo de conceber, ansiar, aspirar, ambicionar, ter vontade de comer ou beber, desejar o outro (como companheiro), entre outros, mas tudo com equil&iacute;brio e de maneira positiva. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Pombagiras s&atilde;o alegres, simp&aacute;ticas, verdadeiras, diretas, honestas, sensuais e conhecem muito bem a alma humana e suas inten&ccedil;&otilde;es. Trabalham descarregando pessoas e ambientes de energias viciadas, caracterizadas pelos excessos humanos, como v&iacute;cios do fumo, do &aacute;lcool, da pregui&ccedil;a, do sexo e outros. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Pombagiras querem que seus protegidos (m&eacute;diuns) conhe&ccedil;am as pr&oacute;prias qualidades, que identifiquem os seus defeitos e fraquezas e descubram tudo o que est&aacute; guardado dentro de si que n&atilde;o lhes fazem bem. S&oacute; assim, o m&eacute;dium poder&aacute; amplificar e aproveitar suas qualidades, corrigir os seus defeitos e criar defesas para as suas fraquezas.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Pombagiras t&ecirc;m particularidades relacionadas &agrave;s caracter&iacute;sticas que faltam nos m&eacute;diuns pelos quais se manifestam. Por exemplo, em entrevista conduzida pela Dra. Mariana Leal a uma Pombagira, sobre a ajuda que presta &agrave; sua m&eacute;dium, a Pombagira respondeu: &ldquo;A gente age na falta. A gente vem na necessidade da pessoa.&rdquo;</span></span></span></span></span></p>

<img src="images/padilha.jpg" style="padding: 0 15px;float:left; width:250px;height: 200px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ou seja, as Pombagiras que se manifestam nos m&eacute;diuns n&atilde;o s&atilde;o quaisquer umas, mas sim aquelas que podem ajudar os m&eacute;diuns naquilo que eles necessitem. Dona Maria Molambo, por exemplo, na entrevista conduzida pela Dra. Mariana, deixou claro que era muito parecida com sua protegida. A sua protegida tinha dores e guardava tudo dentro de si. Por&eacute;m, com a ajuda da Dona Maria Molambo, aprendeu que precisava colocar pra fora, que precisava falar de seus problemas, pois, caso assim n&atilde;o o fizesse, &ldquo;a sujeira cresceria internamente&rdquo; e ela adoeceria, podendo vir a sofrer de c&acirc;ncer e infec&ccedil;&otilde;es.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Existem v&aacute;rias falanges de Pombagiras, cada uma delas ligadas a um Orix&aacute;. Existem as Marias Molambos, Pombagiras Ciganas, Sete Saias, Marias Padilhas, Rosas Caveira, entre outras. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Pombagiras s&atilde;o muito procuradas para resolver problemas de amor, mas tamb&eacute;m surgem mulheres com dificuldades para engravidar, com baixa autoestima, abusadas sexualmente, moralmente e fisicamente. A afinidade e o fato da Entidade atendende e, na maioria dos casos, o m&eacute;dium serem tamb&eacute;m mulheres, facilita a comunica&ccedil;&atilde;o e a compreens&atilde;o dos problemas e das a&ccedil;&otilde;es a serem tomadas. Mas homens tamb&eacute;m s&atilde;o atendidos, obviamente. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A fun&ccedil;&atilde;o de uma Pombagira, trabalhadora da luz nas trevas, &eacute;, acima de tudo, nunca fazer o mal e sempre proteger o seu m&eacute;dium. &Eacute; assim que uma Pombagira diz: &ldquo;N&atilde;o tenha medo, levante a cabe&ccedil;a, encare o problema e siga em frente!&rdquo;</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas caracter&iacute;sticas das pombagiras</span></span></span></u></strong></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: Salve as Sinh&aacute;s!</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cores:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> Preto, vermelho, vermelho e preto ou as cores escolhidas pela entidade.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebidas:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> Cacha&ccedil;a (Marafo), Espumantes (Champanhe), Licores.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fumo: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cigarro branco, cigarrilhas.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Utens&iacute;lios: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Len&ccedil;os, leques, piteiras.</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Linha e Irradia&ccedil;&atilde;o:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> A linha depende da entidade e a irradia&ccedil;&atilde;o do Orix&aacute;.</span></span></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><u><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pontos de For&ccedil;a</span></span></span></u></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Pontos de For&ccedil;a s&atilde;o locais cujas energias s&atilde;o as mais &quot;puras&quot; e facilitam o contato com o outro &quot;lado&quot; da vida. Estes locais s&atilde;o conhecidos tamb&eacute;m como dom&iacute;nios. Esses dom&iacute;nios s&atilde;o muitos parecidos com os de Exu, existindo apenas pequenas diferen&ccedil;as.</span></span></span></span></span></p>

<img src="images/rosacaveira.jpg" style="padding: 0 15px;float:right; width:200px;height: 250px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os pontos de for&ccedil;a s&atilde;o:</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Calunga Grande:</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> A Calunga grande &eacute; o mar. As Pombagiras que atuam nesse ponto de for&ccedil;a fazem trabalhos, obriga&ccedil;&otilde;es e descarregos. Quando em consulta, trabalham descarregando o consulente, sendo tranquilas, sensuais e discretas. Trabalham geralmente para Iemanj&aacute; e na sua irradia&ccedil;&atilde;o.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Calunga Pequena : </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Calunga pequena &eacute; o cemit&eacute;rio. As Pombagiras que atuam nesse ponto de for&ccedil;a fazem trabalhos, obriga&ccedil;&otilde;es e descarregos. Quando em consulta, descarregam o consulente, s&atilde;o s&eacute;rias e discretas. Trabalham geralmente para e na irradia&ccedil;&atilde;o de Obalua&ecirc;.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Encruzilhada em T ou Y: </span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Pombagiras que atuam nesses pontos de for&ccedil;a fazem trabalhos, obriga&ccedil;&otilde;es, descarregos e gostam de dar consultas. Elas s&atilde;o mais descontra&iacute;das e gostam de conversar. Trabalham para diversos Orix&aacute;s.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Caminhos (Estradas, Estradas de ferro e Estradas de terra):</span></span></span></strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> As Pombagiras que atuam nesse ponto de for&ccedil;a d&atilde;o consultas, s&atilde;o expansivas, gostam muito de beber e fumar e de gargalhar. Movimentam-se bastante e podem atender v&aacute;rias pessoas ao mesmo tempo.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Pombagiras s&atilde;o todas mulheres, mas cada uma &eacute; uma individualidade. Todas falam sobre feminino, todas falam sobre mulheres, mas cada uma fala &agrave; sua maneira. Cada uma tem a sua vis&atilde;o.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Pombagiras s&atilde;o exuberantes, mas n&atilde;o vulgares. Bebida, fumo e dan&ccedil;a em excesso n&atilde;o s&atilde;o coisas de Pombagira, mas sim de m&eacute;diuns vaidosos. Elas podem pedir adere&ccedil;os, como leques, saias e len&ccedil;os, mas sempre explicar&atilde;o porque precisam deles. Conhecem bem o esp&iacute;rito humano e a carnalidade e &eacute; exatamente por isso que s&atilde;o t&atilde;o eficazes nas curas que promovem.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Todas v&atilde;o tentar resgatar do consulente, independente de ser homem ou mulher, sua autoestima e confian&ccedil;a.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Pombagiras s&atilde;o mulheres de respeito e que merecem toda a nossa admira&ccedil;&atilde;o e carinho. Elas est&atilde;o aqui para ajudar sempre!</span></span></span></span></span></p>

<div class="text-center"><img src="images/rosas.jpg" style="padding: 0 15px; width:500px;height: 250px;" ></img></div>

					</p>
            </div>
            <div class="card-footer text-muted">
				17/02/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>