<?php $results['pageTitle'] = "A Liturgia da Umbanda| Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
				<h2 class="card-title"><center>A LITURGIA DA UMBANDA</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Encruzamento </span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Primeiro, as pessoas oferecem a m&atilde;o direita, palma e costas, depois a m&atilde;o esquerda, palma e costas, para cruzar. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Por que? Ritual umbandista no in&iacute;cio de um per&iacute;odo ou sess&atilde;o, consistindo em fazer uma cruz com a pemba (giz branco) na palma da m&atilde;o, isso fecha o corpo e protege. Identifica todos os filhos participantes sob a prote&ccedil;&atilde;o do Guia Espiritual da Casa. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fortifica sua mediunidade e ajuda tamb&eacute;m a estabelecer uma liga&ccedil;&atilde;o mais firme com os Guias Espirituais. No encruzamento s&atilde;o entoados cantos, pr&oacute;prios para a ocasi&atilde;o.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A pemba &eacute; a ferramenta utilizada para encruzar, riscar os pontos etc. Confeccionada com calc&aacute;rio e modelada em formato ov&oacute;ide-alongado.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Defuma&ccedil;&atilde;o</span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na UMBANDA como em outras religi&otilde;es, defuma-se com ervas e incensos, para equilibrar e harmonizar o ambiente. A Defuma&ccedil;&atilde;o &eacute; concebida como opera&ccedil;&atilde;o de magia, que possui um poder natural, superior as for&ccedil;as ordin&aacute;rias da natureza. Por ser de origem antigu&iacute;ssima o processo de defuma&ccedil;&atilde;o, trouxe, at&eacute; a &eacute;poca atual, a cren&ccedil;a nos poderes ben&eacute;ficos dos perfumes queimados como o incenso e, por esta raz&atilde;o, em todos os rituais religiosos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas ervas s&atilde;o b&aacute;sicas nos processos de defuma&ccedil;&atilde;o: Benjoim, Mirra, Alecrim, representando a divindade do Messias, por ocasi&atilde;o do seu nascimento. Esses perfumes divinos t&ecirc;m um alto sentido cabal&iacute;stico e o seu uso acoberta dos malef&iacute;cios aqueles que os utilizam. As ervas usadas na defuma&ccedil;&atilde;o est&atilde;o ritualisticamente ligadas aos nossos ORIX&Aacute;S. A riqueza da flora brasileira fornece ervas para os banhos de descarrego, que veremos mais adiante, como parte desta mat&eacute;ria. Antes do in&iacute;cio dos trabalhos, defuma-se o terreiro e as pessoas presentes, m&eacute;diuns e assistidos, para livr&aacute;-los das m&aacute;s influ&ecirc;ncias e para que os m&eacute;diuns tenham &ecirc;xito nas manifesta&ccedil;&otilde;es das Entidades Espirituais. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Para que a defuma&ccedil;&atilde;o seja eficaz &eacute; primordial que seja feita por uma pessoa treinada. Os resultados positivos variam de acordo com a capacidade de cada um em despertar suas for&ccedil;as mentais para &ldquo;varrer&rdquo; as energias negativas, de um ambiente. N&atilde;o se deve usar a defuma&ccedil;&atilde;o para espantar esp&iacute;ritos maus. Algumas ervas se prestam para esse fim, mas os esp&iacute;ritos mal&eacute;ficos, afastados temporariamente do local, aguardam uma ocasi&atilde;o para desforra e ao menor descuido do irm&atilde;o de f&eacute; vingam-se impondo conseq&uuml;&ecirc;ncias desagrad&aacute;veis ao imprudente. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A defuma&ccedil;&atilde;o pode ser usada para limpar o corpo e a casa contra irradia&ccedil;&otilde;es e emana&ccedil;&otilde;es desfavor&aacute;veis, provindas de c&eacute;rebros doentios ou locais l&uacute;gubres e contaminados pelas baixas vibra&ccedil;&otilde;es magn&eacute;ticas.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bater Cabe&ccedil;a</span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O m&eacute;dium deita no ch&atilde;o, de barriga para baixo, e toca o solo com a testa, em frente ao Cong&aacute;. Com as m&atilde;os espalmadas para cima, colocadas no mesmo n&iacute;vel da cabe&ccedil;a, recebe as vibra&ccedil;&otilde;es positivas de Deus (Olorum) e dos Orix&aacute;s cultuados na Umbanda. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Nesse momento, faz uma prece mentalmente, e pede aos mentores e aos Orix&aacute;s seu valioso aux&iacute;lio e suas luzes, para melhor desempenho de suas fun&ccedil;&otilde;es medi&uacute;nicas. Bate-se a cabe&ccedil;a no ch&atilde;o em sinal de respeito e obedi&ecirc;ncia aos Orix&aacute;s, simbolizando que a nossa cabe&ccedil;a, que nos comanda e nos rege, est&aacute; se subordinando ao poder dos Orix&aacute;s, que estamos reverenciando, sejam os Orix&aacute;s do Zelador ou do Cong&aacute;. O bater cabe&ccedil;a no Cong&aacute; &eacute; uma rever&ecirc;ncia a Oxal&aacute;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em diversas culturas, ocidentais ou orientais, baixar a cabe&ccedil;a perante algu&eacute;m ou alguma coisa significa estar submisso e obediente a esta pessoa ou coisa. Ap&oacute;s bater a cabe&ccedil;a, o m&eacute;dium cumprimenta a tabaca. Ali se encontram as entidades que auxiliam o tabaqueiro chefe, Ogan, durante toda a gira. Em seguida, cumprimentamos os guias da escora ou tronqueira, guardi&otilde;es da ordem e da lei, dentro do terreiro.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Gira de Umbanda </span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; a reuni&atilde;o de diversos m&eacute;diuns, devidamente preparados, para prestar a caridade. Consultas, conselhos, passes magn&eacute;ticos e de descarrego, doutrina&ccedil;&otilde;es, desobsess&atilde;o, intercomunica&ccedil;&atilde;o entre encarnados e desencarnados, encaminhamento de esp&iacute;ritos perdidos no desespero ou no sofrimento, puxadas (o m&eacute;dium d&aacute; passagem para receber esp&iacute;ritos dos mais variados n&iacute;veis), desarme de demandas etc.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Puxada</span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A puxada nada mais &eacute; do que a capacidade que o guia tem de transferir parte da energia do assistido para o m&eacute;dium (puxador) auxiliar, iludindo assim, o obsessor, para que este se desligue do encarnado e se ligue momentaneamente ao m&eacute;dium, que neste momento, consegue cont&ecirc;-lo para que assim receba orienta&ccedil;&atilde;o e tratamento. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O mesmo ocorre com as roupas, fotos, fichas etc, pois estas pe&ccedil;as est&atilde;o imantadas com a energia do encarnado obsediado. Este tipo de tratamento tem o nome de psicometria, ou seja, desobsess&atilde;o &agrave; dist&acirc;ncia, utilizando algo que foi imantado pelo obssediado. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Quando o guia pede para escolher um m&eacute;dium puxador, n&atilde;o utilizando seus cambonos para tanto, n&atilde;o h&aacute; porque haver nenhum tipo de melindre entre os m&eacute;diuns n&atilde;o utilizados. Faz-se importante saber que o guia em quest&atilde;o est&aacute; buscando um m&eacute;dium f&iacute;sica e vibratoriamente compat&iacute;vel com aquela energia negativa manifestante. Exemplo: O obsessor a ser doutrinado desencarnou num processo alco&oacute;lico comprometendo seu f&iacute;gado, p&acirc;ncreas etc. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O m&eacute;dium puxador dispon&iacute;vel sofre de gastrite, &uacute;lcera ou alguma outra patologia relacionada. Este m&eacute;dium n&atilde;o pode fazer esta puxada para n&atilde;o comprometer fisicamente seu estado de sa&uacute;de. O mesmo acontece quanto &agrave; energia ou vibra&ccedil;&atilde;o. &Eacute; preciso que haja uma similaridade vibracional e ou energ&eacute;tica. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Quando o m&eacute;dium puxador retorna da incorpora&ccedil;&atilde;o do obsessor, por vezes, guarda, consigo, lembran&ccedil;as e resqu&iacute;cios da energia do esp&iacute;rito, nestes casos, se faz necess&aacute;rio que o m&eacute;dium se ligue a seus guias, aos guias da Tenda, e com o pensamento elevado, permita que estes resqu&iacute;cios de energia circulem pelo seu corpo et&eacute;reo e retorne ao solo, neutralizando assim a sua influ&ecirc;ncia. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O m&eacute;dium n&atilde;o deve reter as energias do obsessor, pois isso pode gerar desequil&iacute;brio espiritual e material.</span></span></span></span></span></p>

					</p>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 26/11/2018
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>