<?php $results['pageTitle'] = "Seu Zé Pelintra | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
			<img src="images/seuze.jpg" class="card-img-top"></img>
				<h2 class="card-title"><center>SARAVÁ SEU ZÉ PELINTRA! SALVE A MALANDRAGEM!</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&quot;Um mist&eacute;rio, uma falange de Umbanda, que &eacute; fundamentada por mist&eacute;rios divinos...&quot; (Z&eacute; Pelintra)</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em nossa querida Umbanda a figura dessa entidade traz muita alegria e sabedoria. Muitos m&eacute;diuns servem de instrumento para ele que tamb&eacute;m &eacute; conhecido como Catimbozeiro, Malandro ou Mestre da Jurema. Ele possui a liberdade de atuar na linha que desejar, at&eacute; aqui todos sabemos, mas h&aacute; muito para se aprender sobre e com o Z&eacute; Pelintra. Muitos m&eacute;diuns que trabalham com ele n&atilde;o conhecem muito sobre essa falange.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Z&eacute; Pelintra: Malandro ou Marginal?</span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Vamos ao dicion&aacute;rio buscar o significado da palavra &quot;Pelintra&quot;:</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pelintra: Substantivo: pessoa pobre e mal trajada, com pretens&atilde;o a exibir-se, desejo de ostenta&ccedil;&atilde;o; adjunto: mal trajado e pretensioso. (Dicion&aacute;rio portugu&ecirc;s brasileiro online).</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Essa defini&ccedil;&atilde;o literal &eacute; algo que ajuda a confundir a mente daqueles que buscam a compreens&atilde;o sobre a falange de Z&eacute; Pelintra. Uma falange de Umbanda &eacute; sustentada e fundamentada por mist&eacute;rios divinos, logo, deve-se interpret&aacute;-la de igual forma. A ideia passada de &quot;pessoa pobre e mal trajada&quot; exp&otilde;e um preconceito com a classe menos favorecida.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O mestre de Jurema, seu Z&eacute; Pelintra, sempre teve sua vestimenta simples e, com sua alegria e versatilidade nos trabalhos, conferiu para si a condi&ccedil;&atilde;o de transitar em todos os n&iacute;veis vibrat&oacute;rios para ajudar a quem o procura. &Eacute; por isso que a alcunha de Malandro lhe foi dada, pois na Jurema &eacute; amigo de todos e jamais haver&aacute; portas fechadas para ele, seja na direita ou na esquerda. Ent&atilde;o, quando nas macumbas cariocas, firmou-se definitivamente na Umbanda. Assim, revestiu-se da imagem do antigo malandro, chique, garboso, ostentador, por&eacute;m simples e muito trabalhador.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Este querido Guia &eacute; simples e complexo, o que dificulta o entendimento de sua falange. Ele elimina qualquer preconceito. Ele se apresenta como uma figura de meia idade, um senhor, mulato ou negro, de terno branco, gravata vermelha e chap&eacute;u branco com fita vermelha. Seu sapato &eacute; bicolor, vermelho e branco, e sua camisa tamb&eacute;m &eacute; branca. Est&aacute; longe de ser um marginal, mas representa todos aqueles que se sentem marginalizados por preconceitos, sejam eles de qualquer origem. Seu pr&oacute;prio nome &eacute; repleto de simbolismo acerca de seu trabalho, o de recuperar a autoestima e ajudar os que mais necessitam e, acima de tudo, resgatar esp&iacute;ritos encarnados ou n&atilde;o da marginalidade.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Z&eacute; Pelintra veio para nossa religi&atilde;o, que por sua natureza &eacute; uma religi&atilde;o pluralista e destruidora de tabus e preconceitos, para mostrar que bom &eacute; aquele que confia em si, levanta a cabe&ccedil;a e caminha. Talvez seja por isso que o Sr. Z&eacute; &eacute; Pelintra: ele &eacute; bo&ecirc;mio e dan&ccedil;arino, alegre e sorridente, curte a vida e porta a luz, independente do moralismo e preconceito da sociedade. Deus &eacute; alegria, satisfa&ccedil;&atilde;o e vida. &Eacute; isso que seu Z&eacute; Pelintra nos ensina com o seu jeito todo pr&oacute;prio.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Falange de Seu Z&eacute; Pelintra</span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Como vimos, o Guia Z&eacute; Pelintra trabalha em qualquer linha, seja na esquerda ou direita. Ent&atilde;o por que o associaram com um Ex&uacute;? &Eacute; prov&aacute;vel que isso tenha ocorrido junto &agrave;s sess&otilde;es de terreiros do Rio de Janeiro, ao observarem os trejeitos de seu Z&eacute;, associaram-no &agrave; linha de Esquerda. Mais tarde, na Umbanda, foi notada a atua&ccedil;&atilde;o dele nas linhas da Direita, de modo que acabou sendo encaminhado para trabalhar junto com os Baianos. Mas, ainda assim, seu Z&eacute; Pelintra n&atilde;o &quot;pertence&quot; nem a uma linha e nem a outra. Ele atua em todas as linhas da mesma forma.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Nesta falange, que se desdobra hierarquicamente em milhares e milhares de esp&iacute;ritos, &eacute; muito natural que v&aacute;rios esp&iacute;ritos que tem como natureza e miss&atilde;o trabalhar na linha da Esquerda adquiram afinidade com a vibra&ccedil;&atilde;o de seu Z&eacute; Pelintra. Assim, atuam como Z&eacute; Pelintra e podem por vezes serem chamados de &quot;Exu Z&eacute; Pelintra&quot;. Isso explica o porqu&ecirc; de muitos &quot;Z&eacute;s&quot; trabalharem na Esquerda com o grau de Exu. &Eacute; preciso deixar claro e definitivo para todos que, mesmo quando Seu Z&eacute; se manifesta como Exu, isso n&atilde;o &eacute; atributo diminuto de forma nenhuma.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Para entender um pouco dessa hierarquia, vamos analisar a falange Z&eacute; Pelintra. Ela &eacute; comandada pelo Conselho dos Sete, como s&atilde;o chamados os Z&eacute;s Pelintra que comandam a linha de Z&eacute; Pelintra na Umbanda. Este conselho tem o comando do Z&eacute; Maior, assim denominado pelos outros integrantes. A Flange se desdobra em um n&uacute;mero infinito, sempre em 7x7.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cada integrante do conselho &eacute; respons&aacute;vel por uma vibra&ccedil;&atilde;o espec&iacute;fica de trabalho e, por isso, h&aacute; uma diversidade de trabalhadores em todas as linhas da Umbanda sob o arqu&eacute;tipo de Z&eacute; Pelintra. Por esse motivo existe o Baiano Z&eacute; Pelintra, Exu Z&eacute; Pelintra e para surpresa de muitos, o Boiadeiro Z&eacute; Pelintra, Preto Velho Z&eacute; Pelintra e por a&iacute; vai. Este conselho tamb&eacute;m sustenta e comanda a linha dos malandros na Umbanda, uma linha numerosa e trabalhadora que se dedica &agrave; a&ccedil;&atilde;o de abertura dos caminhos, de prote&ccedil;&atilde;o e de purifica&ccedil;&atilde;o dos irm&atilde;os que procuram a sua ajuda.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Alguns exemplos da vasta pluralidade da falange de Seu Z&eacute; s&atilde;o: Z&eacute; Pelintra das Almas, Z&eacute; Pelintra do Morro, Z&eacute; Pelintra da Encruzilhada. Tamb&eacute;m existem e merecem ser citadas as Malandras, que s&atilde;o esp&iacute;ritos &ldquo;femininos&rdquo; que possuem afinidade com este mist&eacute;rio de Z&eacute; Pelintra, dentre elas Maria Navalha, Maria da Lira, Risca Giz, Dona Garoa, Maria da Lua, Maria do Morro e Dona N&ecirc;ga. Destaca-se que elas n&atilde;o fazem parte da Linha das Pombagiras.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Assim como todos os outros guias na Umbanda, Seu Z&eacute; Pelintra utiliza suas pr&oacute;prias vestimentas, que o identificam, e faz uso de v&aacute;rios objetos para manipula&ccedil;&atilde;o flu&iacute;dica, tais como bengalas, navalhas, punhais, ter&ccedil;os e at&eacute; mesmo marac&aacute;s. Cada objeto est&aacute; relacionado a uma linha de atua&ccedil;&atilde;o da falange de Z&eacute; Pelintra. Em uma vis&atilde;o puramente umbandista, Z&eacute; Pelintra seria regido por Oxal&aacute;, Ogum, Iemanj&aacute; e Ians&atilde;. Entretanto, pode ocorrer Z&eacute; Pelintra atuando em irradia&ccedil;&otilde;es diferentes dessas, mas sempre responder&atilde;o aos Orix&aacute;s mencionados como mist&eacute;rio maior. Isso &eacute; importante para a compreens&atilde;o da atua&ccedil;&atilde;o dessa falange.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Oxal&aacute;, como o senhor da F&eacute;, da Plenitude, da Luz, da Pureza, do Branco, nos remete &agrave; do&ccedil;ura de seu Z&eacute; e do poder de suas palavras. H&aacute; em Seu Z&eacute; os mist&eacute;rios divinos de Oxal&aacute;, pelos quais ele encaminha seus filhos em dire&ccedil;&atilde;o da F&eacute;. Olhando agora para as cores da vestimenta de Seu Z&eacute;, lembra-nos de Ogum. Sendo Pai Ogum o respons&aacute;vel pela abertura de caminhos e pela quebra de demandas, fica explicado o motivo de Seu Z&eacute; ser ex&iacute;mio protetor, &aacute;gil em quebrar demandas e anular magias negativas. Logo, como filho de Ogum, seu Z&eacute; &eacute; um seguidor fiel da Lei Maior e da Justi&ccedil;a Divina. Assim, aqueles que usam a figura de seu Z&eacute; Pelintra para dar vaz&atilde;o &agrave;s suas negatividades responder&atilde;o imediatamente a Ogum, o Senhor da Lei, pois seu Z&eacute; Pelintra &eacute; guia de Lei e tamb&eacute;m n&atilde;o admite desvios de conduta e de car&aacute;ter em seus filhos.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ao contato com seu Z&eacute; Pelintra, somos vivificados. Ele nos auxilia a externar as virtudes de Deus, fazendo-nos sentir a vida maravilhosa e que somos parte do todo de Deus. Esta caracter&iacute;stica de seu Z&eacute; vem de nossa m&atilde;e Iemanj&aacute;, a rainha da vida e geradora de tudo. Por fim, sob a reg&ecirc;ncia de Ians&atilde;, a m&atilde;e da Lei e das Dire&ccedil;&otilde;es, Seu Z&eacute; oferece seus conselhos doutrinadores e direcionadores, despertando os filhos diante de suas falhas e impelindo-os a se movimentarem de modo nunca imaginado.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Seu Z&eacute; Pelintra atua em nossa F&eacute; nos vivificando, nos direcionando e ordenando nossas vidas para passarmos a caminhar nas Leis e em dire&ccedil;&atilde;o a Olorum! </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Objetos de uso de Z&eacute; Pelintra</span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><u><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A bengala</span></span></u><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: denota idade, sabedoria e amparo. Eles transitam em todas a linhas, assumem trabalhos ou comandam terreiros quando seu filho tem voca&ccedil;&atilde;o sacerdotal. Do contr&aacute;rio, assumem v&aacute;rias responsabilidade na corrente de trabalho, devido ao seu mist&eacute;rio de flexibilidade de seu Ax&eacute;.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><u><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A navalha</span></span></u><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: denota um corte r&aacute;pido e preciso de magias negativas. Contudo, o Z&eacute; Pelintra que trabalha com navalha, al&eacute;m dos cortes de magias negativas, &eacute; especialista em cortes e desmanches de magias de amarra&ccedil;&atilde;o. O campo do amor &eacute; sua especialidade.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><u><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O punhal</span></span></u><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: tamb&eacute;m segue a linha da navalha, por&eacute;m, com uma vibra&ccedil;&atilde;o voltada para a Lei. O Z&eacute; que usa punhal ou punhais &eacute; um perito magista, pois tem firmeza de trabalho, prote&ccedil;&atilde;o, etc.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><u><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O ter&ccedil;o</span></span></u><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: este adere&ccedil;o tamb&eacute;m faz parte da magia do Seu Z&eacute; Pelintra, pois ele &eacute; um ex&iacute;mio rezador e curador, heran&ccedil;a direta da Jurema do Nordeste.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><u><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O marac&aacute;</span></span></u><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">: como um mestre juremeiro, seu Z&eacute; usa o marac&aacute; para fazer parte de suas rezas e encantamentos.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tamb&eacute;m fazem parte da magia de seu Z&eacute; Pelintra todos os s&iacute;mbolos de jogos de azar, tais como dados, cartas, domin&oacute; e outros. &Eacute; preciso esclarecer que v&aacute;rios desses objetos, tais como os dados e os domin&oacute;s, j&aacute; eram usados milenarmente pelos or&aacute;culos, muito antes de se tornarem instrumentos de jogos de azar. Esses objetos fazem parte da magia de seu Z&eacute; Pelintra.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O campo de atua&ccedil;&atilde;o de Seu Z&eacute; Pelintra &eacute; muito grande. Para que ele possa exercer todo o seu Ax&eacute;, seus filhos devem confiar plenamente em seu mist&eacute;rio e atua&ccedil;&atilde;o, abrindo completamente seus mentais para que possam receber todo o conhecimento m&aacute;gico.</span></span></span></span></p>

					</p>
            </div>
            <div class="card-footer text-muted">
				28/01/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>