<?php $results['pageTitle'] = "Os Ciganos | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
					<h2 class="card-title"><center>OS CIGANOS</center></h2>
					<img src="images/ciganos.jpg" class="card-img-top"></img>	
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Ciganos s&atilde;o entidades que buscam seu espa&ccedil;o pela for&ccedil;a que demonstram em termos de caridade e servi&ccedil;os a humanidade. Os ciganos trabalham no campo do bem-estar pessoal e social, sa&uacute;de, equil&iacute;brio f&iacute;sico, mental e espiritual. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o entidades que h&aacute; pouco tempo ganharam maior presen&ccedil;a nos rituais da Umbanda. No come&ccedil;o, eram erroneamente confundidos com entidades espirituais das linhas dos Exus e das Pombagiras. Essa confus&atilde;o se explicava em fun&ccedil;&atilde;o dos nomes pelos quais se apresentavam, por vezes similares aos nomes utilizados por Guias de Esquerda, tais como Cigana das Almas e Cigana do Cruzeiro. Hoje, com o culto dos Ciganos mais difundido, se sabe e se conhece mais sobre essas entidades. Algumas casas chegam a ter dias espec&iacute;ficos para as Giras de Ciganos.</span></span></span></span></span></p>

<img src="images/cigana.jpg" style="padding: 0 15px;float:right; width:200px;height: 180px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As entidades s&atilde;o oriundas de um povo livre, respeitador de tudo que vem da natureza, rico em hist&oacute;rias e lendas. Os trabalhos desse povo tem origem na natureza, muito ligados &agrave; sa&uacute;de. Utilizam ervas para feitura de ch&aacute;s e banhos para a cura do esp&iacute;rito e do corpo. Trabalham tamb&eacute;m com cristais e magias.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Como j&aacute; foi dito, n&atilde;o t&ecirc;m na Umbanda o seu alicerce espiritual. Apresentam-se tamb&eacute;m em rituais do tipo mesa branca e Kardecistas. Por terem herdado de seu povo o amor incondicional &agrave; prote&ccedil;&atilde;o da natureza, tamb&eacute;m se manifestam em outros rituais espec&iacute;ficos de culto &agrave; natureza e todos os seus elementos. Mesmo assim, encontraram na Umbanda um lugar para suas pr&aacute;ticas, de modo a atender suas necessidades de trabalhar e prestar caridade.</span></span></span></span></span></p>

<img src="images/romani.png" style="padding: 0 15px;float:left; width:300px;height: 180px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Assim, o povo cigano passou a se identificar com os toques dos atabaques, com os pontos cantados em sua homenagem e com algumas das oferendas que s&atilde;o entregues &agrave;s outras entidades cultuadas pela Umbanda. Se adaptaram rapidamente &agrave; Umbanda, pela identifica&ccedil;&atilde;o com o exot&eacute;rico e com o oculto.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na Umbanda, os fundamentos dos Ciganos s&atilde;o simples, n&atilde;o possuindo assentamentos ou ferramentas para centraliza&ccedil;&atilde;o da for&ccedil;a espiritual. S&atilde;o cultuados em geral com imagens bem simples, com ta&ccedil;as com vinho ou com &aacute;gua, doces finos e frutas. Trabalham tamb&eacute;m com as energias do Oriente, com cristais, incensos, pedras energ&eacute;ticas, com as cores e com os quatro sagrados elementos da natureza.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os ciganos podem trabalhar em giras espec&iacute;ficas incorporados ou circulando os m&eacute;diuns (encostados), tanto em Giras de Direita quanto de Esquerda, especialmente quando n&atilde;o h&aacute; outras formas de trabalho dispon&iacute;veis para eles em determinadas Casas de Umbanda.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Sauda&ccedil;&atilde;o dos ciganos &eacute; &ldquo;Arriba!&rdquo; (Salve o povo cigano!).</span></span></span></span></span></p>

<img src="images/sara.jpg" style="padding: 0 15px;float:right; width:200px;height: 250px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Santa Sarah Kali &eacute; a orientadora espiritual do Povo Cigano. &Eacute; uma Santa da Igreja Cat&oacute;lica e n&atilde;o uma representa&ccedil;&atilde;o sincretizada de qualquer Orix&aacute;. Isto &eacute;, Santa Sarah Kali n&atilde;o &eacute; Orix&aacute;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Segundo a Igreja Cat&oacute;lica, Santa Sara auxiliou Maria Sant&iacute;ssima na hora do nascimento de Jesus Cristo. Por isso, al&eacute;m de padroeira do povo cigano, ela &eacute; padroeira das mulheres que querem engravidar e do bom parto. As ciganas que n&atilde;o conseguiam ter filhos come&ccedil;aram a rezar para Santa Sara, fazendo promessas de ir &agrave; cidade de Sante Maries de La Mer, caso suas gra&ccedil;as viessem a ser concedidas. Por isso as mulheres ciganas t&ecirc;m tanta devo&ccedil;&atilde;o para com ela.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ela tamb&eacute;m &eacute; a protetora dos exilados e dos desesperados. &Eacute; cultuada nos dias 24 e 25 de maio. O termo Kali significa &quot;a negra&quot;, porque sua pele era escura.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lendas sobre Santa Sarah Kali</span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Primeira Lenda:</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Segundo alguns historiadores, por volta dos anos 50 d.c, uma embarca&ccedil;&atilde;o teria partido de terras Palestinas e cruzado os mares, transportando os primeiros crist&atilde;os, de modo a conseguirem fugir das persegui&ccedil;&otilde;es de Roma.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Primeiros crist&atilde;os &eacute; o termo usado para o grupo de personagens b&iacute;blicos que conviveram com Jesus Cristo, se convertendo &agrave; sua mensagem e divulgando a Palavra ap&oacute;s a Ressurrei&ccedil;&atilde;o. Dentre os passageiros estariam Maria Jacobina ou Jacob&eacute;, irm&atilde; de Maria de Nazar&eacute;, m&atilde;e de Jesus; Maria Salom&eacute;, m&atilde;e dos ap&oacute;stolos Tiago e Jo&atilde;o; Maria Madalena; Marta; L&aacute;zaro; Maximiliano e Sarah, uma negra serva.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O barco teria, milagrosamente, sem rumo e &agrave; merc&ecirc; de todas as intemp&eacute;ries, atravessado o oceano e aportado em Petit-Rh&ocirc;ne, com todos salvos. Atualmente, a localidade &eacute; conhecida como Saintes-Maries-de-La-Mer (Santas Marias do Mar).</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sarah teria sido uma das primeiras convertidas ao cristianismo e morrido a servi&ccedil;o de suas companheiras de viagem, cumprindo sua promessa at&eacute; o final dos seus dias.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Segunda Lenda</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Uma outra vers&atilde;o da lenda &eacute; que Sarah seria uma escrava eg&iacute;pcia de uma das tr&ecirc;s Marias, Madalena, Jacob&eacute; ou Salom&eacute;. Junto com Jos&eacute; de Arimat&eacute;ia, Tr&oacute;fimo e L&aacute;zaro, as quatro mulheres foram lan&ccedil;adas ao mar, pelos judeus, em uma barca sem remos e alimentos.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Desesperadas, as tr&ecirc;s Marias puseram-se a orar e a chorar. Sarah, ent&atilde;o, retira o dikl&ocirc; (len&ccedil;o) da cabe&ccedil;a, chama por Kristesko (Jesus Cristo), prometendo que se todos se salvassem ela seria escrava de Jesus e jamais andaria com a cabe&ccedil;a descoberta em sinal de respeito. Acredita-se que deste gesto de Sarah Kali tenha nascido a tradi&ccedil;&atilde;o de toda mulher cigana casada usar um len&ccedil;o, que &eacute; a pe&ccedil;a mais importante do seu vestu&aacute;rio. Na tradi&ccedil;&atilde;o cigana, por exemplo, quando se quer oferecer o mais belo presente a uma cigana, diz-se: &ldquo;Dalto chucar dikl&ocirc;&rdquo; (Te darei um bonito len&ccedil;o).</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Milagrosamente, eles chegaram a salvo a uma praia pr&oacute;xima a Saintes Maries de La Mer (Santas Marias do Mar). Depois de muitos dias, o barco foi resgatado por moradores de uma vila pr&oacute;xima aos arredores da costa mar&iacute;tima. Todos foram acolhidos pelos moradores, exceto Sarah, por ser escrava (eg&iacute;pcia) e ter pele escura.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Presenciando o abandono de Sarah, um grupo de ciganos a acolheu, passando a cuidar dela, que viveu com eles at&eacute; sua morte, sendo muito querida pela comunidade. Quando veio a falecer, os ciganos foram at&eacute; a igreja da vila pedindo que seu funeral se realizasse na mesma. Devido ao preconceito, os cat&oacute;licos da &eacute;poca recusaram. O povo ent&atilde;o construiu uma pequena capela em homenagem &agrave; Sarah, a partir de uma gruta, visitada at&eacute; os dias de hoje.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ap&oacute;s sua morte, os ciganos passaram a recorrer ao esp&iacute;rito de Sarah Kali com pedidos. Sarah Kali passou a atender aos pedidos dos ciganos, realizando milagres. A partir disso, Sarah se tornou M&atilde;e e Rainha dos Ciganos, honrando-os e protegendo-os.</span></span></span></span></span></p>

					</p>
            </div>
            <div class="card-footer text-muted">
				21/01/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>