<?php $results['pageTitle'] = "Ibeji | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
			<img class="card-img-top" src="images/ibeji.jpg" alt="Card image cap">
				<h2 class="card-title"><center>IBEJI</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; o &uacute;nico orix&aacute; permanentemente duplo. Ibeji, o orix&aacute; formado por duas crian&ccedil;as g&ecirc;meas, &eacute; regente da linha das crian&ccedil;as, governa tudo referente as crian&ccedil;as at&eacute; sua adolesc&ecirc;ncia, e tudo que se inicia, desde a nascente de um rio ou o germinar das plantas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na mitologia africana s&atilde;o filhos de Xang&ocirc; e Ians&atilde;. Para os iorubas n&atilde;o existe maior riqueza que os filhos, pois garantem a continuidade. Agora ser aben&ccedil;oado por g&ecirc;meos, significa boa estrela, sorte e prosperidade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A palavra Ibeji em ioruba significa &ldquo;g&ecirc;meos, duplo&rdquo;, enquanto que a palavra er&ecirc; significa &ldquo;brincadeira, divers&atilde;o&rdquo;. N&atilde;o confundir com crian&ccedil;a que em ioruba se diz &ldquo;omod&eacute;&rsquo;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na &Aacute;frica os deuses g&ecirc;meos tinham nome, sendo eles Taiw&oacute; e Kahinde. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os orix&aacute;s crian&ccedil;as representam a for&ccedil;a da magia e est&atilde;o associados a tudo que &eacute; duplo. Inclusive a eterna dualidade do mundo como bem e mal, amor e guerra, material e espiritual, s&atilde;o muito bem representadas por eles. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Assim como crian&ccedil;as que s&atilde;o, sua energia representa a ingenuidade, leveza, espontaneidade, atividade e respeito aos mais velhos. &Eacute; a energia da inoc&ecirc;ncia. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Regem tamb&eacute;m todos os novos filhos das religi&otilde;es de matriz africana, pois quando iniciamos somos &ldquo;crian&ccedil;as&rdquo; na religi&atilde;o. Para o Candombl&eacute; tem papel indispens&aacute;vel entre os iniciados, pois s&atilde;o eles os respons&aacute;veis pela comunica&ccedil;&atilde;o dos orix&aacute;s com o ia&ocirc;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Alguns pais e m&atilde;es de santo mais antigos relatam que o zelador de santo deve cuidar muito bem de Exu e tamb&eacute;m de Ibeji. Este &uacute;ltimo para que n&atilde;o atrapalhe os rituais com suas brincadeiras infantis. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Muitas correntes do Candombl&eacute; consideram os er&ecirc;s como manifesta&ccedil;&otilde;es infantis dos outros orix&aacute;s, sendo que neste caso os er&ecirc;s s&atilde;o servidos com seu orix&aacute; correspondente. Por este motivo muitos er&ecirc;s se identificam como folhinha, pedrinha, ondinha, pipoquinha, entre outros. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na Umbanda sincretizamos Ibeji com os santos cat&oacute;licos g&ecirc;meos S&atilde;o Cosme e S&atilde;o Dami&atilde;o, e por este motivo cultuamos este orix&aacute; em 27 de setembro, dia do mart&iacute;rio dos santos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cosme e Dami&atilde;o eram m&eacute;dicos e crist&atilde;os que n&atilde;o curavam apenas pelo conhecimento medicinal, mas tamb&eacute;m por ora&ccedil;&otilde;es, e o mais importante, n&atilde;o cobravam nada por seus atendimentos, </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A igreja mais antiga ainda em p&eacute;, constru&iacute;da no Brasil, foi erigida em homenagem aos santos g&ecirc;meos. Constru&iacute;da em Igarassu, Pernambuco, na segunda metade do s&eacute;culo XVI (iniciou a constru&ccedil;&atilde;o em 1565). Igarassu faz pare da Regi&atilde;o Metropolitana do Recife e dizem que em 1685, Recife e adjac&ecirc;ncias foi assolada por um grande surto de febre amarela, entretanto, Igarassu escapou milagrosamente ilesa e este milagre foi conferido &agrave; Cosme e Dami&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Por este motivo, na Umbanda, tamb&eacute;m recorremos a Cosme e Dami&atilde;o para assuntos de sa&uacute;de. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Nas festividades deste orix&aacute; todos os terreiros, templos, tendas, ro&ccedil;as ou barrac&otilde;es abrem suas portas para todas as crian&ccedil;as para serem aben&ccedil;oadas por Ibeji e para receberem os famosos &ldquo;doces de Cosme e Dami&atilde;o&rdquo;. Na ocasi&atilde;o, normalmente a distribui&ccedil;&atilde;o de doce &eacute; farta, podendo incluir brinquedos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; no a&ccedil;&uacute;car que reside o ax&eacute; de Ibeji e &eacute; atrav&eacute;s do a&ccedil;&uacute;car que er&ecirc;, seu representante, distribui este ax&eacute;. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O que pedir?</span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Invocamos Ibeji/Cosme e Dami&atilde;o para cuidar de crian&ccedil;as em todas as situa&ccedil;&otilde;es, para a uni&atilde;o de casais, em casos de acidentes dom&eacute;sticos, nos problemas de sa&uacute;de, mas principalmente para trazer alegria, energia e paz no lar. Pedimos por eles tamb&eacute;m quando vamos iniciar qualquer coisa em nossas vidas. N&atilde;o s&atilde;o poucos os que recorrem a eles por prosperidade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Onde Ibeji est&aacute; assentado a negatividade n&atilde;o encontra campo f&eacute;rtil, mas o amor, a alegria, a uni&atilde;o e a paz sempre haver&atilde;o de prosperar. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Caracter&iacute;sticas dos filhos de Ibeji </span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Ibeji tem naturalmente um comportamento infantil, jovial e inconsequente. Independente da idade que possuam, carregam eternamente dentro de si a crian&ccedil;a interior. S&atilde;o brincalh&otilde;es, espertos, ativos, el&eacute;tricos, &agrave;s vezes um pouco chatos, resumindo, todo comportamento associ&aacute;vel ao de uma crian&ccedil;a. S&atilde;o emocionalmente fr&aacute;geis e muito dependentes nos relacionamentos amorosos, mas podem mostrar uma teimosia e obstina&ccedil;&atilde;o muito intensas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Podem revelar bruscas altera&ccedil;&otilde;es de temperamento e humor. Tendem a adotar posturas simplistas frente a problemas complexos, principalmente no que tange ao emocional. Magoam-se e decepcionam-se com facilidade, mas apresentam grande facilidade em deixar para tr&aacute;s essas tristezas. O tempo n&atilde;o passa para eles, carregam por muito tempo o rosto de crian&ccedil;as, e assim como crian&ccedil;as, gostam de movimento, praticar esportes, eventos sociais e festas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O amor para o homem de Ibeji s&oacute; faz sentido se for alegre e bonito. Principalmente alegre, pois como possui bom astral n&atilde;o consegue ficar pr&oacute;ximo de pessoas que n&atilde;o tenham esta qualidade. S&atilde;o brincalh&otilde;es e adoram fazer surpresas, fazem de tudo para agradar sua companhia, em suma, &eacute; uma &oacute;tima companhia. A mulher que deseja conquistar um homem de Cosme e Dami&atilde;o deve fazer de tudo para estimular sua criatividade, ter paci&ecirc;ncia com sua fragilidade emocional e vencer a desconfian&ccedil;a, pois eles morrem de medo de se machucar. Entretanto o homem deste orix&aacute; &eacute; um dos poucos que pode trazer a felicidade e o equil&iacute;brio para um relacionamento. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">J&aacute; a filha de Cosme e Dami&atilde;o n&atilde;o tem problema em conquistar quem deseja, pois frequentemente &eacute; muito atraente fisicamente, despertando assim o desejo do sexo oposto. &Eacute; naturalmente extrovertida, o que a coloca em constante evid&ecirc;ncia. N&atilde;o tolera a rotina em nenhum aspecto e est&aacute; sempre buscando novidades. &Eacute; vol&uacute;vel, sexualmente extremamente ativa e inovadora. Para conquista-la o homem tem que saber acompanha-la tanto sexual quanto mentalmente, nunca deixando a chama do relacionamento esmorecer. Nem o filho e nem a filha de Ibeji s&atilde;o ciumentos ou possessivos. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Outros Detalhes</span></span></strong></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sincretismo: S&atilde;o Cosme e S&atilde;o Dami&atilde;o; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Data de culto: 27 de setembro; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o: Oni Er&ecirc; ou Oni Ibeijada (Hoje tem brincadeira ou salve os g&ecirc;meos); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Aacute;rea de atua&ccedil;&atilde;o: Crian&ccedil;as, sa&uacute;de, alegria, tudo o que se inicia; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Elemento: Ar; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chacra: Todos especialmente o lar&iacute;ngeo; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Metal: Estanho; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Astro regente: Merc&uacute;rio; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dia da semana: Domingo; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da guia: Azul claro e ou rosa; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da vela: Azul claro e ou rosa; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pedra: Quartzo rosa; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebida: Suco de frutas, &aacute;gua com a&ccedil;&uacute;car, refrigerantes; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Amal&aacute;: Doces de qualquer natureza; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Frutas: Goiaba, groselha, jabuticaba, amora, pitanga, morango; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Flores: Cris&acirc;ntemos, margaridas, rosa manquinha; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas ervas: Manjeric&atilde;o, anis, alecrim, jasmim, rosa, ch&aacute;, trevo, verbena, flhas de groselha, folhas de amoreira, capim lim&atilde;o, folhas de morango;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local de oferta: Jardins, praias, parques e campos limpos; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Animais: Macaco;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Instrumentos: Brinquedos de qualquer natureza;</span></span></span></span></span></li>
</ul>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fontes: </span></span></span></span></span></p>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Marcio Kain, Curso de Teologia da Umbanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fl&aacute;vio Penteado, Povo de Aruanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ademir Jr, Teologia de Umbanda e suas dimens&otilde;es;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lurdes Vieira, Manual Doutrin&aacute;rio, Ritualistico e Comportamental Umbandista</span></span></span></span></span></li>

					</p>
					<a href="AUmbanda_OSORIXAS.php" class="btn btn-primary">&larr; Retornar aos Orixás</a>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 14/04/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>