<?php $results['pageTitle'] = "Nanã | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
			<img class="card-img-top" src="images/nana.jpg" alt="Card image cap">
				<h2 class="card-title"><center>NANÃ</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A mais velha Orix&aacute; cultuada no pante&atilde;o africano. Isso porque Nan&atilde; era cultuada pelo povo do Daom&eacute;, hoje Rep&uacute;blica do Benin, e os ritos e cultos deste povo eram muito antigos, vindos de uma cultura ancestral, que muitos atribuem ser anterior &agrave; descoberta do fogo. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O nome Nan&atilde; significa &ldquo;m&atilde;e&rdquo; e era exatamente isso que ela significava para os daomeanos. Da mesma forma que para os iorubas &eacute; Iemanj&aacute; quem ocupa esse papel. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tamb&eacute;m conhecida como Nan&atilde; Buruqu&ecirc;, Nan&atilde; Burucu, Nan&atilde; Bukuu e Nan&atilde; Brukung. Esta &uacute;ltima considerada uma divindade do fundo rio N&iacute;ger. Nan&atilde; tamb&eacute;m &eacute; um t&iacute;tulo que era dado a pessoas idosas e respons&aacute;veis. Por &uacute;ltimo, era costume uma mulher vi&uacute;va ou de idade avan&ccedil;ada ir morar ao lado do rio para ter menos dificuldade de criar os filhos, essas mulheres tamb&eacute;m eram chamadas de Nan&atilde; ou Nen&ecirc;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Foi incorporada &agrave; mitologia ioruba h&aacute; s&eacute;culos, quando o povo ioruba invadiu e conquistou o Daom&eacute;. Mesmo assim, a paternidade dos filhos de Nan&atilde; &eacute; atribu&iacute;da &agrave; Oxal&aacute;, mesmo n&atilde;o sendo ele parte do culto original &agrave; Nan&atilde;. Com o tempo, a absor&ccedil;&atilde;o de Nan&atilde; foi alcan&ccedil;ada com sucesso e estas pequenas faltas de sincronia mitol&oacute;gica deixaram de ser relevantes. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Muitos acreditam que o surgimento de Nan&atilde; esteja associado &agrave; cria&ccedil;&atilde;o do mundo, quando Odudu&aacute; separou a terra das &aacute;guas, foi no contato destes dois elementos, na lama formada pelos dois elementos e na &aacute;gua parada que surgiu Nan&atilde;. Por esta antiguidade Nan&atilde; &eacute; considerada senhora de muitos mist&eacute;rios, sendo que ela tamb&eacute;m representa a mem&oacute;ria ancestral. Tamb&eacute;m considerada a mais antiga das iab&aacute;s, senhora dos b&uacute;zios, da morte, da fecundidade e da riqueza. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; a m&atilde;e dos orix&aacute;s Iroko, Obalua&ecirc; e Oxumar&ecirc;. Entretanto, por ser representada sempre muito idosa, &eacute; considerada por muitos tamb&eacute;m a av&oacute; de todos os orix&aacute;s. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; o princ&iacute;pio, o meio e o fim. O nascimento, a vida e a morte. Os c&acirc;nticos de Nan&atilde; s&atilde;o s&uacute;plicas para levar Iku (a morte) para longe. &Eacute; ela quem permite que a vida seja mantida. Representa a for&ccedil;a natural mais temida pelos homens, pois ningu&eacute;m quer morrer. Ela &eacute; a senhora da passagem deste mundo para outro, a dona do portal para as dimens&otilde;es do al&eacute;m. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Nan&atilde; &eacute; a possibilidade de conhecer a morte para se valorizar a vida. &Eacute; agradar a morte para se viver em paz. Protege contra feiti&ccedil;os e o perigo de morte. &Eacute; a chuva, a tempestade e a garoa. Dona dos p&acirc;ntanos sendo o lodo seu dom&iacute;nio natural. O banho de chuva &eacute; considerado lavagem de corpo consagrada para este orix&aacute;. Os africanos acreditavam que a chuva traz a vida e a fecundidade da terra, quando a chuva cai demais &eacute; porque Nan&atilde; n&atilde;o est&aacute; satisfeita. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Nan&atilde; &eacute; considerada a m&atilde;e ou a av&oacute; boa, compreens&iacute;vel, carinhosa, sens&iacute;vel e bondosa, mas n&atilde;o reconhece ningu&eacute;m quando em estado de f&uacute;ria. Foi a grande mantenedora do in&iacute;cio da humanidade, pois quando as suas grandes chuvas ca&iacute;am enchiam os rios, e quando estes recuavam ao seu leito normal, deixava grande faixa de terra f&eacute;rtil onde ocorreram as primeiras planta&ccedil;&otilde;es. Foi do barro tamb&eacute;m que o homem p&ocirc;de construir sua primeira morada e foi a mesma argila que forneceu diversos utens&iacute;lios que tornaram mais f&aacute;ceis a vida dos seres humanos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Entre os s&iacute;mbolos de Nan&atilde; est&atilde;o a chave, que simboliza a passagem para o plano espiritual, e o ibiri, que &eacute; feito com palitos ou fibras do dendezeiro dobrados e adornado com b&uacute;zios, que representa a multid&atilde;o de eguns. Ela &eacute; a senhora de todos os eguns, que obedecem suas ordens, e foi quem dominou por primeiro este mist&eacute;rio. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os b&uacute;zios, que simbolizam morte por estarem vazios, e fecundidade porque lembram os &oacute;rg&atilde;os genitais femininos, tamb&eacute;m pertencem a Nan&atilde;. Contudo, o s&iacute;mbolo que melhor sintetiza o car&aacute;ter de Nan&atilde; &eacute; o gr&atilde;o, pois ela domina tamb&eacute;m a agricultura e todo o gr&atilde;o tem que morrer para germinar. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No Candombl&eacute;, sua dan&ccedil;a &eacute; lenta, segurando seu ibiri como um beb&ecirc;, cujos movimentos parecem o de embalar uma crian&ccedil;a. Seu andar &eacute; curvado mostrando toda a sua velhice. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Nan&atilde; rege as &aacute;guas paradas, o p&acirc;ntano, o mangue, a lama, o barro. O mesmo barro que serviu de mat&eacute;ria prima para criar o corpo f&iacute;sico do homem. E como dizem: &ldquo;do p&oacute; o homem veio e ao p&oacute; retornar&aacute;&rdquo;. Isto tamb&eacute;m &eacute; uma alus&atilde;o da terra que recolhe o corpo f&iacute;sico para consumi-lo e faz&ecirc;-lo retornar ao p&oacute;. Isto tamb&eacute;m &eacute; atributo de Nan&atilde;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dizem que Nan&atilde; ampara o esp&iacute;rito do morto enquanto seu corpo &eacute; enterrado. A responsabilidade de Nan&atilde; tamb&eacute;m rege a reencarna&ccedil;&atilde;o, pois &eacute; ela que recolhe os esp&iacute;ritos prontos para a reencarna&ccedil;&atilde;o, e, em seu abra&ccedil;o, faz com que percam a forma, assumindo a forma de uma esfera de energia para ser conectado ao &oacute;vulo fecundado na barriga da futura m&atilde;e terrena. &Eacute; Nan&atilde; tamb&eacute;m, por cuidar da mem&oacute;ria ancestral, quem apaga a mem&oacute;ria dos esp&iacute;ritos ao reencarnarem para que isso n&atilde;o atrapalhe a reencarna&ccedil;&atilde;o vindoura. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Forma com Oxal&aacute; o casal mais velho. Oxal&aacute; que &eacute; representado ora como esposo, ora como amante, que lhe deu filhos e que roubou o segredo dos eguns de Nan&atilde;. Como uma boa idosa, Nan&atilde; &eacute; previdente, organizada e grande zeladora da moral e dos bons costumes. &Eacute; austera, autossuficiente e tem grande capacidade de trabalho; n&atilde;o tolera pregui&ccedil;a, falta de educa&ccedil;&atilde;o, desordem e desperd&iacute;cio. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">N&atilde;o perdoa mentirosos, trai&ccedil;&otilde;es e nem a desonestidade. Jurar por Nan&atilde; &eacute; assumir uma grande responsabilidade perante a orix&aacute;, a qual cobrar&aacute; incessantemente o promissor at&eacute; que cumpra com o juramento. Os filhos de Nan&atilde; sabem, por este motivo, que n&atilde;o devem nunca jurar em seu nome. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O que pedir?</span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Recorremos &agrave; Nan&atilde; para o recebimento de entes queridos falecidos, contra o perigo de morte, para aprimorar nossas virtudes, pois &eacute; ela quem decanta nossos defeitos, no encerramento e in&iacute;cio de ciclos, tamb&eacute;m para a maternidade e em todas as &ldquo;mortes&rdquo; que passamos pela vida. Nan&atilde; ativa o nosso racional para que possamos &ldquo;morrer&rdquo; (transformar), para que possamos nascer melhores e mais equilibrados. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Podemos pedir ainda sabedoria, experi&ecirc;ncia e amadurecimento em nossas vidas. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Caracter&iacute;sticas dos filhos de Nan&atilde; </span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Normalmente s&atilde;o calmos e at&eacute; um pouco lentos. Gostam de crian&ccedil;as, sempre aparentam mais idade do que realmente possuem. N&atilde;o sentem grandes apelos nem pela beleza e nem pela vaidade. S&atilde;o pessoas de &iacute;mpeto, boas, decididas, simp&aacute;ticas, remoem as coisas, guardam rancor de situa&ccedil;&otilde;es n&atilde;o resolvidas. Exigem a aten&ccedil;&atilde;o e o respeito que julgam merecer, independente de terem ou n&atilde;o conquistado estes sentimentos daqueles que o cercam. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tem dificuldades em entender as opini&otilde;es alheias, e, da mesma forma, ficam implicados quando n&atilde;o compreendidos. N&atilde;o entendem como as pessoas n&atilde;o pensam da mesma forma que eles. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">N&atilde;o tomam decis&otilde;es de imediato, pois sabem que toda decis&atilde;o deve ser muito bem analisada. Quando as tomam, s&atilde;o decis&otilde;es s&aacute;bias, justas e equilibradas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o conservadores e nost&aacute;lgicos. Sempre desejando que momentos e costumes do passado retornem, mesmo sabendo que n&atilde;o voltar&atilde;o. Gostam de um mundo previs&iacute;vel e sem sobressaltos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Reclamam dos novos costumes, das novas posturas, da vida atual, enfim, reclamam de tudo o que for novo ou que altere sua rotina muito bem programada. Envelhecem mais r&aacute;pido que os demais e n&atilde;o aparentam for&ccedil;a f&iacute;sica, mas s&atilde;o capazes de surpreender quanto &agrave; for&ccedil;a e &agrave; disposi&ccedil;&atilde;o que possuem. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Valorizam por demais os detalhes e pequenas coisas, transformando quase sempre pequenos problemas em dramas indissol&uacute;veis. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No sentido oposto s&atilde;o excelentes ouvintes e tem grande capacidade de compreens&atilde;o do ser humano, como se fossem mais velhos e experimentados do que realmente s&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Como consequ&ecirc;ncia, dar o perd&atilde;o para os que erram e o consolo para os sofredores &eacute; uma habilidade natural dos filhos desta orix&aacute;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Equilibrados os filhos de Nan&atilde; s&atilde;o sensatos, perseverantes, organizados, dispostos e objetivos. Em desequil&iacute;brio demonstram estupidez, pregui&ccedil;a, conservadorismo extremo, medo e avareza. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Apar&ecirc;ncia f&iacute;sica pesada, desgraciosa, podendo indicar fracasso na sexualidade e no amor. Seu modo de vida austero e &ldquo;reclam&atilde;o&rdquo; pode lev&aacute;-lo &agrave; solid&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A filha de Nan&atilde; tem um temperamento severo e austero. Rabugenta, &eacute; mais temida do que amada, podendo n&atilde;o ter grandes atrativos para o sexo oposto. Afasta-se do amor por medo de ser abandonada. Afasta-se do sexo por medo de ser usada. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Nan&atilde; s&atilde;o sempre prontos e tem facilidade para enxergar as necessidades dos outros. Dedicam-se muito &agrave; vida profissional e &agrave; ambi&ccedil;&atilde;o social, postos que galgam com facilidade pela entrega e dedica&ccedil;&atilde;o que carregam em si. S&atilde;o caridosos e frequentemente est&atilde;o envolvidos em campanhas sociais ou comunit&aacute;rias visando o bem de uma coletividade. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Outros Detalhes</span></span></strong></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sincretismo: Sant&rsquo;Anna; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Data de culto: 26 de julho;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o: Saluba Nan&atilde;! (Nos refugiamos com Nan&atilde;); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Aacute;rea de atua&ccedil;&atilde;o: A vida e a morte, maternidade, amadurecimento, sabedoria. Senhora dos esp&iacute;ritos; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Elemento: &Aacute;gua (em contato com terra);</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chacra: Frontal;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Metal: N&iacute;quel ou lat&atilde;o;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Astro regente: Lua (no quarto minguante);</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dia da semana: Segunda-feira (junto com as almas);</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da guia: Lil&aacute;s ou violeta;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da vela: Lil&aacute;s ou violeta;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pedra: Ametista, tanzanita;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebida: Champanha ros&eacute;, vinho licoroso, &aacute;gua de coco, &aacute;gua de chuva;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Amal&aacute;: Feij&atilde;o preto com pur&ecirc; de batata doce, pipoca, farofa de dend&ecirc; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Frutas: laranja lima, figo, ameixa, uva escura, fruta do conde, coco seco, banana da terra, mel&atilde;o de S&atilde;o Caetano, abacaxi e jaca;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Flores: Rosa rubra, cris&acirc;ntemo roxo e violeta;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas ervas: Manac&aacute;, folhas de berinjela, folha da fortuna, avenca, alfavaca. Viuvinha, cana do brejo, manjeric&atilde;o roxo, canela de velho;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local de oferta: P&acirc;ntanos, lama&ccedil;ais, beira de rio e cemit&eacute;rio; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Animais: R&atilde;, galinha branca, pata branca;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Instrumentos: Ibiri &ndash; cetro feito de cerne de dendezeiro curvado e adornado de b&uacute;zios);</span></span></span></span></span></li>
</ul>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fontes: </span></span></span></span></span></p>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Marcio Kain, Curso de Teologia da Umbanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fl&aacute;vio Penteado, Povo de Aruanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ademir Jr, Teologia de Umbanda e suas dimens&otilde;es;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lurdes Vieira, Manual Doutrin&aacute;rio, Ritualistico e Comportamental Umbandista</span></span></span></span></span></li>

					</p>
					<a href="AUmbanda_OSORIXAS.php" class="btn btn-primary">&larr; Retornar aos Orixás</a>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 14/04/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>