<?php $results['pageTitle'] = "OS Orixás | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
				<h2 class="card-title"><center>A PREPARAÇÃO PARA OS TRABALHOS</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A prepara&ccedil;&atilde;o para os trabalhos medi&uacute;nicos &eacute; feita por meio dos &ldquo;Preceitos&rdquo;. Preceito &eacute; tudo aquilo que deve ser preparado antes do in&iacute;cio de um trabalho espiritual. Os preceitos s&atilde;o regras b&aacute;sicas necess&aacute;rias para o bom desempenho da atividade religiosa e obrigat&oacute;rias para todos os trabalhadores que adentrar&atilde;o ao terreiro. Tamb&eacute;m s&atilde;o desej&aacute;veis para a assist&ecirc;ncia. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Existem tr&ecirc;s preceitos fundamentais para a prepara&ccedil;&atilde;o de m&eacute;diuns e cambonos para os trabalhos espirituais, que devem ser obedecidos desde a meia-noite do dia de trabalho. S&atilde;o eles: </span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">n&atilde;o manter rela&ccedil;&otilde;es sexuais: </span></strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Durante<strong> </strong>o sexo, h&aacute; uma troca de fluidos corp&oacute;reos e uma troca energ&eacute;tica, que pode ser saud&aacute;vel ou n&atilde;o.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">n&atilde;o consumir drogas nem bebidas alco&oacute;licas:</span></strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"> a bebida interfere com o inconsciente do m&eacute;dium, podendo abrir passagens que permitem o acesso de presen&ccedil;as indesej&aacute;veis e provocam desequil&iacute;brio. Al&eacute;m disso, &eacute; desrespeitoso que o m&eacute;dium se apresente perante seus Orix&aacute;s e Guias alcoolizado ou mesmo drogado. Deve-se salientar que os Guias fazem uso da bebida e do fumo apenas durante o trabalho espiritual. Al&eacute;m disso, o fazem n&atilde;o por v&iacute;cio, mas sim por necessidade de manipula&ccedil;&atilde;o energ&eacute;tica, por meio da fuma&ccedil;a dos &ldquo;pitos&rdquo; ou dos vapores e odores das bebidas.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">n&atilde;o comer carne: </span></strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">a digest&atilde;o da carne, especialmente as vermelhas, isto &eacute;, de vaca, porcos, cabras, por exemplo, &eacute; mais lenta que outros alimentos. Isso vale para presuntos, pat&ecirc;s, salames, salsichas e embutidos em geral. Durante o processo digestivo, alguns esp&iacute;ritos podem se aproveitar e se alimentar da energia em libera&ccedil;&atilde;o na digest&atilde;o. Com isso, podem ficar mais pr&oacute;ximos dos m&eacute;diuns, dificultando uma boa incorpora&ccedil;&atilde;o e atrapalhando os trabalhos dos guias e mentores. Ainda, nos caos dos trabalhos que envolvem tratamentos para a cura, a produ&ccedil;&atilde;o de ectoplasma do m&eacute;dium, necess&aacute;ria para os procedimentos, fica comprometida. Assim, o m&eacute;dium deve buscar substitutos para as carnes em geral, mas este preceito n&atilde;o &eacute; considerado absoluto, pois nem sempre os m&eacute;diuns ter&atilde;o op&ccedil;&otilde;es para se alimentar. Nesses casos, deve-se buscar vegetais ou ovos. N&atilde;o estando dispon&iacute;veis, carne de peixe em pequena quantidade e, em &uacute;ltimo caso, carnes vermelhas em pequena quantidade.</span></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Estes preceitos visam &ldquo;guardar&rdquo; o corpo dos m&eacute;diuns e cambonos para as entidades que far&atilde;o uso dele nos trabalhos. Primeiro, em respeito aos Guias, que precisam de um corpo sadio e limpo, que emane boas energias, para um trabalho eficaz. Em segundo lugar, um corpo carregado de energias viciosas dificulta o descarrego que as entidades executam antes de partir. No processo de prepara&ccedil;&atilde;o para o trabalho umbandista, &eacute; tamb&eacute;m recomendado que o m&eacute;dium tome um banho de ervas, detalhado posteriormente.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Por fim, &eacute; preciso ter em mente que nossas atitudes e comportamento s&atilde;o mais importantes que todos esses preceitos. &ldquo;&Eacute; mais prejudicial o que sai da boca para fora, do que entra pela boca adentro&rdquo; (Marcio Kain).</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><a name="_Toc516214045"><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Banho de Ervas</span></strong></a><strong> </strong></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Banho de ervas aproxima o Guia do m&eacute;dium, gerando tamb&eacute;m prote&ccedil;&atilde;o e energia. Em dias de trabalho, fortalece a liga&ccedil;&atilde;o do m&eacute;dium com o Orix&aacute;, permitindo que a Entidade trabalhe em plena for&ccedil;a. O banho serve ainda como um instrumento de descarrego de energias delet&eacute;rias (energias ruins, pesadas).</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A &aacute;gua tamb&eacute;m &eacute; um componente importante na ativa&ccedil;&atilde;o das propriedades das ervas e na absor&ccedil;&atilde;o pelo esp&iacute;rito. </span></span></span></span></p>

<img src="images/ervas.jpg" style="padding: 0 15px;float:right; width:270px;height:150px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Podem ser utilizadas ervas frescas, secas ou as duas juntas, dependendo do que est&aacute; dispon&iacute;vel. Os banhos podem ser feitos com &aacute;gua quente ou fria, dependendo muito do tipo de ervas que ser&atilde;o utilizadas.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Se o banho for composto por apenas ervas frescas o preparo ocorre da seguinte maneira:</span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lavar todas as ervas em &aacute;gua corrente;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Colocar as ervas em uma bacia com &aacute;gua corrente fria;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Macerar (amassar) as ervas com as m&atilde;os, dentro da bacia com &aacute;gua;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cubrir ou tampar a bacia e deixar descansar por 1 hora; e</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;Coar a infus&atilde;o e jogar as ervas num vaso de planta ou jardim (devolver &agrave; terra, se poss&iacute;vel).</span></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A pr&aacute;tica de macerar as ervas &eacute; muito bem recomendada, pois quando voc&ecirc; entra em contato direto, come&ccedil;a ser ativado pelas energias de descarrego e energiza&ccedil;&atilde;o das ervas, ou seja, as ervas come&ccedil;am imediatamente a agir em seu corpo perispiritual, mesmo antes do banho. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Esta forma de fazer o banho deve ser usada preferencialmente para folhas verdes e frescas. Algumas ervas podem causar efeitos indesej&aacute;veis, caso n&atilde;o sejam adequadamente manipuladas. Por isso, os banhos devem ser prescritos pelo Dirigente e pelos Guias da Casa, que indicar&atilde;o os banhos de acordo com as necessidades de cada m&eacute;dium ou consulente.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Banhos compostos por ervas secas ou por ervas secas e frescas precisam de um preparo com &aacute;gua quente. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><u><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Como Preparar:</span></u></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ferver uma caneca com &aacute;gua e apagar o fogo ap&oacute;s o in&iacute;cio da fervura;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Colocar as ervas para a infus&atilde;o e tampar;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ap&oacute;s 15 minutos, coar a infus&atilde;o; e</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Jogar as ervas num vaso de planta ou jardim (devolver &agrave; terra, se poss&iacute;vel).</span></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Todos os banhos de ervas s&atilde;o administrados ap&oacute;s o banho de higiene normal. O preparado pode ser colocado em um balde, bacia ou vasilha e misturado com a &aacute;gua do chuveiro. Fa&ccedil;a uma ora&ccedil;&atilde;o antes de jogar o banho sobre o corpo. O preparado deve ser jogado no corpo do pesco&ccedil;o para baixo, dando-se prefer&ecirc;ncia para o peito e as costas. Aguarda-se a absor&ccedil;&atilde;o e enxuga-se normalmente. Isto deve ser feito preferencialmente pouco antes de se encaminhar para o terreiro. Por vezes, os Guias podem receitar o banho a partir do topo da cabe&ccedil;a.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Esses banhos tamb&eacute;m pode ser utilizados depois dos trabalhos medi&uacute;nicos ou em outras condi&ccedil;&otilde;es, sob recomenda&ccedil;&atilde;o dos Guias da Casa.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><a name="_Toc516214046"><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Firmeza de Velas</span></strong></a><strong> </strong></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Esse &eacute; um aspecto fundamental. &Eacute; na firmeza das velas que ocorre a transfer&ecirc;ncia de energia necess&aacute;ria para nossa jornada de f&eacute;. Para tanto, s&atilde;o necess&aacute;rios alguns princ&iacute;pios: que a vela seja dedicada a um Orix&aacute; ou Entidade espec&iacute;fica, para que nenhum outro esp&iacute;rito possa ter acesso &agrave; ela. &Eacute; preciso tamb&eacute;m que seja feito um pedido de cora&ccedil;&atilde;o limpo para a Entidade, para que a for&ccedil;a da sua vontade seja impressa na vela. A esse processo se d&aacute; o nome de &ldquo;plasmar&rdquo; a vela. Conforme a vela vai se consumindo, as energias s&atilde;o transferidas para a Entidade, que a transformar&aacute; na realiza&ccedil;&atilde;o do seu pedido, de acordo com o merecimento de quem fez o pedido. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As velas podem ser firmadas para agradecimentos, para pedidos e, antes do in&iacute;cio dos trabalhos, para pedir prote&ccedil;&atilde;o. &Eacute; importante saber que as velas para os Srs. Exus devem ser as primeiras a serem firmadas em qualquer ocasi&atilde;o. Na firmeza da vela, o filho de f&eacute; pode utilizar ora&ccedil;&atilde;o pr&oacute;pria (espont&acirc;nea), ora&ccedil;&otilde;es tradicionais (Pai-Nosso, Ave-Maria. etc) ou uma ora&ccedil;&atilde;o m&iacute;nima com o nome da Entidade. Segue um exemplo: </span></span></span></span></p>

<img src="images/vela.jpg" style="padding: 0 15px;float:left; width:170px;height: 150px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&ldquo;Salve [nome da entidade] ! Salve toda a sua for&ccedil;a e toda a sua banda! </span></strong></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A ti firmo esta vela com todo amor do meu cora&ccedil;&atilde;o, para agradecer-lhe tudo que faz por mim e pedir a sua prote&ccedil;&atilde;o, sua ajuda material e espiritual para [fazer o pedido que deseja]. Sou confiante! Salve!&rdquo; </span></strong></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Note que utilizamos o termo &ldquo;firmar&rdquo; e n&atilde;o &ldquo;acender&rdquo; velas. Velas s&atilde;o acesas para ilumina&ccedil;&atilde;o de ambientes, quando falta energia el&eacute;trica, por exemplo, e para decora&ccedil;&atilde;o. Umbandistas firmam velas.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><a name="_Toc516214047"><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Ora&ccedil;&otilde;es</span></strong></a><strong> </strong></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A ora&ccedil;&atilde;o &eacute; uma das mais importantes ferramentas do umbandista. As ora&ccedil;&otilde;es n&atilde;o devem ser feitas somente no ato de firmeza de velas, pois n&atilde;o se firmam velas todos os dias. A contr&aacute;rio, as ora&ccedil;&otilde;es devem ser feitas diariamente. Tudo o que se precisa &eacute; de alguns minutos, boa vontade e f&eacute;. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tudo pode ser alcan&ccedil;ado atrav&eacute;s da ora&ccedil;&atilde;o, isto depende apenas de quem a profere. Feita diariamente, auxilia na desagrega&ccedil;&atilde;o de maus fluidos e na aproxima&ccedil;&atilde;o de boas energias, resultando em um &oacute;timo t&ocirc;nico para a manuten&ccedil;&atilde;o do esp&iacute;rito. Lembre-se das palavras do Mestre Jesus Cristo: &ldquo;<strong>orai e vigiai sempre&rdquo;</strong>. Este ensinamento deve ser levado &agrave; risca por todo umbandista que se preze. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ora&ccedil;&atilde;o &eacute; um momento de reconex&atilde;o com o sagrado, de restabelecimento do contato com Deus. Pode ser espont&acirc;nea ou decorada. Lembrando novamente as palavras de Jesus, disse Ele que tudo aquilo que pedirmos atrav&eacute;s do Pai-Nosso, ser&aacute; imediatamente recebido. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Segundo Marcio Kain, <em>a ora&ccedil;&atilde;o pode ser silenciosa, mas se o filho de f&eacute; deseja um melhor resultado, sugerimos que as fa&ccedil;a em p&eacute; e em voz alta, como se estivesse ordenando algo. O Poder do verbo ir&aacute; certamente ampliar o poder da ora&ccedil;&atilde;o.</em></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><a name="_Toc516214048"><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As Roupa</span></strong></a><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">s </span></strong></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As roupas para o trabalho medi&uacute;nico ou &ldquo;roupas de santo&rdquo; devem ser condizentes com uma pr&aacute;tica religiosa. N&atilde;o devem ser justas, curtas, decotadas, transparentes ou ostensivas. Dar prefer&ecirc;ncia aos tecidos naturais como o algod&atilde;o. Quanto &agrave; cor, dever&atilde;o ser brancas nos trabalhos.</span></span></span></span></p>

<img src="images/roupa.jpg" style="padding: 0 15px;float:right; width:370px;height: 250px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O uso adequado da roupa branca de trabalho &eacute; condi&ccedil;&atilde;o que deve ser seguida com seriedade. Um m&eacute;dium n&atilde;o vai receber seus Guias e Mentores com uma roupa inadequada, suja ou mesmo rasgada. A roupa do m&eacute;dium deve ser bem lavada, perfumada e descarregada.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em algumas Casas, os procedimentos para a lavagem das roupas de trabalho s&atilde;o definidas pelo Dirigente. Nas Casas que seguem tradi&ccedil;&otilde;es umbandistas mais antigas, n&atilde;o se pode colocar a roupa de santo tomando o sereno da noite. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O procedimento corriqueiro para a lavagem da roupa branca de trabalho &eacute; o seguinte:</span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lavar a roupa branca normalmente, para tirar a sujeira mais grossa;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lavar novamente, com sal grosso; e</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No enxague, colocar anil ou ess&ecirc;ncias ou mesmo alfazema.</span></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Obs: N&atilde;o lave as roupas de trabalho junto com roupas comuns do dia-a-dia.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><a name="_Toc516214051"><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O dia dos Trabalhos</span></strong></a><strong> </strong></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; desejado que o m&eacute;dium mantenha-se calmo durante o dia em que ir&aacute; trabalhar no terreiro e evite conflitos de qualquer tipo. Isso &eacute; importante porque, quando perdemos a calma, entramos em sintonia com esp&iacute;ritos e energias hostis que ir&atilde;o contaminar e envenenar o nosso esp&iacute;rito. No caso de m&eacute;diuns atendentes ou cambonos, isto dificultar&aacute; a incorpora&ccedil;&atilde;o e tornar&aacute; a atividade do Guia incorporado mais dif&iacute;cil. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No dia de trabalho, &eacute; comum a espiritualidade mal intencionada &ldquo;atacar&rdquo; o m&eacute;dium ou o assitido, tentando evitar que compare&ccedil;am &agrave; Casa e tornando a tarefa ainda mais dif&iacute;cil. Os convites para festas e reuni&otilde;es com amigos tamb&eacute;m costumam acontecer com mais frequ&ecirc;ncia em dias de trabalho, de forma a tirar o m&eacute;dium do caminho de sua miss&atilde;o. Dores repentinas, des&acirc;nimo, apatia e falta de vontade de ir aos trabalhos s&atilde;o tamb&eacute;m muito comuns. A solu&ccedil;&atilde;o &eacute; manter-se calmo e paciente, firme no seu prop&oacute;sito, orando e vigiando. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chegar com bastante anteced&ecirc;ncia ao terreiro, caso poss&iacute;vel, &eacute; extremamente recomend&aacute;vel para ajudar na prepara&ccedil;&atilde;o do trabalho, seja m&eacute;dium, cambono ou outro trabalhador. &Eacute; preciso lembrar que todo o trabalho desenvolvido dentro de um terreiro n&atilde;o &eacute; para o Dirigente, nem para o m&eacute;dium, nem mesmo para a assist&ecirc;ncia. &Eacute; sempre um trabalho para Deus, todos os Orix&aacute;s, Guias e Protetores, os quais saber&atilde;o te recompensar, de acordo com o sentimento com o qual voc&ecirc; realizou o seu trabalho e o seu merecimento. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><a name="_Toc516214049"><strong><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O P&eacute; no Ch&atilde;o</span></strong></a><strong> </strong></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O p&eacute; no ch&atilde;o tem v&aacute;rias simbologias: a humildade necess&aacute;ria para o trabalho de caridade e as ra&iacute;zes e tradi&ccedil;&otilde;es da Umbanda. Lembre que &iacute;ndios e negros n&atilde;o usavam cal&ccedil;ados. &Eacute; o contato com o elemento natural terra, pois a Umbanda trabalha com as for&ccedil;as da natureza, mas a principal fun&ccedil;&atilde;o &eacute; facilitar o descarrego.</span></span></span></span></p>

<img src="images/pe.jpg" style="padding: 0 15px;float:left; width:270px;height: 250px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na Tenda Nossa Senhora da Piedade, que &eacute; considerada a Tenda M&atilde;e da Umbanda, os m&eacute;diuns trabalhavam cal&ccedil;ados. Entretanto, por v&aacute;rios motivos culturais ou regionais, a maioria das Casas n&atilde;o faz disso um procedimento obrigat&oacute;rio. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Al&eacute;m de tudo o que foi visto, lembre sempre que o comprometimento, a responsabilidade e a pontualidade s&atilde;o tamb&eacute;m da maior import&acirc;ncia, tanto quanto os preceitos e procedimentos aqui descritos, e devem ser observado com seriedade.</span></span></span></span></p>

					</p>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 02/12/2018
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>