<?php $results['pageTitle'] = "Ogum | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
			<img class="card-img-top" src="images/ogum.jpg" alt="Card image cap">
				<h2 class="card-title"><center>OGUM</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A tradu&ccedil;&atilde;o do nome Ogum j&aacute; nos diz muito a respeito deste Orix&aacute;. O significado pode ser &ldquo;Senhor da Guerra&rdquo; ou &ldquo;Guerreiro&rdquo;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Para n&oacute;s, Ogum imediatamente remete &agrave; ideia de prote&ccedil;&atilde;o e de caminhos abertos. Mas originalmente ele era visto como o Orix&aacute; da metalurgia. Sendo assim, tudo o que pudesse ser confeccionado em metal era atribu&iacute;do a Ogum. De armas para a ca&ccedil;a e para a guerra, utens&iacute;lios dom&eacute;sticos e principalmente ferramentas. Principalmente aquelas voltadas para a agricultura e que facilitavam a vida no campo. Por este motivo, Ogum tamb&eacute;m foi conhecido como Orix&aacute; da agricultura. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ogum &eacute; considerado o primeiro Orix&aacute; a descer do Orun (c&eacute;u) para o Aiy&ecirc; (terra). Carrega consigo um molho de ferramentas contendo alavanca, machado, p&aacute;, picareta, espada, faca e outros instrumentos que fez quest&atilde;o de mostrar aos homens e ensinar como deveriam ser feitos. Foi com estes instrumentos que o homem dominou a natureza. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tudo o que o ser humano faz para melhorar as atividades costumeiras &eacute; conhecido como tecnologia. Tecnologia &eacute; inova&ccedil;&atilde;o. E &eacute; por isso que Ogum &eacute; considerado o Orix&aacute; patrono da tecnologia. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; o poder do sangue que corre nas veias. Como Exu, est&aacute; presente no calor e na ira. Ogum &eacute; uma for&ccedil;a da natureza, incontrol&aacute;vel, que se faz presente nos momentos de for&ccedil;a e impacto. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Ogum tem tend&ecirc;ncia a serem magros, t&iacute;midos, discretos, atraentes e algumas correntes defendem que podem ter mudan&ccedil;a radical ap&oacute;s os 40 anos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ogum &eacute; o arqu&eacute;tipo do guerreiro. Bastante venerado no Brasil por estar associado &agrave; luta e &agrave; conquista. Tem como sincretismo S&atilde;o Jorge e Santo Antonio, figuras extremamente populares dos cat&oacute;licos, o que ajudou a disseminar seu culto. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Filho de Iemanj&aacute;, irm&atilde;o mais velho de Exu e Ox&oacute;ssi. Este &uacute;ltimo extremamente adorado pelo irm&atilde;o, foi Ogum quem deu &agrave; Ox&oacute;ssi suas ferramentas para a ca&ccedil;a. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ogum rege o sangue que corre em nossas veias e talvez isso explique o comportamento t&atilde;o ativo deste Orix&aacute;, que pode ser cruel e impiedoso com os inimigos, mas tamb&eacute;m d&oacute;cil e am&aacute;vel para aqueles que ama. &Eacute; a vida em seus extremos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ogum &eacute; aquele que adora iniciar uma conquista, mas n&atilde;o usufrui dela. T&atilde;o logo alcance a vit&oacute;ria, busca uma nova demanda. Gosta do calor da batalha e n&atilde;o dos louros da vit&oacute;ria. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ao mesmo tempo, &eacute; imparcial e implac&aacute;vel. &Eacute; o agente que executa a lei ditada por Xang&ocirc;. N&atilde;o discute a lei, apenas a aplica de forma exemplar. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; e sempre ser&aacute; mais paix&atilde;o que raz&atilde;o. Aos amigos, tudo, at&eacute; o doloroso perd&atilde;o. Aos inimigos, a m&atilde;o forte e impiedosa da destrui&ccedil;&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Diz uma lenda que coube a Ogum a tarefa de povoar a Terra. E assim seguiu Ogum, abrindo caminhos, firmando aldeias e seguindo com sua tarefa at&eacute; conclu&iacute;-la. Ent&atilde;o Ogum n&atilde;o &eacute; apenas um guerreiro ou aquele que abre picadas na densa mata virgem. &Eacute; tamb&eacute;m o respons&aacute;vel por todo o conhecimento pr&aacute;tico existente, aquele que tira as ideias do papel e as torna reais. Da agricultura, passando pelas armas, pela eletricidade e pelos atuais computadores, Ogum, o patrono da tecnologia, &eacute; o grande desbravador do mundo em que vivemos. Assim sendo ele abre caminhos para a instala&ccedil;&atilde;o de uma rodovia ou estrada de ferro, leva energia e saneamento a lugares carentes, favorece a instala&ccedil;&atilde;o de ind&uacute;stria em locais in&oacute;spitos. &Eacute; o respons&aacute;vel pelo desenvolvimento. O desconhecido &eacute; seu inimigo. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; padroeiro de todos os of&iacute;cios que trabalhem com carros, caminh&otilde;es, ferramentas e armas. Ogum &eacute; o grande protetor dos militares. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na Umbanda, &eacute; o protetor maior, sem o qual n&atilde;o h&aacute; seguran&ccedil;a nas giras. &Eacute; tamb&eacute;m considerado protetor contra toda e qualquer entidade masculina, encarnada ou desencarnada. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O que pedir?</span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Recorremos a Pai Ogum para a prote&ccedil;&atilde;o de qualquer tipo de mal, nas brigas, conflitos e desaven&ccedil;as &eacute; ajuda poderosa, para o desenvolvimento de empresas ligadas &agrave; ind&uacute;stria, &agrave; qu&iacute;mica e &agrave; tecnologia, e, por fim, para que a lei se cumpra. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Caracter&iacute;stica de Ogum e seus filhos </span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O orix&aacute; e seus filhos dividem as caracter&iacute;sticas sendo trabalhadores, impetuosos, autorit&aacute;rios, desconfiados e um pouco ego&iacute;stas. &Eacute; f&aacute;cil perceber a presen&ccedil;a de um filho de Ogum. Ele &eacute; coerente e eloquente, sempre defendendo com muita paix&atilde;o seus pontos de vista. Sem perceber, este comportamento coerente se transforma em uma explos&atilde;o, onde a intoler&acirc;ncia e a teimosia aparecer&atilde;o certamente. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Gostam de festas, de estar entre amigos e de conversas que n&atilde;o acabam mais. Fazem suas pr&oacute;prias brigas e, caso n&atilde;o consigam, compram a dos companheiros. Mas s&atilde;o amigos e companheiros para uma vida. Gostam de desafios e de tudo o que for novidade. Entretanto, um filho de Ogum pode mudar se encontrar seu verdadeiro amor. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Gostam de viagens, de trocar de endere&ccedil;o e est&atilde;o sempre antenados aos &uacute;ltimos lan&ccedil;amentos tecnol&oacute;gicos. S&atilde;o curiosos e quando tem sua aten&ccedil;&atilde;o presa a algo, querem aprender sobre aquilo. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o batalhadores e fazem de tudo para alcan&ccedil;ar seus objetivos. Contrariando o l&oacute;gico, alcan&ccedil;am a vit&oacute;ria mesmo diante do imposs&iacute;vel, como em tudo em suas vidas. N&atilde;o se prendem &agrave; riqueza. Ganham hoje, gastam amanh&atilde;. O que os fascina &eacute; o poder e o comando. S&atilde;o l&iacute;deres natos e esta necessidade de estar &agrave; frente de tudo pode torna-los desagrad&aacute;veis. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fazem de tudo uma competi&ccedil;&atilde;o, mas tem dificuldades em se comunicar e acabam sendo por demais &aacute;speros quando tentam impor suas vontades e ideias. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Normalmente s&atilde;o alegres e falantes, contam suas hist&oacute;rias, sempre falando alto para que todos possam se divertir com elas. Adoram compartilhar suas felicidades. N&atilde;o s&atilde;o exigentes para comida, vestu&aacute;rio e moradia, n&atilde;o se preocupam muito com tais coisas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Ogum tem muita dificuldade de perdoar, mas perdoam os amigos e os entes queridos. Mesmo porque sempre est&atilde;o a pedir perd&atilde;o pelos rompantes de ira que constantemente os acometem. Quando isso acontece, ficam mais abertos a conselhos e &agrave;s opini&otilde;es alheias, desde que sejam coerentes. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Um dos maiores defeitos do filho de Ogum &eacute; o g&ecirc;nio dif&iacute;cil e impulsivo que acaba por ferir todos que o cercam. Em contrapartida, sua maior qualidade &eacute; que ser&atilde;o sempre vitoriosos em tudo o que fizerem, n&atilde;o importando qu&atilde;o dif&iacute;cil seja a miss&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sua impaci&ecirc;ncia &eacute; conhecida. Por este motivo toma decis&otilde;es precipitadas. &Eacute; pontual e fica enlouquecido quando algu&eacute;m atrasa em um compromisso, e fica doente se os desmarcarem em cima da hora, n&atilde;o importando qual seja o motivo. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Come&ccedil;a v&aacute;rias tarefas e certamente as terminar&aacute;. S&oacute; n&atilde;o sabe nem quando e nem como. Vive buscando o imposs&iacute;vel. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Adapta-se a qualquer coisa ou situa&ccedil;&atilde;o. Odeia injusti&ccedil;as e sempre se coloca em posi&ccedil;&atilde;o de proteger os mais fracos. Sabe mandar e ser mandado, desde que n&atilde;o seja desrespeitado. &Eacute; franco e direto ao ponto, na maioria das vezes sem nenhuma necessidade, o que constantemente lhe traz problemas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Ogum adoram armas e n&atilde;o &eacute; incomum comprarem armas de fogo, facas, espadas, etc. Odeiam a fraqueza e falta de garra, o que costumeiramente associam &agrave; falta de car&aacute;ter. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Outros Detalhes</span></span></strong></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sincretismo: S&atilde;o Jorge ou Santo Antonio; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Data de culto: 23 de Abril (S&atilde;o Jorge), 13 de Junho (Santo Antonio) </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o: Ogunh&ecirc; (Salve Ogum),Patakori (Salve aquele que tem a cabe&ccedil;a coroada); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Aacute;rea de atua&ccedil;&atilde;o: Caminhos, guerras, demandas e tecnologia; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Elemento: Fogo;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chacra: Umbilical; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Metal: Ferro (A&ccedil;o); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Astro regente: Marte; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dia da semana: Ter&ccedil;a-feira; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da guia: Vermelha, azul escuro(em algumas casas); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da vela: Vermelha;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pedra: Granada, rubi e s&aacute;rdio. L&aacute;pis-lazuli ou top&aacute;zio azul; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebida: Cerveja branca;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Amal&aacute;: Feijoada, inhame, car&aacute;, feij&atilde;o mulato ou fradinho, amendoim; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Frutas: Manga espada, banana, ameixa, ma&ccedil;&atilde;, uva ros&eacute;, laranja; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Flores: Cravo vermelho, crista de galo, palmas vermelhas;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas ervas: Peregum verde, espada de S&atilde;o Jorge, Lan&ccedil;a de S&atilde;o Jorge, Coroa de S&atilde;o Jorge, folhas de rom&atilde;, losna, alcachofra, jurubeba, abre-caminho, carqueja, pariet&aacute;ria;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local de oferta: Estradas, caminhos e estradas de ferro. O meio da encruzilhada pertence &agrave; Ogum;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Animais: Galo vermelho, cabrito malhado e cachorro; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Instrumentos: Espada, faca, lan&ccedil;a, escudo;</span></span></span></span></span></li>
</ul>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fontes: </span></span></span></span></span></p>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Marcio Kain, Curso de Teologia da Umbanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fl&aacute;vio Penteado, Povo de Aruanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ademir Jr, Teologia de Umbanda e suas dimens&otilde;es;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lurdes Vieira, Manual Doutrin&aacute;rio, Ritualistico e Comportamental Umbandista</span></span></span></span></span></li>

					</p>
					<a href="AUmbanda_OSORIXAS.php" class="btn btn-primary">&larr; Retornar aos Orixás</a>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 13/04/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>