<?php $results['pageTitle'] = "OS Anjos da Guarda | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
                           <img class="card-img-top" src="images/anjo5.jpg" alt="Card image cap">
				<h2 class="card-title"><center>O ANJO DA GUARDA</center></h2>
				<p class="card-text">
						
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Allan Kardec, no livro &quot;O C&eacute;u e o Inferno&quot;, existe uma descri&ccedil;&atilde;o baseada na doutrina cat&oacute;lica: <em>&ldquo;Os Anjos s&atilde;o seres puramente espirituais, anteriores e superiores a Humanidade, criaturas privilegiadas e voltadas a felicidade suprema e eterna desde a sua forma&ccedil;&atilde;o, dotadas, por sua pr&oacute;pria natureza, de todas as virtudes e conhecimentos, nada tendo feito, ali&aacute;s, para adquiri-los. Est&atilde;o, por assim dizer, no primeiro plano de Cria&ccedil;&atilde;o, contrastando com o &uacute;ltimo onde a vida &eacute; puramente material; e, entre o dois, medianamente existe a Humanidade, isto &eacute;, as almas, seres inferiores aos Anjos e ligados a corpos materiais&rdquo;</em>.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Kardec ainda relata, no mesmo livro, um entendimento um pouco mais abrangente, segundo a Doutrina Esp&iacute;rita: <em>&ldquo;Que haja seres dotados de todas as qualidades atribu&iacute;das aos Anjos, n&atilde;o restam d&uacute;vidas. A revela&ccedil;&atilde;o esp&iacute;rita neste ponto confirma a cren&ccedil;a de todos os povos, fazendo-nos conhecer ao mesmo tempo a origem e natureza de tais seres&rdquo;</em>. At&eacute; este ponto, percebe-se a concord&acirc;ncia com a vis&atilde;o cat&oacute;lica dos Anjos. A diferen&ccedil;a est&aacute; no fato de que, conforme o ensinamento dos Esp&iacute;ritos, todos os seres possuem uma &ldquo;centelha divina&rdquo;, a ess&ecirc;ncia do pr&oacute;prio Criador em cada um de n&oacute;s. Portanto ningu&eacute;m &eacute; privilegiado na Cria&ccedil;&atilde;o. Todos ter&atilde;o que trilhar o caminho da evolu&ccedil;&atilde;o espiritual a fim de manifestarem o potencial divino de cada um. Kardec diz ainda que: <em>&ldquo;As almas ou Esp&iacute;ritos s&atilde;o criados simples e ignorantes. Isto &eacute;, sem conhecimento e nem consci&ecirc;ncia do que &eacute; o bem e o mal, por&eacute;m, aptos para adquirir o que lhes falta. O trabalho &eacute; o meio de aquisi&ccedil;&atilde;o, e o fim &ndash; que &eacute; a perfei&ccedil;&atilde;o &ndash; &eacute; para todos, o mesmo. Conseguem-no mais ou menos prontamente em virtude do livre-arb&iacute;trio e na raz&atilde;o direta dos seus esfor&ccedil;os; todos t&ecirc;m os mesmos degraus a franquear, o mesmo trabalho a concluir (...). Deste modo, pouco a pouco, se desenvolve, aperfei&ccedil;oa e adianta na hierarquia espiritual at&eacute; ao estado de puro Esp&iacute;rito ou Anjo. Os Anjos s&atilde;o, pois, as almas dos homens chegados ao grau de perfei&ccedil;&atilde;o que a criatura comporta, fruindo em sua plenitude a prometida felicidade. Antes, por&eacute;m, de atingir o grau supremo, gozam de felicidade relativa ao seu adiantamento, felicidade que consiste, n&atilde;o na ociosidade, mas nas fun&ccedil;&otilde;es que a Deus apraz confiar-lhes, e por cujo desempenho se sentem ditosas, tendo ainda nele um meio de progresso&rdquo;.</em> </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Entre os Anjos (ou Esp&iacute;ritos puros), existem aqueles que participam de tarefas grandiosas, como o planejamento e coordena&ccedil;&atilde;o dos mundos, at&eacute; aqueles mais pr&oacute;ximos da nossa condi&ccedil;&atilde;o espiritual. Logo, todos os Esp&iacute;ritos chegar&atilde;o ao est&aacute;gio evolutivo de Anjo, inclusive aqueles mais cru&eacute;is. Ainda que percorram mil&ecirc;nios e incont&aacute;veis encarna&ccedil;&otilde;es, a evolu&ccedil;&atilde;o &eacute; inevit&aacute;vel.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Diante das dificuldades inerentes &agrave; jornada evolutiva, o Anjo da Guarda normalmente auxilia os encarnados. Ele &eacute; um Esp&iacute;rito que possui algum tipo de la&ccedil;o afetivo com a pessoa que ele ajuda; esses la&ccedil;os s&atilde;o muito antigos, de encarna&ccedil;&otilde;es passadas e por ter um grau elevado de equil&iacute;brio espiritual, recebe a dif&iacute;cil miss&atilde;o de orientar os seres humanos. Os Anjos da Guarda n&atilde;o s&atilde;o &quot;bab&aacute;s&quot;, ou seja, n&atilde;o fazem as atribui&ccedil;&otilde;es do protegido, mas podem atuar sobre o Esp&iacute;rito do mesmo intuindo sobre suas obriga&ccedil;&otilde;es. O trabalho de prote&ccedil;&atilde;o espiritual tem um tempo limitado e &eacute; muito mais intenso na fase infantil da pessoa encarnada, mas isso n&atilde;o quer dizer que quando esse tempo terminar, o encarnado n&atilde;o ter&aacute; mais um Anjo da Guarda, </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Um Esp&iacute;rito protetor tem como miss&atilde;o a tarefa semelhante a de um pai, guiar o seu protegido pela senda do bem, auxili&aacute;-lo com seus conselhos, consol&aacute;-lo nas suas afli&ccedil;&otilde;es, levantar-lhe o &acirc;nimo nas provas da vida. Ficam ligados desde o nascimento at&eacute; a passagem de plano do protegido, muitas vezes inclusive, o acompanha na vida espiritual, ap&oacute;s seu desencarne, e mesmo atrav&eacute;s de muitas exist&ecirc;ncias corp&oacute;reas, que s&atilde;o fases curt&iacute;ssimas da vida do Esp&iacute;rito. &Eacute; importante que se diga que estes Esp&iacute;ritos n&atilde;o s&atilde;o exclusivos protetores de apenas um encarnado.</span></span></span></span></p>
<img src="images/anjo1.png" style="padding: 0 15px;float:left; width:250px;height: 200px;"></img>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Esp&iacute;rito protetor ou Anjo da Guarda pode afastar-se de seu protegido quando este v&ecirc; que seus conselhos s&atilde;o in&uacute;teis e que as influ&ecirc;ncias dos Esp&iacute;ritos inferiores s&atilde;o mais fortes em seu protegido. Por&eacute;m, n&atilde;o o abandona e sempre se faz ouvir. &Eacute; ent&atilde;o o homem quem tapa os ouvidos. O protetor volta desde que este o chame. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A seguinte passagem aparece no livro dos Esp&iacute;tiros, Cap&iacute;tulo IX, <em>&ldquo;N&atilde;o vos parece grandemente consoladora a ideia de terdes sempre junto de v&oacute;s seres que vos s&atilde;o superiores, prontos sempre a vos aconselhar e amparar, a vos ajudar na ascens&atilde;o da abrupta montanha do bem; mais sinceros e dedicados amigos do que todos os que mais intimamente se vos liguem na Terra? Eles se acham ao vosso lado por ordem de Deus. Foi Deus quem ai os colocou e, a&iacute; permanecendo por amor de Deus, desempenham bela, por&eacute;m penosa miss&atilde;o. Sim, onde quer que estejais, estar&atilde;o convosco. Nem nos c&aacute;rceres, nem nos hospitais, nem nos lugares de devassid&atilde;o, nem na solid&atilde;o, estais separados desses amigos a quem n&atilde;o podeis ver, mas cujo brando influxo vossa alma sente, ao mesmo tempo que lhes ouve os ponderados conselhos.&rdquo;</em></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">De maneira sucinta, Anjo da Guarda &eacute; um Esp&iacute;rito protetor, pertencente a uma ordem elevada.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No Livro &quot;Entre a Terra e o C&eacute;u&quot; de Andr&eacute; Luiz, ele define o Anjo da Guarda como embaixadores de Deus, mantendo acesa a chama da f&eacute; nos cora&ccedil;&otilde;es e auxiliando os enfraquecidos na luta terrestre. Quais estrelas formosas, que iluminam as noites das almas e atendem-lhes as necessidades com un&ccedil;&atilde;o e devotamento inigual&aacute;veis. Perseveram ao lado dos seus tutelados em toda circunst&acirc;ncia, jamais se impacientando ou os abandonando, mesmo quando eles, em desequil&iacute;brio, vociferam e atiram-se aos despenhadeiros da alucina&ccedil;&atilde;o. S&atilde;o s&aacute;bios e evolu&iacute;dos, encontrando-se em perfeita sintonia com o pensamento divino, que buscam transmitir, de modo que as criaturas se integrem psiquicamente na harmonia geral que vige no Cosmo.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Anjos da Guarda s&atilde;o li&ccedil;&otilde;es vivas de amor, que nunca se cansam, porquanto aplicam mil&ecirc;nios do tempo terrestre auxiliando aqueles que lhes s&atilde;o confiados. Os anjos t&ecirc;m defini&ccedil;&otilde;es claras de fun&ccedil;&otilde;es, neste caso o &ldquo;da-guarda&rdquo; significa que eles devem guardar nossas almas imortais, at&eacute; que cheguemos a perfei&ccedil;&atilde;o. Isso n&atilde;o implica em nos cercear a liberdade ou impedir que possamos evoluir por meio da prova&ccedil;&atilde;o. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Umbanda aceita a explica&ccedil;&atilde;o dada pelo Espiritismo para os que seriam os Anjos da Guarda, como Esp&iacute;ritos protetores e Esp&iacute;ritos familiares, ligados por amor a n&oacute;s, e nos acompanhando sempre. Isso &eacute; verdade. Mas, a Umbanda vai al&eacute;m. Al&eacute;m da presen&ccedil;a de um Anjo da Guarda, existe ainda a presen&ccedil;a dos Mentores e dos Guardi&otilde;es, os dois &uacute;ltimos orientam e protegem o ser humano na encarna&ccedil;&atilde;o vigente. Os Mentores e Guardi&otilde;es s&atilde;o importantes para a sobreviv&ecirc;ncia f&iacute;sica no planeta.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Anjos da Guarda t&ecirc;m uma fun&ccedil;&atilde;o muito parecida com dos mentores espirituais tamb&eacute;m, quando se analisa isso de uma maneira muito pr&oacute;xima e simplista. O Mentor Espiritual tem uma fun&ccedil;&atilde;o para com o encarnado de uma ou algumas encarna&ccedil;&otilde;es, mas nem sempre esteve com o protegido desde o momento da cria&ccedil;&atilde;o do Esp&iacute;rito Imortal. Pode ser que esse mentor, que &eacute; uma entidade humana, ou seja, fora um esp&iacute;rito humano, tenha sido criado ao mesmo momento que o encarnado, por&eacute;m evoluiu de maneira mais c&eacute;lere, o que lhe possibilitou tomar a mentoria da pr&oacute;xima encarna&ccedil;&atilde;o do outro esp&iacute;rito, para si.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">J&aacute; no caso dos Anjos da Guarda, al&eacute;m de sua natureza atemporal (diferente dos esp&iacute;ritos humanos que s&atilde;o temporais) eles j&aacute; estavam conosco desde a primeira respira&ccedil;&atilde;o astral e estar&aacute; at&eacute; a &uacute;ltima no fim dos tempos. Desta forma fica claro que o mentor espiritual poder&aacute; e ir&aacute; mudar conforme o passar das encarna&ccedil;&otilde;es, mas o anjo-da-guarda sempre ser&aacute; o mesmo.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na Umbanda, os m&eacute;diuns firmam uma vela com um copo de &aacute;gua para o Anjo da Guarda, mas o anjo n&atilde;o necessita de velas, &aacute;gua, etc., para se fazer presente na vida dos m&eacute;diuns. A vela &eacute; firmada para &ldquo;iluminar o Esp&iacute;rito do encarnado&rdquo;. Os elementos usados para &ldquo;firmar o Anjo da Guarda&rdquo; s&atilde;o elementos da Natureza (a vela representa a terra; a chama da vela representa o fogo; o copo com &aacute;gua representa a &aacute;gua; o ar que alimenta o fogo representa o ar), adequadamente vibrados, que ir&atilde;o fazer a devida liga&ccedil;&atilde;o, plasmando essas for&ccedil;as nos corpos &aacute;urico, duplo et&eacute;rico e corpo f&iacute;sico, dos m&eacute;diuns, para a prote&ccedil;&atilde;o, o aux&iacute;lio e o amparo dos mesmos. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">H&aacute; um outro momento em que o Anjo da Guarda se afasta um pouco, esse momento &eacute; quando o m&eacute;dium vai incorporar, para que a Entidade se aproxime, o anjo de guarda permite a passagem para ocorrer a incorpora&ccedil;&atilde;o. Quando a Entidade est&aacute; incorporada no m&eacute;dium, o anjo da guarda permanece ao lado, pois o m&eacute;dium est&aacute; protegido por energias da Entidade que est&aacute; ali.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Quando h&aacute; o processo de desincorpora&ccedil;&atilde;o, o Anjo da Guarda se aproxima mais, para manter o equil&iacute;brio do m&eacute;dium. Assim, os m&eacute;diuns devem ficar atentos para n&atilde;o oferecer resist&ecirc;ncia na hora da desincorpora&ccedil;&atilde;o dessa Entidade, pois existe uma hora certa em que a Entidade deve deixar a mat&eacute;ria e o anjo da guarda se aproximar, n&atilde;o deixando a mat&eacute;ria desprotegida.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>
<img src="images/anjo2.jpg" style="padding: 0 15px;float:right; width:250px;height: 200px;"></img>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&ldquo;SEU ANJO DA GUARDA TE CHAMA&rdquo;</span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O anjo da guarda &eacute; particularmente importante no momento da desincorpora&ccedil;&atilde;o. Quando o m&eacute;dium oferece resist&ecirc;ncia no momento da desincorpora&ccedil;&atilde;o, isso &eacute; prejudicial a ele, pois ele perde a prote&ccedil;&atilde;o celestial. &Eacute; comum ocorrer um sutil estado de transe logo ap&oacute;s a desincorpora&ccedil;&atilde;o, e nesse momento as pessoas que acompanham o m&eacute;dium colocam a m&atilde;o no cora&ccedil;&atilde;o dele e dizem: &ldquo;Seu anjo da guarda te chama! &rdquo;. Isso ajuda a acalmar e facilitar o processo de desincorpora&ccedil;&atilde;o de forma mais tranquila. Os anjos trazem o equil&iacute;brio perfeito de energia pura e divina ao m&eacute;dium para que ele consiga cumprir sua miss&atilde;o de mensageiro e canal espiritual.</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exemplo de uma prece para o Anjo da Guarda</span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Esp&iacute;ritos esclarecidos e benevolentes, mensageiros de Deus, que tendes por miss&atilde;o assistir os homens e conduzi-los pelo bom caminho, sustentai-me nas provas desta vida; dai-me a for&ccedil;a de suport&aacute;-la sem queixumes; livrai-me dos maus pensamentos e fazei que eu n&atilde;o d&ecirc; entrada a nenhum mau Esp&iacute;rito que queira induzir-me ao mal. Esclarecei a minha consci&ecirc;ncia com rela&ccedil;&atilde;o aos meus defeitos e tirai-me de sobre os olhos o v&eacute;u do orgulho, capaz de impedir que eu os perceba e os confesse a mim mesmo. </span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10px"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fontes:</span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10px"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">- O C&eacute;u e o Inferno, Allan Kardec</span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10px"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">- O Livro dos Esp&iacute;ritos, Allan Kardec</span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10px"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">- Entre a Terra e o C&eacute;u, Andr&eacute; Luiz</span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10px"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">- WeMestic</span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10px"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">- Sergio Oliveira</span></span></span></p>

					</p>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 24/03/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>