<?php $results['pageTitle'] = "Exu| Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
			<img class="card-img-top" src="images/exu.jpg" alt="Card image cap">
				<h2 class="card-title"><center>EXU</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Todos os Orix&aacute;s foram sincretizados pelo negro escravizado, com santos da igreja cat&oacute;lica, pois era essa a &uacute;nica religi&atilde;o aceita e obrigat&oacute;ria naquela &eacute;poca. Exu tamb&eacute;m foi associado a um santo, entretanto, quando o homem branco conheceu Exu, com sua gargalhada, com seu tridente, bebendo cacha&ccedil;a e fumando charuto, imediatamente associou com o diabo da cultura judaico-crist&atilde;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em 1822 a costa da &Aacute;frica ainda estava permeada de homens inescrupulosos, que ali compravam escravos para revend&ecirc;-los em grandes centros nas Am&eacute;ricas. Esses escravos vinham de povos do interior do continente e eram escravizados pelos pr&oacute;prios povos irm&atilde;os que, ap&oacute;s atacar as aldeias, trocavam os sobreviventes por armas com os brancos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Nesta data, um garoto de 13 anos chamado Ajayi foi capturado e, abordo de um navio negreiro, era levado para a Am&eacute;rica. Ocorre que a Inglaterra, nesta &eacute;poca, al&eacute;m de n&atilde;o mais fazer uso de escravos, coibia o tr&aacute;fico negreiro. E foi em uma abordagem inglesa que o navio que carregava Ajayi foi obrigado a retornar &agrave; costa e libertar todos os escravos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O garoto j&aacute; n&atilde;o possu&iacute;a fam&iacute;lia, nem amigos e nem sequer uma aldeia para onde pudesse retornar, sendo entregue, desta forma, aos cuidados da col&ocirc;nia de Serra Leoa, que era formada basicamente por religiosos crist&atilde;os europeus e ex-escravos repatriados. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na col&ocirc;nia, apesar da resist&ecirc;ncia, Ajayi foi lentamente se convertendo ao cristianismo, abra&ccedil;ando a religi&atilde;o do povo ingl&ecirc;s, o anglicanismo. Come&ccedil;a a&iacute; um grande passo para Ajayi, quando come&ccedil;a a receber aulas de ingl&ecirc;s, o que cumina com seu batismo em 1825, e, continuando os estudos, foi ordenado pastor em 1843, quando assume o nome de Samuel Crowther, em homenagem a um eminente cl&eacute;rigo daquela religi&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Como pastor, Crowther teve papel indiscut&iacute;vel na comunica&ccedil;&atilde;o dos religiosos com o povo ioruba, e, em face disso, publica o &ldquo;Vocabul&aacute;rio Iorub&aacute;&rdquo;, criando assim um dicion&aacute;rio de f&aacute;cil uso para os ingleses. O fato marcante &eacute; que at&eacute; este momento, o ioruba era uma l&iacute;ngua apenas falada, n&atilde;o existia gram&aacute;tica. Foi Ajayi Crowther quem criou a gram&aacute;tica e criou o primeiro livro de livre tradu&ccedil;&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Depois de muitas colabora&ccedil;&otilde;es como int&eacute;rprete, religioso e escritor, Crowther dedicou-se &agrave; primeira tradu&ccedil;&atilde;o da B&iacute;blia para o ioruba, fato conclu&iacute;do em meados de 1880. Ao traduzir a B&iacute;blia, Samuel Ajayi Crowther traduziu Deus como Olorun e o diabo como Exu. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Esta &eacute; a primeira constata&ccedil;&atilde;o hist&oacute;rica da deturpa&ccedil;&atilde;o da imagem de Exu pela cultura judaico-crist&atilde;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No Brasil, fora a gargalhada e o tridente, as cores vermelha e preta, associadas a este Orix&aacute;, ajudavam a confundi-lo com o dem&ocirc;nio. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">At&eacute; mesmo alguns escritores como Alu&iacute;zio Fontenelle, associou a figura de Exu com a dos dem&ocirc;nios do livro Go&eacute;cia em sua obra &ldquo;Exu&rdquo; de 1954, gerando ainda mais pol&ecirc;mica e confus&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Essa confus&atilde;o permaneceu e permanece na mente de muitos umbandistas at&eacute; hoje, e &eacute; por isso que o mist&eacute;rio Exu deve ser estudado e compreendido de forma adequada. Pois, sem este Orix&aacute;, nada podemos alcan&ccedil;ar na Umbanda. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Antes de qualquer coisa, &eacute; importante frisar que Exu n&atilde;o &eacute; o diabo, nem Satan&aacute;s, n&atilde;o faz nenhuma oposi&ccedil;&atilde;o a Deus. Para os crist&atilde;os, o mal &eacute; simbolizado por um &uacute;nico ser, que ap&oacute;s ser expulso do c&eacute;u, atormenta os seres humanos. &Eacute; conhecido como diabo, dem&ocirc;nio, satan&aacute;s, entre outros nomes populares. Para os africanos nenhum deus ou Orix&aacute; emanava qualquer tipo de mal, sendo o mal um atributo espec&iacute;fico dos seres encarnados. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Para a cultura africana, em linhas gerais, Exu &eacute; o mensageiro dos Orix&aacute;s. Existe outro ser espiritual que tamb&eacute;m recebe a mesma fun&ccedil;&atilde;o, mas, entre os ocidentais, ele &eacute; chamado de anjo, do grego &ldquo;angelus&rdquo;, o mensageiro. Assim sendo, se voc&ecirc; deseja associar a figura de Exu com outro ser encantado, que seja um anjo. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A palavra &ldquo;exu&rdquo; significa &ldquo;esfera&rdquo; em ioruba. Ele &eacute; o grande respons&aacute;vel pela comunica&ccedil;&atilde;o do Orun (c&eacute;u/plano espiritual) e o Ayi&ecirc; (terra/mundo material). Exu &eacute; quem leva nossos pedidos e clamores para os Orix&aacute;s e traz de volta suas respostas, criando uma rede de comunica&ccedil;&atilde;o simbolizada pela esfera. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu, dessa forma, &eacute; o grande Orix&aacute; mensageiro, da comunica&ccedil;&atilde;o e do movimento. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A vibra&ccedil;&atilde;o de Exu &eacute; indispens&aacute;vel para os seres humanos, pois sem ela o ser entra em desequil&iacute;brio, de forma que nenhuma comunica&ccedil;&atilde;o externa chega completa ou adequada, e nem mesmo suas express&otilde;es internas conseguem ser proferidas. O homem, sem Exu, fica completamente isolado da natureza divina. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; conhecido tamb&eacute;m como fiscal dos Orix&aacute;s, cabendo a ele identificar, quais ofertas ou obriga&ccedil;&otilde;es ser&atilde;o aceitas ou n&atilde;o, quais ser&atilde;o entregues aos Orix&aacute;s ou n&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Por todos estes motivos, &eacute; necess&aacute;rio entender que n&atilde;o existe nada na Umbanda que seja feito sem que Exu seja informado, louvado ou ofertado em primeiro lugar, pois, sem a a&ccedil;&atilde;o de Exu nada se movimenta. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">At&eacute; mesmo um simples pedido a qualquer Orix&aacute;, dever&aacute; ser feito a Exu primeiro ou, ao menos, sua atua&ccedil;&atilde;o dever&aacute; ser solicitada, para que ele encaminhe nossos pedidos ao seu destino. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; por este motivo tamb&eacute;m que se diz que todo Orix&aacute; tem um Exu correspondente, um elo de liga&ccedil;&atilde;o com o mundo terreno. Os Orix&aacute;s tamb&eacute;m sabem que nada conseguiriam fazer na Terra sem o trabalho de Exu. Por esta associa&ccedil;&atilde;o com os Orix&aacute;s, encontramos Exu em todos os dom&iacute;nios da natureza, mas as encruzilhadas e o cemit&eacute;rio s&atilde;o os mais populares. Muitos atribuem a Exu o r&oacute;tulo de escravo dos Orix&aacute;s. Ledo engano! </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu &eacute; um Orix&aacute; como qualquer outro, com fun&ccedil;&otilde;es e atribui&ccedil;&otilde;es bem definidas. Seu trabalho &eacute; regido por Olorun. Exu &eacute; movimento, o fogo crescente que inicia seu caminho. A evolu&ccedil;&atilde;o dos seres tamb&eacute;m pode ser atribu&iacute;da a Exu, pois sem ele nenhum movimento &eacute; poss&iacute;vel, nem mesmo os movimentos evolutivos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Por ser Exu que traz as determina&ccedil;&otilde;es dos Orix&aacute;s para a Terra, tamb&eacute;m &eacute; entregue a ele o t&iacute;tulo de &ldquo;Senhor do Destino&rdquo;, pois, independente da resolu&ccedil;&atilde;o dos Orix&aacute;s ser boa ou ruim, &eacute; Exu que se encarregar&aacute; de concretiz&aacute;-la. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu compreende que n&atilde;o importa quem fa&ccedil;a, tem que ser feito. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A Exu tamb&eacute;m pertence todo fluxo de energia. Tanto a aflu&ecirc;ncia (de onde a energia parte) como a conflu&ecirc;ncia (onde as energias se encontram). Por isso portas, porteiras, port&otilde;es, passagens, caminhos e encruzilhadas, tamb&eacute;m s&atilde;o atribu&iacute;dos a ele. O ax&eacute; tamb&eacute;m &eacute; sua propriedade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Antigamente n&atilde;o era incomum se dizer que em terreiro que n&atilde;o se tem Exu assentado, n&atilde;o se sente o ax&eacute;. A energia de Exu pode construir ou destruir. Quando destr&oacute;i n&atilde;o &eacute; por f&uacute;ria e sim por necessidade de modifica&ccedil;&atilde;o. &Eacute; a forma que Exu tem para nos dizer que estamos no caminho errado, que &eacute; melhor recome&ccedil;ar. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; conhecido por ser grande adepto dos prazeres da vida. Exu gosta de comer, beber, dan&ccedil;ar, rir e fazer amor. Mas, exagero e vulgaridade n&atilde;o fazem parte de seu comportamento. Tudo com muito bom gosto, tudo com muito charme. Sempre muito alegre, animado, inteligente e vivo. A ast&uacute;cia &eacute; uma de suas principais qualidades. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A ele pertence o caminho dos bons e dos maus costumes, independente de serem estes costumes antigos ou novos. Exu tamb&eacute;m est&aacute; em nossas sombras internas. O defeito, o v&iacute;cio, aquela por&ccedil;&atilde;o de n&oacute;s mesmos que menos gostamos. A sombra s&oacute; existe onde h&aacute; luz. Esta luz &eacute; Exu, que aceita e compreende nossos defeitos, mas tamb&eacute;m trabalha para melhor&aacute;-los. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A seguran&ccedil;a do terreiro e a boa abertura dos trabalhos tamb&eacute;m cabem a Exu, desde que devidamente ofertado. Sua energia &eacute; densa, pesada. Pode modular a polaridade tanto para positiva como negativa, como bem entender. Por este motivo o descarrego de Exu &eacute; o mais profundo dentro da Umbanda. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu pode trabalhar em qualquer frente: neg&oacute;cios, cura, amor, orienta&ccedil;&atilde;o. Podemos solicitar seu aux&iacute;lio em qualquer momento. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Orix&aacute; Exu tem como falangeiros Exu e Pombagira. N&atilde;o confundir o Orix&aacute; com seus tarefeiros. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O termo Pombagira tem origem em Angola. Pambu Njila era como os angolanos chamavam a sua vers&atilde;o do Exu ioruba. &ldquo;Mpambu&rdquo; em kikongo significa &ldquo;encruzilhadas&rdquo; e &ldquo;Njila&rdquo;, &ldquo;caminho&rdquo;. Pambu Njila &eacute; o senhor dos caminhos, das encruzilhadas e dos come&ccedil;os. Muitos dizem que foi atrav&eacute;s desta vers&atilde;o que Exu ficou conhecido como senhor das encruzilhadas. Tamb&eacute;m conhecido como Legba (o poder) e Elegbara (senhor do poder). </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na &Aacute;frica era comum encontrar em &aacute;rvores pr&oacute;ximas &agrave;s entradas das aldeias, falos eretos (um dos s&iacute;mbolos de Exu) enormes nelas gravados. Isso simbolizava a prote&ccedil;&atilde;o de Exu, e mesmo hoje ele ainda &eacute; cultuado como grande guardi&atilde;o das cidades. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu, para um esp&iacute;rito em evolu&ccedil;&atilde;o, &eacute; um t&iacute;tulo que dever&aacute; ser conquistado atrav&eacute;s do tempo, do trabalho e do merecimento de cada entidade. Uma pessoa por se vestir como um policial, n&atilde;o se torna um; nem quem veste um guardap&oacute; se torna m&eacute;dico. Um esp&iacute;rito, apenas por se dizer Exu, n&atilde;o significa que o seja. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Todos j&aacute; tivemos oportunidades de ouvir nos terreiros esp&iacute;ritos obsessores que se dizerem Caveira, Tranca-Ruas ou Maria Padilha. Esses nomes de falanges s&atilde;o t&iacute;tulos e jamais ser&atilde;o utilizados de forma inadequada por qualquer esp&iacute;rito, e nem se dar&atilde;o a trabalhos negativos ou obsessivos. Precisa-se entender os mecanismos para dissipar d&uacute;vidas que surgem dentro dos terreiros. Exu &eacute; uma linda patente do plano espiritual. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">As imagens de Exu s&atilde;o outro ponto que deve ser mudado. Exu n&atilde;o tem rabo, nem chifre e nem p&eacute;s de bode. Mais uma vez a mente dos homens, deturpada pela cultura crist&atilde;, deturpa o verdadeiro conceito do Orix&aacute;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu pode usar terno, capa, cartola, bengala. Pode usar uniforme ou a vestimenta dos cavaleiros, ou guerreiros do passado, mas tenha certeza de que nada lembrar&aacute; um dem&ocirc;nio. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu &eacute; limpo, correto e certeiro. Exu n&atilde;o bebe demais e, caso o fa&ccedil;a, tenha certeza de que tem um motivo, e de que ele levar&aacute; embora todo o &aacute;lcool de seu aparelho. Quando o m&eacute;dium fica b&ecirc;bado, tenha certeza de que Exu nada tem a ver com o fato. Isso &eacute; coisa de m&eacute;dium desorientado ou sem preparo. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu Orix&aacute; tamb&eacute;m est&aacute; ligado &agrave; conten&ccedil;&atilde;o de entidades negativas, impedindo seu fluxo de energia. Por este motivo, muitos tarefeiros de Exu (Exu e Pombagira) trabalham em zonas trevosas ou pouco iluminadas. Esses esp&iacute;ritos, quando se manifestam no terreiro, podem inicialmente ter comportamento arredio ou violento. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Associo estas entidades a agentes penitenci&aacute;rios que n&atilde;o podem deixar seu local de trabalho. Passando muito tempo no pres&iacute;dio, o agente acaba por adquirir algumas posturas mais pesadas por puro senso de sobreviv&ecirc;ncia. Estar pr&oacute;ximo e ter que controlar criminosos e malfeitores o tempo todo, pode afetar seu psique. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Mas os trabalhadores de Exu s&atilde;o humildes o suficiente para cumprir suas tarefas da forma que for e onde quer que seja, sem titubear e sem deixar o posto. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Infelizmente ainda existem terreiros de Umbanda que n&atilde;o trabalham com a linha de Exu e nem sequer consideram-no um Orix&aacute;. Uma pena. Pois &eacute; Exu que d&aacute; descarrego e equil&iacute;brio na vida de um m&eacute;dium. Sem Exu a seguran&ccedil;a de um terreiro pode ser inst&aacute;vel. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Para entender um pouco mais Exu, vejamos as sauda&ccedil;&otilde;es que dedicamos a ele nos trabalhos de Umbanda: </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Laroy&ecirc; (Laru&ecirc;) - significa o bem-falante, o comunicador. Adapta-se esta tradu&ccedil;&atilde;o por &ldquo;mensageiro&rdquo;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Exu Mojub&aacute; - Mo Jub&aacute; em ioruba significa &ldquo;eu me curvo&rdquo;, Curvo-me a ti Exu. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ina Ina Mojub&aacute; - In&aacute; em ioruba significa fogo ou fogo que resplandece a luz. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Eu me curvo ao fogo que resplandece a luz.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Por tudo isso devemos amar e respeitar Exu como o grande Orix&aacute; que &eacute;, tendo plena consci&ecirc;ncia de sua bondade e de sua necessidade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em uma das mais c&eacute;lebres e felizes frases de Rubens Saraceni, ele diz: </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&ldquo;Exu &eacute; m&atilde;o esquerda de Deus&rdquo;.</span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Caracter&iacute;sticas de Exu e seus filhos </span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Seus filhos tem personalidade marcante. Corajosos e dedicados. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o fi&eacute;is aos seus princ&iacute;pios, aos amigos e &agrave; fam&iacute;lia. N&atilde;o medem esfor&ccedil;os para ajudar aqueles que amam. S&atilde;o dados ao com&eacute;rcio, mas se dar&atilde;o bem em qualquer profiss&atilde;o pois s&atilde;o r&aacute;pidos e astutos. Dedicam-se com muito ardor at&eacute; alcan&ccedil;ar suas metas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Podem ter alguma marca no corpo que se destaque. S&atilde;o emotivos e ciumentos. S&atilde;o sonhadores e gostam de liberdade. Podem ter vida curta, mas muito agitada. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Gostam de todos os prazeres mundanos. Se beberem demais, podem ser violentos, desordeiros, provocativos, insolentes e atrevidos. N&atilde;o gostam de ficar sozinhos, adoram ser o centro das aten&ccedil;&otilde;es e de chamar a aten&ccedil;&atilde;o. Gostam de situa&ccedil;&otilde;es embara&ccedil;osas. Mudam de opini&atilde;o constantemente. Gostam de fracos e doentes, gostam de ajudar aqueles que precisam. N&atilde;o se amedrontam com doen&ccedil;as e nem com situa&ccedil;&otilde;es dif&iacute;ceis. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Temperamento impulsivo e explosivo. S&atilde;o vanguardistas, enxergam longe e est&atilde;o sempre &agrave; frente. Amoroso, radical, gosta de surpresas. &Eacute; apaixonado pelo sexo oposto. Tem tend&ecirc;ncia forte &agrave; infidelidade, mas est&atilde;o sempre amarrados a uma s&oacute; pessoa. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O filho de Exu tem enorme poder de sedu&ccedil;&atilde;o e poder&aacute; estar com v&aacute;rias mulheres ao mesmo tempo. Jamais se afasta de mulheres que o satisfizeram sexualmente. A filha de Exu tamb&eacute;m carrega muita sensualidade, mas n&atilde;o a deixa transparecer facilmente. Pelo contr&aacute;rio, tentar&aacute; escond&ecirc;-la atrav&eacute;s de uma imagem bastante reservada. S&oacute; mostrar&aacute; esse lado ao parceiro com quem se sentir segura, que a compreenda e que seja seu c&uacute;mplice. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Mas todos, de uma forma geral, s&atilde;o Fortes, capazes, rom&acirc;nticos, felizes, participativos, francos, espertos, inquietos, saud&aacute;veis, despachados e sagazes.</span></span></span></span></span></p>

<ul>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black">&nbsp;<span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Outros Detalhes</span></span></strong></span></span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sincretismo: Santo Antonio;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Data de culto: 13 de junho;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o: Laroy&ecirc;, Exu &eacute; Mojub&aacute;; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Aacute;rea de atua&ccedil;&atilde;o: Todas;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Elemento: Fogo; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chacra: B&aacute;sico e Sacro; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Metal: Ferro; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Astro regente: Merc&uacute;rio e Terra; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dia da semana: Segunda-feira (muitas casas aceitam tamb&eacute;m a sexta-feira); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da guia: Preta, vermelha ou vermelha e preta; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da vela: Preta, vermelha ou vermelha e preta;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pedra: &Ocirc;nix;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebida: Aguardente (marafo), conhaque e whisky; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Amal&aacute;: Pad&ecirc; (farofa feita com mi&uacute;dos, dend&ecirc; e bastante pimenta); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Frutas: Lim&atilde;o e lima; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Flores: Cravos vermelhos (Exu), rosa vermelha (Pombagira); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas ervas: Pimenta, capim tiririca, urtiga, mamona, arruda e cana; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local de oferta: Encruzilhadas e cemit&eacute;rios; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Animais: Cachorro e galinha preta; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Instrumentos: Tridente e Og&oacute; (bast&atilde;o em forma de falo);</span></span></span></span></span></li>
</ul>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fontes: </span></span></span></span></span></p>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Marcio Kain, Curso de Teologia da Umbanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fl&aacute;vio Penteado, Povo de Aruanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ademir Jr, Teologia de Umbanda e suas dimens&otilde;es;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lurdes Vieira, Manual Doutrin&aacute;rio, Ritualistico e Comportamental Umbandista</span></span></span></span></span></li>

					</p>
					<a href="AUmbanda_OSORIXAS.php" class="btn btn-primary">&larr; Retornar aos Orixás</a>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 14/04/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>