<?php $results['pageTitle'] = "As Linhas Principais | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
				<h2 class="card-title"><center>AS LINHAS PRINCIPAIS</center></h2>
                                <img src="images/caboclos.jpg" class="card-img-top"></img>	
				
                         <p class="card-text">
			
		
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Segundo o dicion&aacute;rio Aur&eacute;lio, caboclo &eacute; a designa&ccedil;&atilde;o dada, no Brasil, para o indiv&iacute;duo que foi gerado a partir da miscigena&ccedil;&atilde;o do &iacute;ndio nativo com o europeu branco. &Eacute; uma antiga denomina&ccedil;&atilde;o do ind&iacute;gena brasileiro. A palavra tamb&eacute;m &eacute; usada por vezes como adjetivo de uma pessoa desconfiada ou de um matuto. O caboclo &eacute; a representa&ccedil;&atilde;o do ind&iacute;gena brasileiro, de pele acobreada e cabelos lisos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na Umbanda, o caboclo est&aacute; associado a todos os &iacute;ndios, &agrave; for&ccedil;a, &agrave; dire&ccedil;&atilde;o, ao destemor, ao conhecimento das ci&ecirc;ncias da natureza, &agrave; capacidade de subjugar o mal. S&atilde;o nativos da terra que viviam nas matas, donde tiravam seu sustento e manipulavam suas ervas para fins medicinais e de cura. S&atilde;o excelentes curandeiros e ca&ccedil;adores. Ligados, dessas maneiras, &agrave; natureza, estes Guias Espirituais, com trejeitos rudes e gritos de guerra, amedrontam as entidades do baixo astral, descarregando seus m&eacute;diuns e limpando sua aura.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Eles representam o homem na idade adulta, em pleno vigor f&iacute;sico, com plenas condi&ccedil;&otilde;es de alcan&ccedil;ar todos os seus objetivos, sendo que nenhum obst&aacute;culo ser&aacute; grande ou forte o suficiente para det&ecirc;-lo. S&atilde;o excepcionais em trabalhos de prosperidade, abrindo caminhos e, em seus passes magn&eacute;ticos, envolvem o consulente em energias de alt&iacute;ssima vibra&ccedil;&atilde;o positiva, despertando na pessoa o conhecimento e a disposi&ccedil;&atilde;o necess&aacute;ria para alcan&ccedil;ar a sua sobreviv&ecirc;ncia.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Caboclos s&atilde;o regidos pelo Orix&aacute; Ox&oacute;ssi, mas podem trabalhar nas for&ccedil;as de qualquer Orix&aacute;. Neste caso, s&atilde;o &agrave;s vezes chamados de Caboclos Cruzados.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em seus trabalhos, usam folhas, ervas, ess&ecirc;ncias e flores. Aceitam frutas como agrado, que podem ser consumidas pelo m&eacute;dium incorporado. Tamb&eacute;m bebem cerveja branca ou preta, &aacute;gua, suco de frutas, &aacute;gua de coco, vinho tinto, com ou sem mel. Fazem uso de fumo, na forma de charutos, cigarros de palha e cachimbos.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Podem solicitar a seus m&eacute;diuns adere&ccedil;os t&iacute;picos como penachos, bra&ccedil;adeiras, arcos e flechas, entre outros objetos. Sua cor &eacute; o verde e seu dom&iacute;nio s&atilde;o as matas ou o dom&iacute;nio dos outros Orix&aacute;s, quando forem cruzados.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A sauda&ccedil;&atilde;o &eacute;: Ok&ecirc; Caboclo!</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<img src="images/adorei.jpg" class="card-img-top"></img>

<br></br> 

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Preto-Velho &eacute; o s&iacute;mbolo da humildade, da for&ccedil;a de vontade, da resigna&ccedil;&atilde;o, da sabedoria, do amor e da caridade. Os Pretos-Velhos s&atilde;o refer&ecirc;ncia para todos aqueles que necessitam de cura, de ensinamento e de orienta&ccedil;&atilde;o. Eles educam pessoas e esp&iacute;ritos sem luz. N&atilde;o t&ecirc;m raiva ou &oacute;dio pelas humilha&ccedil;&otilde;es, atrocidades e torturas a que foram submetidos em vidas passadas. Com seus cachimbos, fala pausada e tranquilidade nos gestos, eles escutam e ajudam aqueles que necessitam, independentemente de sua cor, idade, sexo e religi&atilde;o.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o extremamente pacientes com os seus filhos e, como poucos, sabem incutir-lhes os conceitos de carma e ensinar-lhes resigna&ccedil;&atilde;o. N&atilde;o se pode afirmar que todos os esp&iacute;ritos dessa linha foram escravos e correspondam aos mesmos Pretos-Velhos das senzalas, anci&atilde;os s&aacute;bios que costumavam ser consultados pelos negros mais jovens na &eacute;poca da escravid&atilde;o.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Al&eacute;m disso, no processo c&iacute;clico da reencarna&ccedil;&atilde;o, passaram por muitas vidas anteriores e podem mesmo ter reencarnado ap&oacute;s a vida de escravo. Foram negros escravos, ju&iacute;zes, fazendeiros, comerciantes, fil&oacute;sofos, m&eacute;dicos, ricos, pobres, iluminados ou n&atilde;o. Outros, nem negros foram. Alguns j&aacute; atuaram na luz na forma de Exus. Por&eacute;m, independente de suas outras experi&ecirc;ncias carnais, com a finalidade de oferecer ajuda &agrave;queles que necessitam, optaram ou foram escolhidos para atuar na forma incorporada de Preto-Velho.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Podem mesmo ter sido Exus que evolu&iacute;ram e tomaram as formas de um Preto-Velho? Sim. Este fato pode deixar algumas pessoas, umbandistas e n&atilde;o umbandistas, surpresas e confusas. Trata-se, simplesmente, de evolu&ccedil;&atilde;o e especializa&ccedil;&atilde;o dos esp&iacute;ritos.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Esses esp&iacute;ritos assumem a forma do Preto-Velho de forma a manter uma melhor comunica&ccedil;&atilde;o com aqueles que os vem em busca de ajuda. O Esp&iacute;rito de Luz com este grau de evolu&ccedil;&atilde;o tem a capacidade de assumir diversas formas, pois ele &eacute; energia viva, condutor de luz. A forma &eacute; apenas mais uma ferramenta para o que quer que eles tenham que fazer na terra.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Esses esp&iacute;ritos podem se apresentar em alguns lugares, por exemplo, como um m&eacute;dico e, em outros, como um Preto-Velho ou at&eacute; mesmo um Caboclo ou Exu. Tudo isso vai de acordo com o seu trabalho, sua miss&atilde;o, pois s&atilde;o muito capazes e vers&aacute;teis.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">N&atilde;o se trata de dissimula&ccedil;&atilde;o ou de uma forma de enganar ou manipular os encarnados. Muito pelo contr&aacute;rio, para aqueles mais esclarecidos, dispostos a conhecer seus mist&eacute;rios com maior profundidade, e que possuam merecimento para tal, eles podem at&eacute; mesmo compartilhar mais detalhes das suas identidades e das suas outras frentes de trabalho.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Por isso, quando for falar com um Preto-Velho, tenha humildade e respeito, pois s&atilde;o seres muito elevados e amorosos. Saiba escutar, antes de tudo. N&atilde;o queira milagres ou solu&ccedil;&otilde;es m&aacute;gicas para seus problemas. Entenda que qualquer solu&ccedil;&atilde;o come&ccedil;a dentro de voc&ecirc; mesmo. Tenha f&eacute;, acredite em voc&ecirc;, tenha amor a Deus e a voc&ecirc; mesmo.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Para muitos, os Pretos-Velhos s&atilde;o conselheiros que esclarecem a vida e seus caminhos. Para outros, s&atilde;o psic&oacute;logos, amigos, confidentes e mentores espirituais. S&atilde;o os exorcistas que lutam e desfazem trabalhos, com suas mirongas, banhos de ervas, pontos de fogo, pontos riscados e outros, normalmente auxiliados pelos Exus. Tamb&eacute;m s&atilde;o fortes combatentes das for&ccedil;as negativas (o mal), esp&iacute;ritos obsessores e kiumbas (quiumbas).</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Pretos-Velhos s&atilde;o regidos, normalmente, pelo Orix&aacute; Obalua&ecirc;, mas tamb&eacute;m podem trabalhar nas for&ccedil;as de outros Orix&aacute;s.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Usam diversos materiais em seus trabalhos, incluindo folhas, ervas, &aacute;gua, sal grosso, e velas brancas e brancas e pretas. Podem beber caf&eacute;, normalmente ado&ccedil;ado com a&ccedil;&uacute;car, mel ou rapadura, vinho tinto ou cacha&ccedil;a com mel (&agrave;s vezes com outras ervas). Fazem uso de fumo, na forma de cachimbos ou cigarros de palha.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Podem utilizar utens&iacute;lios como len&ccedil;o de cabe&ccedil;a, chap&eacute;u de palha, tecido carij&oacute; (xadrez preto e branco), ros&aacute;rios (simples ou de l&aacute;grima de Cristo ou l&aacute;grima de Nossa Senhora) e aventais de cozinheira. Sua cor &eacute; o preto e branco, seu dia da semana &eacute; a segunda-feira. Os alimentos relacionados aos Pretos-Velhos s&atilde;o v&aacute;rios, mas os principais s&atilde;o a feijoada, o bolo de tapioca e o bolo de fub&aacute;.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A sauda&ccedil;&atilde;o &eacute;: Adorei as Almas!</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

<img src="images/eres.jpg" class="card-img-top"></img>	

<br></br>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Esses Esp&iacute;ritos que se identificam como crian&ccedil;as na Umbanda s&atilde;o, na sua maioria, seres encantados, isto &eacute;, nunca encarnaram. Alguns encarnaram somente uma vez. Assim, est&atilde;o mais ligados ao plano encantado da natureza do que ao natural humano e vibram em sintonia com certas for&ccedil;as espec&iacute;ficas na natureza. Por isso, alguns Er&ecirc;s s&atilde;o das cachoeiras, outros das praias, do mar, das pedreiras e das matas.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Costumam ser chamados tamb&eacute;m de &ldquo;Ibeijada&rdquo;, &ldquo;Ibejis&rdquo;, &ldquo;Er&ecirc;s&rdquo;, &ldquo;Cosminhos&rdquo; ou simplesmente crian&ccedil;as. Quando incorporadas, elas vibram, o tempo todo na energia encantada do reino a que est&atilde;o ligadas. Basta entrar na sua sintonia infantil, brincando e comendo doces, para que aconte&ccedil;ar toda uma limpeza espiritual completa. Muito temos a aprender com as Crian&ccedil;as na Umbanda como nas express&otilde;es populares:</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&ldquo;Se todos tivessem olhos de Crian&ccedil;as n&atilde;o haveria mais guerras&rdquo;;</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&ldquo;Se nos permitirmos ser mais crian&ccedil;as, em nosso dia-a-dia, seriamos muito mais alegres&rdquo;;</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&ldquo;A pureza das Crian&ccedil;as &eacute; cor em nossas vidas&rdquo;;</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&ldquo;O Reino dos C&eacute;us pertence &agrave;s Crian&ccedil;as, aos puros de cora&ccedil;&atilde;o&rdquo;; e</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&ldquo;Quando as Crian&ccedil;as est&atilde;o em terra tudo vira arco-&iacute;ris&rdquo;.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Muitos n&atilde;o conseguem ver a import&acirc;ncia dos trabalhos das Crian&ccedil;as e n&atilde;o percebem o quanto elas realizam apenas &ldquo;brincando&rdquo; e comendo doces.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os Er&ecirc;s s&atilde;o regidos pelo Orix&aacute; Ibeji (S&atilde;o Cosme, S&atilde;o Dami&atilde;o e Doum), mas tamb&eacute;m podem trabalhar nas for&ccedil;as de outros Orix&aacute;s.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Costumam usar bolos, doces, balas, bebidas n&atilde;o alco&oacute;licas (refrigerante de guaran&aacute; e suco de frutas) e brinquedos em seus trabalhos, al&eacute;m de velas de cor azul, cor-de-rosa e azul com cor-de-rosa. Podem beber refrigerantes ou sucos de frutas. Fazem uso de fumo, na forma de cachimbos ou cigarros de palha.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Podem utilizar utens&iacute;lios como bonecas, bolas, carrinhos e outros brinquedos, la&ccedil;os de fita, chupetas e ter&ccedil;os coloridos. Suas cores s&atilde;o o azul e o cor-de-rosa, seu dia da semana &eacute; a segunda-feira.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A sauda&ccedil;&atilde;o &eacute;: Uni Ibejada!</span></span></span></span></span></p>

					</p>
            </div>
            <div class="card-footer text-muted">
				06/01/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>