<?php $results['pageTitle'] = "Obaluaê | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
			<img class="card-img-top" src="images/obaluaeomulu.jpg" alt="Card image cap">
				<h2 class="card-title"><center>OBALUAÊ/OMULU</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tamb&eacute;m conhecido por Omulu, Xapan&atilde; e Babalu Ay&ecirc;. A forma gr&aacute;fica Abalua&ecirc; tamb&eacute;m &eacute; bastante comum. Entretanto, Omulu e Obalua&ecirc; s&atilde;o os mais utilizados. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O nome Obalua&ecirc; significa &ldquo;Senhor Dono da Terra&rdquo; e Omulu quer dizer &ldquo;Filho do Senhor&rdquo;. S&oacute; pelos nomes j&aacute; imaginamos o respeito que os africanos t&ecirc;m por este orix&aacute;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Filho de Oxal&aacute; com Nan&atilde;, foi abandonado por sua progenitora em uma gruta, pr&oacute;ximo ao mar, por ser manco, deformado e ter o corpo coberto de chagas. Foi adotado por Iemanj&aacute; que o criou como se fosse seu filho. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Assim como sua m&atilde;e, Obalua&ecirc; &eacute; um orix&aacute; origin&aacute;rio do Daom&eacute;. As divindades dessa regi&atilde;o africana s&atilde;o muito antigas. Nos cultos de Obalua&ecirc; e Nan&atilde;, por exemplo, n&atilde;o se usam utens&iacute;lios met&aacute;licos, o que sugere que o culto a estas divindades pode preceder a idade do ferro. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ao contr&aacute;rio dos orix&aacute;s iorubanos, que s&atilde;o alegres, ativos, que possuem caracter&iacute;sticas que os aproxima dos humanos, os orix&aacute;s do Daom&eacute; s&atilde;o s&eacute;rios, contemplativos, deixando clara sua superioridade aos homens e, quando estes vem a Terra, s&atilde;o ind&iacute;cios de grandes cat&aacute;strofes. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Com Obalua&ecirc; n&atilde;o &eacute; diferente. No passado foi temido por ser considerado o orix&aacute; da var&iacute;ola e das doen&ccedil;as epid&ecirc;micas. Em tempos de epidemias, todas as cidades faziam grandes oferendas a este orix&aacute;, na inten&ccedil;&atilde;o de afastar a doen&ccedil;a. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Mas Obalua&ecirc; hoje &eacute; visto pelo que &eacute;. Um orix&aacute; bondoso que ajuda a todos que precisam, entretanto, aqueles que merecerem sua f&uacute;ria, sentir&atilde;o o pranto e o ranger de dentes. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pelo lado de sua m&atilde;e biol&oacute;gica, recebeu o controle dos esp&iacute;ritos dos mortos (eguns), e de sua m&atilde;e adotiva, recebeu a guarda desses esp&iacute;ritos atrav&eacute;s da calunga. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Obalua&ecirc; rege as casas e postos de sa&uacute;de, as cl&iacute;nicas, hospitais, necrot&eacute;rios e cemit&eacute;rios, em suma, todos os lugares onde a dor, a doen&ccedil;a, o sofrimento e a morte se encontram. A este orix&aacute; &eacute; atribu&iacute;do o dom da vida e da morte, da cura e do alcance de toda sorte de b&ecirc;n&ccedil;&atilde;os. Seu poder maior &eacute; a transforma&ccedil;&atilde;o, a transmuta&ccedil;&atilde;o das coisas e dos seres, cujo s&iacute;mbolo m&aacute;ximo &eacute; a morte f&iacute;sica, que &eacute; a transforma&ccedil;&atilde;o da vida, passando a ser uma vida espiritual. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Atua na morte dos seres cortando o fio de prata que liga o perisp&iacute;rito ao corpo f&iacute;sico, e tamb&eacute;m &eacute; ele quem o liga no ato da reencarna&ccedil;&atilde;o. Ele &eacute; morte, mas tamb&eacute;m &eacute; vida. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Obalua&ecirc; &eacute; a terra dura e quente, como a febre das doen&ccedil;as infecciosas, mas mesmo nesse terreno in&oacute;spito Obalua&ecirc; faz a vida surgir, conduzindo e transformado nossos defeitos em virtudes. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Obalua&ecirc; &eacute; a morte para uma nova vida, &eacute; a sa&uacute;de, a prosperidade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Usa um capacete e roupa feita de palha da costa que n&atilde;o deixa vis&iacute;vel nem seu corpo e nem seu semblante. Algumas lendas dizem que Iemanj&aacute; preparou essa roupa para o filho, para que ele pudesse esconder seu defeitos e, principalmente, a lepra que carrega. Outras lendas dizem que a roupa existe para guardar os olhos de quem o v&ecirc;, pois se olh&aacute;ssemos diretamente para ele ser&iacute;amos cegados pela energia irradiada de seu corpo, semelhante a um sol. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Obalua&ecirc; sempre teve poder sobre os mortos, mas algumas correntes defendem que ele conheceu todos os oruns (c&eacute;us) e dominou todos os seus mist&eacute;rios, de forma a n&atilde;o haver entidade positiva ou negativa que o incomode em suas andan&ccedil;as pelo al&eacute;m. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; temido por todos os esp&iacute;ritos por possui o dom de converter um esp&iacute;rito em um ov&oacute;ide, o qual cola no teto de sua caverna enquanto considerar necess&aacute;rio. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Assim como Oxal&aacute; que se divide em Oxagui&atilde; (o novo) e Oxaluf&atilde; (o velho), este orix&aacute; cujo nome primeiro &eacute; Xapan&atilde;, divide-se em Obalua&ecirc;, o jovem e curador de doen&ccedil;as, e Omulu, o velho que dominou todos os segredos dos mortos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; tamb&eacute;m conhecido como padroeiro dos pobres, humildes e doentes. Quem pede com respeito e humildade a Obalua&ecirc;, &eacute; prontamente atendido. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A febre, a doen&ccedil;a (em especial as de pele e as contagiosas), cegueira e surdez, catapora, var&iacute;ola e sarampo, s&atilde;o consideradas manifesta&ccedil;&otilde;es deste orix&aacute; que somente age quando existe necessidade de purificar a humanidade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ainda todas as dores que sentimos, sem importar a origem, o calor abafado, a agonia, a ansiedade, a coceira e o mal funcionamento dos &oacute;rg&atilde;os tamb&eacute;m evidenciam a sua presen&ccedil;a. Obalua&ecirc; &eacute; a for&ccedil;a da natureza que rege o inc&ocirc;modo de um modo geral. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; protetor dos aleijados, mutilados, doentes mentais e de todos os enfermos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Enfim &eacute; o orix&aacute; da miseric&oacute;rdia. Est&aacute; ligado ao oculto com muita for&ccedil;a e muito temos para desvendar dessa for&ccedil;a da natureza. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O que pedir?</span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Invocamos Obalua&ecirc; em todos os momentos, principalmente em casos de doen&ccedil;as. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Caracter&iacute;sticas dos filhos de Obalua&ecirc; </span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Obalua&ecirc; s&atilde;o cautelosos e discretos, sempre presentes mas pouco notados. S&atilde;o r&uacute;sticos e desajeitados, faltando-lhes a diplomacia e o bom gosto. Ambiciosos e combativos, gostam de planos a longo prazo, e quase sempre alcan&ccedil;am seus objetivos. S&atilde;o perseverantes, gostam de estabilidade, tendo muita dificuldade para aceitar mudan&ccedil;as. S&atilde;o realistas, l&oacute;gicos, resignados, humildes, conservadores, e optam por uma vida de ren&uacute;ncia. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">N&atilde;o gostam de crian&ccedil;as, os homens n&atilde;o tem sorte com as mulheres e as mulheres n&atilde;o s&atilde;o boas m&atilde;es. Na vida profissional, s&atilde;o exigentes e meticulosos, possuindo grande senso de responsabilidade. Compreens&atilde;o, amizade e generosidade s&atilde;o qualidade que aparecem mais facilmente no ambiente de trabalho. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em desequil&iacute;brio s&atilde;o levados a esquisitices, vaidade exagerada, maldade, morbidez, intoler&acirc;ncia. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ocultam sua individualidade sob uma m&aacute;scara de austeridade. Socialmente s&atilde;o superficiais e intimamente s&atilde;o profundos e distantes. Apaixonam-se por pessoas totalmente diferentes de si, como figuras extrovertidas e sensuais, por exemplo. Normalmente s&atilde;o ir&ocirc;nicos, secos e diretos. N&atilde;o falam pelas costas e nem levam desaforos para casa. Odeiam fofocas. Gostam de solid&atilde;o. N&atilde;o se sentem satisfeitos quando a vida corre normalmente. Gostam de mostrar seu sofrimento, se bem que exageram um pouco neste quesito. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o muito independentes e tem a necessidade de crescer com suas pr&oacute;prias for&ccedil;as e recursos. Apresentam pouco brilho no rosto e semblante s&eacute;rio, com poucos momentos de descontra&ccedil;&atilde;o. Adoram fazer caridade e aliviar o sofrimento dos outros. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Outros Detalhes</span></span></strong></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sincretismo: S&atilde;o Roque (Omol&uacute;), S&atilde;o L&aacute;zaro (Obalua&ecirc;);</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Data de culto: 16 de agosto (S&atilde;o Roque), 17 de dezembro (obalua&ecirc;);</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o: Atot&ocirc; (Sil&ecirc;ncio, respeito); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Aacute;rea de atua&ccedil;&atilde;o: Vida, morte, cura e transforma&ccedil;&atilde;o;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Elemento: Terra; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chacra: B&aacute;sico;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Metal: Chumbo;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Astro regente: Saturno; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dia da semana: Segunda-feira (almas); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da guia: Preto e branco, em algumas casas lil&aacute;s ou violeta; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da vela: Preto e branco, em algumas casas lil&aacute;s ou violeta;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pedra: Obsediana, &ocirc;nix;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebida: &Aacute;gua mineral, vinho tinto, caf&eacute;; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Amal&aacute;: Feij&atilde;o preto, pipoca, amendoim torrado e pilado (abad&ocirc;); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Frutas: Abacaxi, laranja, maracuj&aacute;, uva preta;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Flores: Cris&acirc;ntemo branco, monsenhor branco, d&aacute;lias escuras; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas ervas: Eucalipto, guin&eacute; caboclo, folha de bananeira, erva de bicho, velame, agoniada, manjeric&atilde;o roxo, carobinha do campo, cord&atilde;o de frade, alfazema, cinco chagas, barba de velho;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local de oferta: Cemit&eacute;rios, grutas e praia;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Animais: Cachorro, caranguejo e galinha d&rsquo;angola; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Instrumentos: Xaxar&aacute; (cetro de palha da costa adornado com b&uacute;zios);</span></span></span></span></span></li>
</ul>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fontes: </span></span></span></span></span></p>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Marcio Kain, Curso de Teologia da Umbanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fl&aacute;vio Penteado, Povo de Aruanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ademir Jr, Teologia de Umbanda e suas dimens&otilde;es;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lurdes Vieira, Manual Doutrin&aacute;rio, Ritualistico e Comportamental Umbandista</span></span></span></span></span></li>

					</p>
					<a href="AUmbanda_OSORIXAS.php" class="btn btn-primary">&larr; Retornar aos Orixás</a>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 13/04/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>