<?php $results['pageTitle'] = "Oxóssi | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
			<img class="card-img-top" src="images/oxossi.jpg" alt="Card image cap">
				<h2 class="card-title"><center>OXÓSSI</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O nome Ox&oacute;ssi significa &ldquo;Ca&ccedil;ador Noturno&rdquo; ou &ldquo;Aquele que Ca&ccedil;a &agrave; Noite&rdquo;. Tamb&eacute;m conhecido por Od&eacute;, Ox&oacute;ssi &eacute; o Orix&aacute; das matas e das florestas. Respons&aacute;vel pelo sustento, conhecimento, agricultura e fartura. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Filho de Oxal&aacute; e Iemanj&aacute;, irm&atilde;o de Exu e de Ogum, sendo este &uacute;ltimo o seu irm&atilde;o mais pr&oacute;ximo e querido. Foi Ogum quem o presenteou com suas armas, o arco e a flecha. Algumas lendas dizem que Ox&oacute;ssi e Ogum lutaram muitas batalhas, e, dessa forma, teria Ox&oacute;ssi ajudado Ogum a levar o desenvolvimento para os homens. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Por este motivo muitos consideram Ogum e Ox&oacute;ssi os maiores guerreiros do pante&atilde;o africano, sendo que suas for&ccedil;as unidas s&atilde;o imbat&iacute;veis. Por este motivo, em muitos terreiros, quando o filho de f&eacute; &eacute; batizado, ele recebe b&ecirc;n&ccedil;&atilde;o especial de Ogum e Ox&oacute;ssi para que nunca lhe falte prote&ccedil;&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Conhecido como o ca&ccedil;ador de uma flecha s&oacute;, ou aquele que n&atilde;o &eacute; detido pelos caminhos fechados, Ox&oacute;ssi demonstra atrav&eacute;s dessas alcunhas seu poder de atua&ccedil;&atilde;o que faz com que ele alcance qualquer objetivo por mais imposs&iacute;vel que pare&ccedil;a. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Vive nas matas fechadas, onde recebe suas oferendas. L&aacute; domina os esp&iacute;ritos da floresta. Conhece toda a fauna e a flora, da qual tamb&eacute;m &eacute; guardi&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Muito ligado a vida, &agrave; liberdade, Ox&oacute;ssi n&atilde;o se submete facilmente, tendo &agrave;s vezes muitos problemas com hierarquia. Suas habilidades com ca&ccedil;a exigem qualidades como orienta&ccedil;&atilde;o, decis&atilde;o, concentra&ccedil;&atilde;o, determina&ccedil;&atilde;o e paci&ecirc;ncia, atributos que constantemente s&atilde;o transferidos para seus filhos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Eacute; tamb&eacute;m conhecido como aquele que vive na casa de barro ou na casa de folhas, o que denota claramente sua simplicidade. Al&eacute;m de simples &eacute; o mais honesto de todos os Orix&aacute;s. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">De comportamento arredio, Ox&oacute;ssi gosta de estar em contato com a natureza, evitando lugares com muita gente e principalmente grandes multid&otilde;es, o que, no entanto, n&atilde;o o impede de se socializar com as pessoas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ox&oacute;ssi era cultuado principalmente no Estado de Ketu, onde chegou a receber o t&iacute;tulo de rei. Entretanto, no final do s&eacute;culo XIX, Ketu foi destru&iacute;do pelas for&ccedil;as do estado vizinho, o Daom&eacute;. Aqueles que n&atilde;o forma mortos foram escravizados e levados para o Brasil, Cuba e Antilhas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Isto fez com que o culto &agrave; Ox&oacute;ssi praticamente desaparecesse na &Aacute;frica, segundo Pierre Verger. Entretanto, seus filhos mantiveram viva a chama da cultura Ketu, o que fez com que Ketu ressurgisse, n&atilde;o mais como estado pol&iacute;tico, mas como uma grande na&ccedil;&atilde;o religiosa do Candombl&eacute;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Foi provavelmente o Orix&aacute; mais dif&iacute;cil de sincretizar, por n&atilde;o haver santos cat&oacute;licos com o perfil de ca&ccedil;ador. S&atilde;o Sebasti&atilde;o, cuja imagem demonstra um tronco possivelmente associado &agrave;s matas e um homem com v&aacute;rias flechas (que era a arma de Ox&oacute;ssi), acabou sendo o escolhido para ser associado a este Orix&aacute;. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No Brasil, este Orix&aacute; &eacute; muito popular, sendo muito cultuado principalmente em S&atilde;o Paulo, Rio de Janeiro, Bahia e Rio Grande do Sul. Para o Candombl&eacute;, Ox&oacute;ssi &eacute; considerado o patrono de todos os terreiros tradicionais. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Na Umbanda, &eacute; o grande regente da Linha dos Caboclos, que vem a ser a linha mais ativa e importante da religi&atilde;o, cujo representante maior &eacute; o Caboclo das Sete Encruzilhadas, que era diretamente um caboclo de Ox&oacute;ssi. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em qualquer refei&ccedil;&atilde;o encontramos Ox&oacute;ssi, pois &eacute; ele quem prov&ecirc; o alimento. Na &Aacute;frica, era considerado o protetor dos ca&ccedil;adores, pois traziam o sustento para a tribo. Hoje em dia aben&ccedil;oa a todos aqueles que v&atilde;o para o trabalho para defender o sustento de suas casas. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O que pedir?</span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Recorremos &agrave; Ox&oacute;ssi para obter emprego, fartura e prosperidade. &Eacute; protetor das matas e florestas, da ca&ccedil;a e dos ca&ccedil;adores. Objetivos extremamente dif&iacute;ceis de serem alcan&ccedil;ados (ou imposs&iacute;veis) tamb&eacute;m s&atilde;o solicitados a ele. Rege o estudo e a concentra&ccedil;&atilde;o. Pode ser invocado tamb&eacute;m como protetor de todas as manifesta&ccedil;&otilde;es art&iacute;sticas. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Caracter&iacute;sticas dos filhos de Ox&oacute;ssi </span></span></strong></span></span></span></li>
</ul>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Os filhos de Ox&oacute;ssi s&atilde;o normalmente joviais, r&aacute;pidos e espertos, tanto mental quanto fisicamente. Como seu pai ca&ccedil;ador, s&atilde;o dotados de extrema aten&ccedil;&atilde;o, concentra&ccedil;&atilde;o e determina&ccedil;&atilde;o para buscar seus objetivos, al&eacute;m de paci&ecirc;ncia para saber aguardar o momento da colheita. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o extremamente independentes e pouco apegados &agrave;s pessoas. Quando em busca de seus objetivos, ficam facilmente distantes daqueles que amam. Gostam de coisas materiais e mesmo do luxo, sem criar nenhuma depend&ecirc;ncia. S&atilde;o s&eacute;rios e respons&aacute;veis. Reservados, gostam de solid&atilde;o. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Quando equilibrados s&atilde;o amantes da liberdade, companheiros, sens&iacute;veis. Em desequil&iacute;brio s&atilde;o irrespons&aacute;veis e vingativos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">S&atilde;o curiosos e donos de um poder de observa&ccedil;&atilde;o impressionante. S&atilde;o devotados &agrave; casa e &agrave; fam&iacute;lia. No cotidiano s&atilde;o am&aacute;veis, educados, calmos e normalmente muito queridos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Simbolizam um dos tipos masculinos mais atraentes, sendo normalmente esbeltos, &aacute;geis, finos, rom&acirc;nticos e carinhosos. Os homens de Ox&oacute;ssi exercem fasc&iacute;nio sobre as mulheres e at&eacute; sobre alguns homens. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Gostam de ajudar os outros, de roupas e de tudo o que &eacute; pr&aacute;tico, gostam de dormir e podem ser um pouquinho pregui&ccedil;osos. S&atilde;o francos e rancorosos. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O lado emocional do filho de Ox&oacute;ssi vem &agrave; tona com muita facilidade. Quando se apaixonam, largam tudo por amor. Por esta certa fragilidade emocional, n&atilde;o demonstram facilmente suas emo&ccedil;&otilde;es. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Desconfiados, cautelosos, inteligentes. Escolhem suas amizades justamente por n&atilde;o conseguir confiar em ningu&eacute;m. Entretanto, s&atilde;o extremamente confi&aacute;veis. S&atilde;o criativos e frequentemente desenvolvem habilidades em qualquer &aacute;rea da arte ou cultura. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">M&iacute;sticos e intuitivos, s&atilde;o misteriosos e cheios de manias e supersti&ccedil;&otilde;es. Falam bastante e tendem a ajuntar as m&atilde;os ao falar. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Como s&atilde;o inseguros e inconstantes, os relacionamentos dos filhos de Ox&oacute;ssi s&atilde;o tumultuados, raramente est&aacute;veis. Escolhem por companheiro ou companheira pessoas que partilhem com ele o amor pela liberdade e independ&ecirc;ncia. Entretanto, encara uma rela&ccedil;&atilde;o com a uni&atilde;o tempor&aacute;ria de duas partes, gosta de manter sua individualidade. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Podem desenvolver problemas de est&ocirc;mago, alguns dizem tamb&eacute;m problemas nas pernas. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Comunica&ccedil;&atilde;o, publicidade, desenho, artes e turismo s&atilde;o algumas das profiss&otilde;es apropriadas para os filhos de Ox&oacute;ssi. </span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Outros Detalhes</span></span></strong></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sincretismo: S&atilde;o Sebasti&atilde;o; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Data de culto: 20 de Janeiro; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sauda&ccedil;&atilde;o: Oke Ar&ocirc; (Salve aquele que est&aacute; no ponto mais alto); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Aacute;rea de atua&ccedil;&atilde;o: Subsist&ecirc;ncia, trabalho, demandas, determina&ccedil;&atilde;o, fartura;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Elemento: Terra; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Chacra: Espl&ecirc;nico; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Metal: Cobre e lat&atilde;o; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Astro regente: V&ecirc;nus; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dia da semana: Quinta-feira; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da guia: Verde;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cor da vela: Verde;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Pedra: Esmeralda, amazonita, calcita verde, quartzo verde;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Bebida: Cerveja branca, vinho tinto, &aacute;gua de coco, caldo de cana; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Amal&aacute;: Milho cozido, mandioca assada, frutas;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Frutas: Abacate, ameixa, coco, milho verde, laranja, lim&atilde;o, caju, acerola;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Flores: Flores do campo, palmas; </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algumas ervas: Erva-doce, eucalipto, folhas de jurema, guin&eacute; caboclo, mangueira, sai&atilde;o, samambaia, peregum verde, sabugueiro, malva cjeirosa, malvarisco, cip&oacute; caboclo, dracena, taioba;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Local de oferta: Matas (preferencialmente as virgens ou fechadas); </span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Animais: Porco do mato e aves malhadas;</span></span></span></span></span></li>
	<li style="margin-left: 0cm; margin-right: 0cm; text-align: justify;"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Instrumentos: Of&aacute; (arco e flecha);</span></span></span></span></span></li>
</ul>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fontes: </span></span></span></span></span></p>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Marcio Kain, Curso de Teologia da Umbanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Fl&aacute;vio Penteado, Povo de Aruanda;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ademir Jr, Teologia de Umbanda e suas dimens&otilde;es;</span></span></span></span></span></li>

<li style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><span style="font-size:10.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lurdes Vieira, Manual Doutrin&aacute;rio, Ritualistico e Comportamental Umbandista</span></span></span></span></span></li>

					</p>
					<a href="AUmbanda_OSORIXAS.php" class="btn btn-primary">&larr; Retornar aos Orixás</a>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 13/04/2019
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>