<?php $results['pageTitle'] = "A História da Umbanda | Tenda de Umbanda Pai Benedito da Guiné";
include "templates/include/header.php" ?>

    <ul class="col-sm-12" id="headlines">
		<!-- Blog Post -->
		<br>
		<br>
        <div class="card mb-4">
			<div class="card-body">
				<h2 class="card-title"><center>A HISTÓRIA DA UMBANDA</center></h2>
					<p class="card-text">
						<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Funda&ccedil;&atilde;o da Umbanda</span></span></span></strong></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No final de 1908, Z&eacute;lio Fernandino de Moraes, um jovem rapaz com 17 anos de idade, que se preparava para ingressar na carreira militar, Marinha, come&ccedil;ou a sofrer estranhos ataques. Sua fam&iacute;lia, conhecida e tradicional na cidade de Neves, Estado do Rio de Janeiro, foi pega de surpresa pelos acontecimentos.</span></span></span></span></span></p>

<img src="images/zelio-fernandino-de-moraes.jpg" style="padding: 0 15px;float:right; width:270px;height: 250px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Esses &ldquo;ataques&rdquo; do rapaz eram caracterizados por posturas de um velho, falando coisas sem sentido e desconexas, como se fosse uma pessoa que havia vivido em outra &eacute;poca. Muitas vezes assumia uma forma que parecia a de um felino l&eacute;pido e desembara&ccedil;ado, que mostrava conhecer muitas coisas da natureza.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Como os &ldquo;ataques&rdquo; estavam se agravando, a fam&iacute;lia recorreu ao Dr. Epaminondas de Moraes, m&eacute;dico da fam&iacute;lia e tio de Z&eacute;lio, que era diretor da &ldquo;Col&ocirc;nia de Alienados&rdquo; em Vargem Alegre. Ap&oacute;s examin&aacute;-lo e observ&aacute;-lo durante v&aacute;rios dias, reencaminhou-o &agrave; fam&iacute;lia, dizendo que a loucura n&atilde;o se enquadrava em nada do que ele havia conhecido, ponderando ainda, que melhor seria encaminh&aacute;-lo a um padre, pois o garoto mais parecia estar endemoniado. Como acontecia com quase todas as fam&iacute;lias importantes da &eacute;poca, tamb&eacute;m havia na fam&iacute;lia Moraes um sacerdote cat&oacute;lico. Atrav&eacute;s desse padre, tio de Z&eacute;lio, foi realizado um exorcismo, sem o sucesso esperado, pois os chamados &ldquo;ataques&rdquo; prosseguiam, apesar de tudo.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Depois de algum tempo, Z&eacute;lio passou alguns dias com uma esp&eacute;cie de paralisia, prendendo-o a cama, sendo levado por sua m&atilde;e a uma benzedeira, que, segundo relatos, era m&eacute;dium de um Esp&iacute;rito chamado tio Ant&ocirc;nio.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algu&eacute;m sugeriu que &ldquo;isso era coisa de espiritismo&rdquo; e que era melhor lev&aacute;-lo &agrave; Federa&ccedil;&atilde;o Esp&iacute;rita de Niter&oacute;i (segundo relatos, essa Federa&ccedil;&atilde;o era dirigida por Jos&eacute; de Souza), munic&iacute;pio vizinho &agrave;quele em que residia a fam&iacute;lia Moraes, pois era presumido que &agrave;queles fen&ocirc;menos estariam ligados a manifesta&ccedil;&otilde;es de entidades sobrenaturais. </span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Depois de algum tempo, Z&eacute;lio passou alguns dias com uma esp&eacute;cie de paralisia, prendendo-o a cama, sendo levado por sua m&atilde;e a uma benzedeira, que, segundo relatos, era m&eacute;dium de um Esp&iacute;rito chamado tio Ant&ocirc;nio.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Algu&eacute;m sugeriu que &ldquo;isso era coisa de espiritismo&rdquo; e que era melhor lev&aacute;-lo &agrave; Federa&ccedil;&atilde;o Esp&iacute;rita de Niter&oacute;i (segundo relatos, essa Federa&ccedil;&atilde;o era dirigida por Jos&eacute; de Souza), munic&iacute;pio vizinho &agrave;quele em que residia a fam&iacute;lia Moraes, pois era presumido que &agrave;queles fen&ocirc;menos estariam ligados a manifesta&ccedil;&otilde;es de entidades sobrenaturais.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&ldquo;...Vim para criar uma nova religi&atilde;o, baseada no Evangelho de Jesus e que ter&aacute; como seu maior mentor o Cristo...&rdquo; </span></span></strong></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:right"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="color:black"><strong><span style="font-size:14.0pt"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">(Caboclo das Sete Encruzilhadas)</span></span></strong></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No dia 15 de novembro, o jovem Z&eacute;lio foi convidado a participar de uma sess&atilde;o, esp&iacute;rita ocupando um lugar &agrave; mesa. Tomado por uma for&ccedil;a estranha, alheia a sua vontade, e contrariando as normas, que impediam o afastamento de qualquer dos componentes da mesa, Z&eacute;lio levantou-se e disse: &ldquo;Aqui est&aacute; faltando uma flor&rdquo;. Saiu da sala, indo ao jardim, voltou com uma flor, que colocou no centro da mesa. Essa atitude causou um enorme tumulto entre os presentes. Restabelecidos os trabalhos, manifestaram-se nos m&eacute;diuns &ldquo;Kardecistas&rdquo; esp&iacute;ritos que se diziam negros, escravos e &iacute;ndios. O diretor dos trabalhos achou aquilo tudo um absurdo e advertiu-os com aspereza, citando o seu atraso espiritual e convidando-os a se retirarem da sess&atilde;o.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ap&oacute;s esse incidente, novamente uma for&ccedil;a estranha tomou o jovem Z&eacute;lio e atrav&eacute;s dele falou: Por que repelem a presen&ccedil;a desses esp&iacute;ritos, se nem sequer se dignaram a ouvir suas mensagens? Ser&aacute; por causa de suas origens sociais e da cor?</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Seguiu-se um di&aacute;logo acalorado, e os respons&aacute;veis pela sess&atilde;o procuravam doutrinar e afastar o esp&iacute;rito desconhecido, que desenvolvia uma argumenta&ccedil;&atilde;o segura.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Um m&eacute;dium clarividente perguntou: Por que o irm&atilde;o fala nestes termos, pretendendo que a dire&ccedil;&atilde;o aceite a manifesta&ccedil;&atilde;o de esp&iacute;ritos que, pelo grau de cultura que tiveram, quando encarnados, s&atilde;o claramente atrasados? Por que fala desse modo, se estou vendo que me dirijo neste momento a um jesu&iacute;ta e a sua veste branca reveste uma aura de luz? E qual o seu nome irm&atilde;o?</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Se querem um nome, que seja este: sou o Caboclo das Sete Encruzilhadas, porque para mim, n&atilde;o haver&aacute; caminhos fechados. O que voc&ecirc; v&ecirc; em mim s&atilde;o &ldquo;restos&rdquo; de uma exist&ecirc;ncia anterior. Fui padre e o meu nome era Gabriel Malagrida. Acusado de bruxaria, fui sacrificado na fogueira da Inquisi&ccedil;&atilde;o, em Lisboa, no ano de 1761. Mas, em minha &uacute;ltima exist&ecirc;ncia f&iacute;sica, Deus concedeu-me o privil&eacute;gio de nascer como caboclo (&iacute;ndio) brasileiro.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Anunciou tamb&eacute;m o tipo de miss&atilde;o que trazia do Astral: &ldquo;Se julgam atrasados os esp&iacute;ritos de pretos e &iacute;ndios, devo dizer que amanh&atilde;, 16 de novembro, estarei na casa do meu aparelho (m&eacute;dium), &agrave;s 20 horas, para dar in&iacute;cio a um culto em que estes irm&atilde;os poder&atilde;o dar suas mensagens e, assim, cumprir a miss&atilde;o que o Plano Espiritual lhes confiou. Ser&aacute; uma religi&atilde;o que falar&aacute; aos humildes, simbolizando a igualdade que deve existir entre todos os irm&atilde;os, encarnados e desencarnados&rdquo;.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O clarividente retrucou: Julga o irm&atilde;o que algu&eacute;m ir&aacute; assistir ao seu culto? _ perguntou com ironia. E o esp&iacute;rito j&aacute; identificado respondeu: &ldquo;Cada colina de Niter&oacute;i atuar&aacute; como porta-voz, anunciando o culto que amanh&atilde; iniciarei&rdquo;.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Para finalizar o caboclo completou: <strong><em>Deus, em sua infinita Bondade, estabeleceu na morte o grande nivelador universal; rico ou pobre, poderoso ou humilde, todos se tornariam iguais na morte, mas voc&ecirc;s, homens preconceituosos, n&atilde;o contentes em estabelecer diferen&ccedil;as entre os vivos, procuram levar essas mesmas diferen&ccedil;as at&eacute; al&eacute;m da barreira da morte.</em></strong> Porque n&atilde;o podem nos visitar esses humildes trabalhadores do espa&ccedil;o, se apesar de n&atilde;o haverem sido pessoas socialmente importantes na Terra, tamb&eacute;m trazem importantes mensagens do al&eacute;m?</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No dia seguinte, na casa da fam&iacute;lia Moraes, na rua Floriano Peixoto, n&uacute;mero 30, ao se aproximar da hora marcada, l&aacute; j&aacute; estavam reunidos os membros da Federa&ccedil;&atilde;o Esp&iacute;rita para comprovarem a veracidade do que fora declarado na v&eacute;spera; estavam os parentes mais pr&oacute;ximos, amigos, vizinhos e, do lado de fora, uma multid&atilde;o de desconhecidos.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&Agrave;s vinte horas manifestou-se o Caboclo das Sete Encruzilhadas. Declarou que naquele momento se iniciava um novo culto, em que os esp&iacute;ritos de velhos africanos que haviam sido escravos e que, desencarnados, n&atilde;o encontravam campo de atua&ccedil;&atilde;o nos remanescentes das seitas negras, j&aacute; deturpadas e dirigidas em sua totalidade para os trabalhos de feiti&ccedil;aria, e os &iacute;ndios nativos de nossa terra poderiam trabalhar em benef&iacute;cio de seus irm&atilde;os encarnados, qualquer que fosse a cor, a ra&ccedil;a, o credo e a condi&ccedil;&atilde;o social.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A pr&aacute;tica da caridade no sentido do amor fraterno, seria a caracter&iacute;stica principal desse culto, que teria por base o evangelho de Jesus.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O caboclo estabeleceu as normas em que se processariam o culto. Sess&otilde;es, assim seriam chamados os per&iacute;odos de trabalho espiritual di&aacute;rios das 20h &agrave;s 22h; os participantes estariam uniformizados de branco e o atendimento seria gratuito. Deu, tamb&eacute;m, o nome do movimento religioso que se iniciava: Umbanda &ndash; A manifesta&ccedil;&atilde;o do esp&iacute;rito para a caridade.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">A casa de trabalhos espirituais que ora se fundava, recebeu o nome de Nossa Senhora da Piedade, porque assim como Maria acolheu o filho nos bra&ccedil;os, tamb&eacute;m seriam acolhidos como filhos todos os que necessitavam de ajuda ou de conforto.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ditadas as bases do culto, ap&oacute;s responder em latim e alem&atilde;o &agrave;s perguntas dos sacerdotes ali presentes, o Caboclo das Sete Encruzilhadas passou a parte pr&aacute;tica dos trabalhos.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">O Caboclo foi atender um paral&iacute;tico, fazendo este ficar curado. Passou a atender outras pessoas que havia neste local praticando suas curas.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Neste mesmo dia, o jovem Z&eacute;lio incorporou um preto-velho chamado Pai Ant&ocirc;nio, aquele que, com fala mansa, foi confundido como loucura do m&eacute;dium. Com palavras de muita sabedoria, humildade e com timidez aparente, recusava-se a sentar junto com os presentes &agrave; mesa dizendo as seguintes palavras: <em>N&ecirc;go num senta n&atilde;o meu sinh&ocirc;, n&ecirc;go fica aqui mesmo. Isso &eacute; coisa de sinh&ocirc; branco e nego deve arrespeit&aacute;.</em></span></span></span></span></span></p>

<img src="images/pai_antonio.jpg" style="padding: 0 15px;float:left; width:270px;height: 250px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Ap&oacute;s insist&ecirc;ncia dos presentes fala: <em>Num carece preocup&aacute; n&atilde;o. N&ecirc;go fica no toco que &eacute; lug&aacute; di nego</em>. Assim continuou dizendo outras palavras representando a sua humildade. Uma pessoa na reuni&atilde;o pergunta se ele sentia falta de alguma coisa que tinha deixado na Terra e ele responde: <em>Minha caximba. Nego qu&eacute; o pito que deixou no toco. Manda mureque busc&aacute;.</em> Tal afirmativa deixou os presentes perplexos, os quais estavam presenciando a solicita&ccedil;&atilde;o do primeiro elemento de trabalho para esta religi&atilde;o. Foi Pai Ant&ocirc;nio, tamb&eacute;m, a primeira entidade a solicitar uma guia, at&eacute; hoje usadas pelos membros da Tenda e carinhosamente chamada de &ldquo;Guia de Pai Ant&ocirc;nio&rdquo;.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">No dia seguinte, verdadeira romaria formou-se na Rua Floriano Peixoto. Enfermos, cegos etc. vinham em busca de cura e ali a encontravam, em nome de Jesus. M&eacute;diuns, cuja manifesta&ccedil;&atilde;o medi&uacute;nica fora considerada loucura, deixaram os sanat&oacute;rios e deram provas de suas qualidades excepcionais. A partir da&iacute; o Caboclo das Sete Encruzilhadas come&ccedil;ou a trabalhar incessantemente para o esclarecimento, difus&atilde;o e sedimenta&ccedil;&atilde;o da religi&atilde;o Umbanda. Al&eacute;m de Pai Ant&ocirc;nio, tinha como auxiliar o Caboclo Orix&aacute; Mal&eacute;, entidade com grande experi&ecirc;ncia no &ldquo;desmanche&rdquo; de trabalhos de magia.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Em 1918, o Caboclo das Sete Encruzilhadas recebeu ordens do Astral Superior para fundar sete tendas para a propaga&ccedil;&atilde;o da Umbanda. As agremia&ccedil;&otilde;es ganharam os seguintes nomes:</span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tenda Esp&iacute;rita Nossa Senhora da Guia;</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tenda Esp&iacute;rita Nossa Senhora da Concei&ccedil;&atilde;o;</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tenda Esp&iacute;rita Santa B&aacute;rbara;</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tenda Esp&iacute;rita S&atilde;o Pedro;</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tenda Esp&iacute;rita Oxal&aacute;;</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tenda Esp&iacute;rita S&atilde;o Jorge;</span></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Tenda Esp&iacute;rita S&atilde;o Jer&ocirc;nimo.</span></span></span></span></span></li>
</ul>

<img src="images/tenda_piedade.png" style="padding: 0 15px;float:right; width:270px;height: 250px;"></img>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Conta-se que enquanto Z&eacute;lio estava encarnado, foram fundadas mais de 10.000 tendas a partir das mencionadas.</span></span></span></span></span></p>

<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Embora n&atilde;o seguindo a carreira militar para a qual se preparava, pois, sua miss&atilde;o medi&uacute;nica n&atilde;o o permitiu, Z&eacute;lio nunca fez da religi&atilde;o sua profiss&atilde;o. Trabalhava para o sustento de sua fam&iacute;lia e diversas vezes contribuiu financeiramente para manter os templos que o Caboclo das Sete Encruzilhadas fundou, al&eacute;m das pessoas que se hospedavam em sua casa para os tratamentos espirituais, que, segundo o que dizem, parecia um albergue. Nunca aceitara ajuda monet&aacute;ria de ningu&eacute;m.</span></span></span></span></span></p>

<p style="text-align:justify"><span style="font-size:14.0pt"><span style="background-color:white"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Era ordem do seu guia chefe, apesar de in&uacute;meras vezes isso ter sido oferecido a ele. Ministros, industriais e militares recorriam ao poder medi&uacute;nico de Z&eacute;lio para a cura de parentes enfermos e os vendo recuperados procuravam retribuir o benef&iacute;cio atrav&eacute;s de presentes ou preenchimento de cheques vultosos. &ldquo;N&atilde;o os aceite. </span></span></span></p>

					</p>
            </div>
            <div class="card-footer text-muted">
				Atualizado pela última vez em 26/11/2018
				<br>
            </div>
        </div>
    </ul>

<?php include "templates/include/footer.php" ?>